# -*- coding: utf-8 -*-
"""Safety & environment — inherent safety, waste, tritium, proliferation, footprint."""

def register(cat, page, F):
    cat("safety", "Safety & Environment",
        "Why fusion is inherently safe, what its waste and footprint really are, and how "
        "Kronos treats the honest environmental questions rather than hand-waving them.", 11)

    P = [
     ("inherent-safety","Why Fusion Is Inherently Safe","There is no chain reaction and only seconds of fuel in the machine; any fault simply stops the plasma.",
      "Fusion's safety is not a system bolted on — it is physics. There is nothing to run away.",
      [('p',"A fusion plasma holds only a tiny, continuously-supplied amount of fuel and depends on precisely maintained conditions. Anything that perturbs it — a power loss, a leak, a fault — makes it cool and extinguish within seconds. There is no chain reaction, no critical mass, and no stored energy that can drive a runaway."),
       ('p',"The burner adds a further margin: as a linear mirror it has none of the tokamak's disruption failure mode."),
       ('gap',("The honest limit","'Inherently safe' refers to the fusion process. Like any industrial plant, a fusion facility still has conventional hazards — high fields, cryogens, and, on the breeder, tritium — which are engineered and licensed accordingly."))],
      [("Chain reaction","None"),("Fuel in machine","Seconds' worth"),("Meltdown pathway","None")],
      ["can-a-fusion-plant-melt-down","tritium-safety","fusion-vs-fission"]),
     ("fusion-waste","Fusion's Waste Profile","No long-lived high-level waste; activated structure that low-activation materials keep short-lived.",
      "Fusion's waste question is real but bounded — and far smaller than fission's.",
      [('p',"Fusion produces no long-lived high-level waste and no spent fuel. Its waste is activated structural material — metal made mildly radioactive by neutrons. Choosing low-activation steels keeps that material's radioactivity short-lived, decaying to hands-on levels in decades rather than millennia."),
       ('p',f"The breeder, being neutron-rich ({F['b_fn']}), carries most of this; the burner far less ({F['u_fn']}). Kronos screens activation and waste class per component rather than assuming the problem away."),
       ('gap',("Studied, not assumed","Kronos treats waste volumes and activation as a screening study with honest uncomputed items, not a solved footnote."))],
      [("High-level waste","None"),("Waste type","Activated structure"),("Mitigation","Low-activation materials")],
      ["activation-products","low-activation-steel","fusion-vs-fission"]),
     ("tritium-safety","Tritium Safety","Tritium is managed with low inventories, permeation barriers and monitoring — a handled hazard, stated plainly.",
      "Tritium is the breeder's one genuinely radioactive material. Kronos names it and engineers for it.",
      [('p',f"Tritium is a low-energy beta emitter that is hazardous chiefly if inhaled or ingested. Plants manage it by keeping inventories low (HYPERION's startup inventory is {F['b_startup']}), using permeation barriers, multiple containment, and continuous monitoring."),
       ('p',"Because the burner runs low-neutron D–&sup3;He, tritium handling is overwhelmingly a breeder consideration, not a burner one."),
       ('gap',("Licensing-relevant","Tritium handling and accountancy are among the breeder's named gate items, treated as a real licensing task."))],
      [("Isotope","Radioactive hydrogen"),("Startup inventory (breeder)",F["b_startup"]),("Burner tritium","Minimal")],
      ["tritium","tritium-permeation","tritium-inventory"]),
     ("no-proliferation","Fusion and Non-Proliferation","Fusion produces no plutonium or enriched uranium; its proliferation profile is fundamentally different from fission.",
      "Fusion does not make bomb material as a by-product. That is a structural advantage.",
      [('p',"A fusion plant produces no plutonium and requires no enriched uranium; its fuels are hydrogen isotopes and helium-3. The proliferation concerns that shadow fission simply do not arise in the same way."),
       ('gap',("The honest caveat","A high neutron flux can in principle be misused to breed materials; this is a safeguards-and-siting consideration handled by design and oversight, and Kronos does not pretend the topic is empty."))],
      [("Plutonium","None"),("Enriched uranium","Not required")],
      ["can-fusion-be-used-for-weapons","inherent-safety","the-neutron-economy"]),
     ("can-fusion-be-used-for-weapons","Can Fusion Be Used for Weapons?","No — a power plant's slow, low-density plasma is the opposite of what a weapon needs.",
      "The short answer is no, and the reason is physics, not policy.",
      [('p',"A fusion power plant runs a low-density plasma in near-steady state — precisely the wrong conditions for the explosive, ultra-fast, ultra-dense reaction a weapon requires. The plant cannot be operated as a weapon."),
       ('gap',("Safeguards still apply","The materials and neutron flux are subject to normal safeguards and export controls, which Kronos treats as part of responsible deployment."))],
      [("Weapon pathway","None from operation")],
      ["no-proliferation","inherent-safety","fusion-waste"]),
     ("water-use","Fusion and Water Use","Cooling water needs are conventional-plant scale; the burner's direct conversion can reduce them.",
      "Water is a real siting question for any thermal plant. Kronos reports it rather than skipping it.",
      [('p',"Like other thermal generators, the breeder rejects waste heat and needs cooling. The burner's direct energy conversion recovers energy without a full steam cycle, which can reduce cooling-water demand — a genuine siting advantage worth stating precisely rather than overselling."),
       ('gap',("Screening study","Water and waste footprints are part of Kronos's environmental screening, with honest uncomputed items flagged."))],
      [("Breeder","Thermal-plant cooling"),("Burner","Reduced via direct conversion")],
      ["carnot-efficiency","direct-energy-conversion","land-use"]),
     ("land-use","Fusion and Land Use","Compact, high-density generation with a small footprint per megawatt.",
      "A compact fusion plant packs a great deal of firm power into a small footprint.",
      [('p',"High-field, compact machines generate large, firm power from a small site, with none of the land intensity of intermittent sources. The burner's point-of-use, low-neutron character further eases siting near demand."),
       ('gap',("Not yet built","Footprint figures are design-stage estimates for machines that do not yet exist."))],
      [("Character","Compact, high-density"),("Siting","Point-of-use (burner)")],
      ["metrovolt","baseload-power","water-use"]),
     ("fusion-carbon-footprint","Fusion's Carbon Footprint","Zero-carbon in operation; the honest question is embodied carbon in construction.",
      "Fusion emits no carbon while running. Kronos points the real question at construction, where it belongs.",
      [('p',"A fusion plant emits no CO&sub2; in operation — its fuel is hydrogen isotopes. The meaningful lifecycle question is embodied carbon in materials and construction, common to all built infrastructure, which Kronos includes in its environmental screening rather than claiming a free pass."),
       ('gap',("Lifecycle, not just operation","Kronos frames its environmental case on a full lifecycle basis, with the embodied-carbon screening among the honestly-flagged items."))],
      [("Operational CO2","Zero"),("Lifecycle","Embodied carbon in construction")],
      ["fusion-waste","water-use","fusion-vs-fission"]),
    ]
    for slug,title,desc,lede,body,facts,rel in P:
        page(slug,title,"safety",desc,lede,body,facts=facts,related=rel,jtype="TechArticle")
