# -*- coding: utf-8 -*-
"""Glossary depth batch E — nuclear, materials engineering, magnets, plant."""
def register(cat, page, F, enrich):
    G = {
     "binding-energy": "The binding-energy-per-nucleon curve peaks near iron, so fusing light nuclei toward that peak releases energy while splitting heavy ones does the same from the other side. Fusion sits on the steep, low-mass part of the curve, which is why merging deuterium and tritium yields millions of times more energy per reaction than any chemical bond.",
     "the-dt-reaction": f"Conservation of momentum hands the light neutron 14.1 MeV and the helium 3.5 MeV, and that split is the whole architecture of the breeder: the neutron carries its energy out to breed tritium and deposit heat, while the confined helium heats the plasma. It is also why the breeder is deliberately neutron-rich at {F['b_fn']}.",
     "the-dhe3-reaction": f"Because D–&sup3;He releases its 18.3 MeV almost entirely as charged particles, its energy can be recovered by direct conversion instead of a steam cycle — the physical basis for the burner's Q<sub>E</sub> = {F['u_QE']}. Side D–D reactions still emit some neutrons, giving the {F['u_fn']} fraction that keeps Kronos honest about calling it low-neutron rather than aneutronic.",
     "neutron-flux": f"Neutron flux sets both value and damage: it drives the tritium breeding rate in the blanket and the degradation rate in structures. The breeder's {F['b_Pn']} of neutron power makes its flux the dominant design driver, treated as a product to be captured rather than merely a hazard to be shielded.",
     "neutron-wall-loading": f"Neutron wall loading — the fusion-neutron power per square metre on the first wall — combines with the neutron spectrum to set the damage rate and component lifetime. HYPERION's {F['b_wall']} is a real, stated number that drives its materials and maintenance planning; the burner's is far gentler thanks to its low neutron fraction.",
     "dpa": "Displacements-per-atom counts how many times, on average, each atom has been knocked from its lattice site by neutrons — the standard yardstick for radiation damage. It accumulates with fluence and, together with helium and hydrogen production, sets how long a component survives before it must be replaced, especially at the breeder's first wall.",
     "activation-products": "Fusion neutrons transmute structural atoms into radioactive isotopes, and the whole low-activation materials strategy exists to ensure those isotopes are short-lived and low-hazard. Choosing steels whose decay chains relax to hands-on levels in decades rather than millennia is what keeps fusion's waste bounded and manageable.",
     "tritium": f"Tritium is a low-energy beta emitter with a ~12-year half-life, hazardous mainly if inhaled or ingested and essentially absent in nature. The breeder makes its own — {F['b_T']}/yr at breeding ratio {F['b_TBR']} — managed with low inventories, permeation barriers and continuous monitoring, which turns the tritium-supply problem into a feature.",
     "helium-3": f"Helium-3 is a rare, non-radioactive isotope valued for quantum computing, neutron detection and medical imaging as well as fusion fuel. The breeder co-produces about {F['b_He3']}/yr, giving Kronos an internal terrestrial supply and a strategic position in a genuinely constrained material — value Kronos frames as strategic rather than near-term revenue.",
     "deuterium": "Deuterium is a stable, abundant hydrogen isotope separated from water at industrial scale, and it is a component of every Kronos fuel — D–T, D–&sup3;He and D–D. Its abundance is why fuel supply is never the constraint fusion faces; the scarce inputs are tritium (bred in the blanket) and helium-3 (co-produced by the breeder).",
     "lorentz-force": "A current in a magnetic field feels the Lorentz force, and in a high-field magnet those forces are immense, producing hoop stresses the structure must contain. They are the origin of the magnet's fatigue gate: a single cycle is safe, but the cyclic loading of repeated operation is what must be proven for the burner's high-field plug.",
     "hoop-stress": "Like pressure in a pipe, the Lorentz forces in a magnet create hoop stress that tries to expand the coil, and containing it drives the choice of high-strength cryogenic alloys and a robust case. Bore-resolved stress analysis shows the static case is sound; the cyclic version of this stress is the binding magnet gate.",
     "magnet-fatigue": "Repeated energising cycles fatigue a magnet's structure even when a single cycle is well within limits, and for the burner's high-field plug coil that cyclic fatigue is the binding engineering gate. Kronos states it openly and closes it with a powered magnet test coil taken through many cycles at full field.",
     "critical-current": "Above its critical current — which falls as field and temperature rise — a superconductor quenches back to normal resistance, so magnet design keeps operation safely inside that surface with margin. Kronos's REBCO study maps the critical-current envelope explicitly, because reaching the breeder's and burner's fields means operating near the high-field frontier of it.",
     "vacuum-vessel": "The vacuum vessel is the primary containment: a welded, ported chamber holding ultra-high vacuum and providing the first structural boundary against disruption forces. Built from forged and rolled sectors joined by automated welds, it is a long-lead procurement item and a hub where many subsystems interface.",
     "cryostat": "The cryostat is the large vacuum enclosure surrounding the entire cold mass, providing the insulating vacuum that keeps room-temperature heat from reaching the magnets. With multi-layer insulation and an actively-cooled thermal shield inside it, the cryostat is what lets the cryoplant handle only the residual heat leaks.",
     "shielding": "Shielding between the plasma and the magnets slows and captures neutrons to protect the superconductors' lifetime, and it is heaviest on the neutron-rich breeder where space in the central column is scarce. Achieving adequate magnet protection in a compact machine is a genuine neutronics constraint, not a formality.",
     "steam-cycle-x": "",
     "biological-shield": "A thick concrete-and-steel biological shield attenuates neutrons and gammas to safe levels outside the machine, and its design follows directly from the neutron source strength — heavy for the breeder, far lighter for the low-neutron burner. It is conventional radiation-protection engineering scaled to the source.",
     "remote-handling": "Once a machine has operated its interior is too activated for hands-on work, so maintenance is done by remote-handling robots through the ports, and designing for remote maintainability is a first-order constraint that shapes component modularity. Fast, reliable remote handling is ultimately what determines plant availability.",
     "first-wall-panel": f"First-wall panels bond plasma-facing armour to actively-cooled heat sinks and take the radiation and particle load, rated for {F['b_wall']} on the breeder. They are designed as modular, remotely-replaceable units so the machine can be maintained as an operating plant rather than a one-shot experiment.",
     "blanket-module": f"The breeding blanket is built from modular segments that can be maintained or replaced remotely, each slowing neutrons to breed tritium (toward ratio {F['b_TBR']}) and recovering their energy as heat. Modularity is central to plant availability, because it lets worn breeding units be swapped without rebuilding the machine.",
     "divertor-cassette": "Divertor cassettes carry the high-heat-flux target plates and are swapped by remote handling as they wear. Their design balances heat handling, pumping and maintainability — the divertor being both the most thermally-stressed component and one that must be routinely serviced.",
     "cryopump": "Cryopumps freeze exhaust gas onto very cold surfaces, achieving the high pumping speeds a fusion vessel needs to control density and remove helium ash. They fill up and are periodically regenerated, and on the breeder that regeneration is part of the tritium-handling loop.",
     "nbi-injector": f"A neutral-beam injector accelerates ions, neutralises them, and fires fast atoms across the confining field to heat the plasma and drive current, within HYPERION's {F['b_Paux']} auxiliary budget. High-energy beams use negative-ion sources and are specialised, long-lead components of the heating system.",
     "gyrotron": "A gyrotron generates the high-power microwaves for electron-cyclotron heating and current drive, enabling precise, steerable deposition useful for heating and for suppressing specific tearing modes. It is a specialised source with a multi-year lead time, delivered to the plasma through diamond windows and low-loss transmission lines.",
     "dec-collector-ring": f"The direct-energy converter's angled, biased 'venetian-blind' collector rings decelerate the burner's escaping ions and collect their energy as electricity at about {F['u_dec']}. They are the heart of direct conversion — the component that lets the burner skip the steam cycle and lift its plant-level efficiency.",
     "power-conversion": f"Conversion follows the fuel: the breeder recovers its energy as heat through a thermal cycle, while the burner recovers charged-particle energy directly at about {F['u_dec']}, skipping the Carnot-limited steam cycle. Reporting net electricity after the plant's own consumption — not gross — is how Kronos states the burner's honest engineering gain.",
     "balance-of-plant": "Beyond the fusion core sits the balance of plant — heat rejection, electrical distribution, power supplies, controls — much of it conventional power-plant and big-science engineering. Kronos's construction-readiness review classes most of it as ready for detailed design, separating the genuinely novel systems from the well-understood ones.",
    }
    G.pop("steam-cycle-x", None)
    for slug, para in G.items():
        if para: enrich(slug, add_body=[('p', para)])
