# -*- coding: utf-8 -*-
"""Glossary batch 19 — advanced scenarios, edge/exhaust regimes, fast-ion physics."""
def register(cat, page, F):
    T = [
     ("advanced-tokamak","Advanced-Tokamak Scenarios","High-performance steady-state regimes with strong bootstrap current.","Advanced-tokamak scenarios shape the current and pressure profiles for high confinement and a large bootstrap fraction, easing steady-state current drive. They are the high-performance target regimes for a power-plant tokamak.",["bootstrap-fraction","steady-state-operation","reversed-shear"]),
     ("hybrid-scenario","Hybrid Scenario","A robust operating regime between standard and fully non-inductive.","The hybrid scenario blends inductive and non-inductive current for long, stable, good-performance discharges — a robust middle path between baseline and advanced operation. It is one option for the breeder's operating point.",["advanced-tokamak","steady-state-operation","current-profile"]),
     ("second-stability","Second Stability","A high-pressure regime accessible past the first ballooning limit.","At strong shaping and bootstrap, plasmas can re-stabilise above the first ballooning limit — 'second stability' — accessing higher pressure. It is one route to high beta, exploited by strongly-shaped designs.",["ballooning-modes","plasma-beta","beta-limit"]),
     ("high-recycling-divertor","High-Recycling Divertor","A dense, cool divertor regime that precedes detachment.","In the high-recycling regime the divertor plasma becomes dense and cool as recycled neutrals ionise near the target, radiating heat and setting the stage for detachment. It is a normal operating regime for the divertor.",["neutral-recycling","detachment","divertor"]),
     ("detachment-front","The Detachment Front","The boundary where the divertor plasma lifts off the target.","As power drops or radiation rises, an ionisation/recombination front moves off the divertor target — the detachment front — cutting the surface heat load. Controlling its position is a divertor-operation goal.",["detachment","radiative-divertor","recombination"]),
     ("momentum-loss-divertor","Divertor Momentum Loss","Friction with neutrals that reduces the plasma pressure reaching the target.","Collisions with neutral gas near the divertor rob the plasma of momentum and pressure before it reaches the target, part of how detachment reduces heat flux. It links neutral physics to surface protection.",["detachment","neutral-recycling","parallel-heat-flux"]),
     ("critical-energy","Fast-Ion Critical Energy","The energy at which fast ions heat ions versus electrons.","Above the critical energy a fast ion mainly heats electrons; below it, ions. The critical energy shapes how beam and fusion-product energy is distributed as fast ions slow down.",["fast-ion-slowing-down","alpha-heating","fast-ions"]),
     ("alpha-channeling","Alpha Channelling","A concept for redirecting fusion-product energy usefully via waves.","Alpha channelling proposes using waves to extract energy from fusion alphas and give it to fuel ions or current, rather than letting them slow down conventionally. It is an advanced concept for improving the energy balance.",["alpha-heating","fast-ions","wave-heating"]),
     ("beam-ion-confinement","Beam-Ion Confinement","Keeping injected fast ions confined long enough to heat the plasma.","Injected beam ions must stay confined through their slowing-down time to deliver their energy; poor confinement wastes heating and loads the wall. It is worse in compact machines and drives beam-geometry choices.",["fast-ions","orbit-loss","neutral-beam-injection"]),
     ("resistive-time","Resistive Diffusion Time","The timescale on which the current profile relaxes.","The resistive time sets how quickly the plasma current profile diffuses and relaxes — long in a hot plasma. It governs how current-profile control must be applied over a discharge.",["current-relaxation","current-diffusion","spitzer-resistivity"]),
     ("alfven-time","Alfvén Time","The fast timescale of magnetohydrodynamic motion.","The Alfvén time is the very short timescale on which ideal MHD instabilities grow — microseconds. It is why ideal instabilities are so dangerous and must be avoided by design rather than controlled after the fact.",["ideal-mhd","alfven-wave","mhd-stability"]),
     ("gyrotron-window","Gyrotron Window & Transmission","Getting microwave power from the source into the plasma.","High-power microwaves travel from the gyrotron through a diamond window and low-loss transmission line to a steerable launcher at the plasma. This transmission chain is part of the ECRH system's engineering.",["gyrotron","electron-cyclotron-heating","steerable-launcher"]),
     ("steerable-launcher","Steerable Microwave Launcher","An aimed mirror that directs heating to a chosen location.","A steerable launcher aims the microwave beam to deposit power exactly where needed — for heating, current drive or stabilising a specific mode. Its precision is what makes ECRH so useful for control.",["gyrotron-window","ec-current-drive","neoclassical-tearing-mode"]),
     ("quench-heater","Quench Protection Heaters","Devices that spread a quench deliberately to protect the coil.","Some magnets use heaters to intentionally spread a quench across the winding, avoiding a damaging local hot spot by sharing the energy. It is one quench-protection strategy among several.",["quench-protection","normal-zone","hot-spot-temperature"]),
     ("field-quality","Magnetic Field Quality","How closely the real field matches the ideal design field.","Field quality measures unwanted harmonic errors in the magnetic field from manufacturing and assembly imperfections. Poor field quality seeds error fields and islands, so it is controlled in fabrication.",["error-field","harmonic-error","dimensional-control"]),
     ("harmonic-error","Field Harmonic Errors","Unwanted components of the magnetic field from imperfect coils.","Harmonic errors are the unwanted Fourier components of the field arising from real, imperfect coils. Minimising and correcting them keeps the plasma stable and well-confined.",["field-quality","error-field","magnetic-diagnostics"]),
     ("fluence","Neutron Fluence","Accumulated neutron exposure over a component's life.","Fluence is the total neutrons per area a component receives over its life, integrating flux over time. End-of-life fluence, with the spectrum, determines total damage and sets replacement schedules.",["neutron-flux","dpa","blanket-lifetime"]),
     ("fracture-toughness","Fracture Toughness","A material's resistance to cracking — degraded by irradiation.","Fracture toughness measures how well a material resists crack propagation; neutron irradiation lowers it, especially below the ductile-brittle transition. Maintaining adequate toughness over life is a materials-qualification requirement.",["radiation-embrittlement","materials-qualification","ductile-brittle-transition"]),
     ("ductile-brittle-transition","Ductile-Brittle Transition","The temperature below which a steel becomes brittle — raised by irradiation.","Ferritic steels turn brittle below a transition temperature, which irradiation shifts upward. Keeping operating temperatures above the irradiated transition is a structural-integrity requirement for the breeder.",["fracture-toughness","radiation-embrittlement","low-activation-steel"]),
     ("irradiation-creep","Irradiation Creep","Slow deformation of materials under stress and neutron flux.","Under simultaneous stress and irradiation, materials deform slowly (creep) faster than either effect alone would cause. It contributes to long-term component distortion and must be designed around.",["radiation-swelling","neutron-damage-materials","structural-analysis"]),
     ("doubling-time","Tritium Doubling Time","How long a breeder takes to produce a second plant's startup inventory.","The doubling time is how long a breeding plant needs to produce enough surplus tritium to start another plant — a measure of how fast a fusion fleet can grow. A short doubling time and good breeding margin support scale-up.",["tritium-breeding","tbr-margin","tritium-supply"]),
     ("inventory-minimization","Tritium Inventory Minimisation","Keeping the resident tritium as low as possible for safety.","Minimising the tritium held in fuel, blanket and processing at any time reduces both hazard and startup needs. Kronos's "+F['b_startup']+" startup inventory reflects this minimisation goal.",["tritium-inventory","source-term","tritium-safety"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
