# -*- coding: utf-8 -*-
"""Glossary batch 25 — currents, divertor hardware, cryo/vacuum operations, applications."""
def register(cat, page, F):
    T = [
     ("pfirsch-schluter-current","Pfirsch–Schlüter Current","A pressure-driven current that flows to maintain equilibrium.","The Pfirsch–Schlüter current flows within the plasma to satisfy force balance in a torus, part of the neoclassical picture. It is a basic feature of toroidal equilibrium.",["plasma-equilibrium","bootstrap-current","neoclassical-transport"]),
     ("driven-current","Externally Driven Current","The share of plasma current supplied by heating and waves.","The driven current is the non-bootstrap share of the plasma current, supplied by beams and RF. HYPERION drives the majority of its "+F['b_Ip']+" externally, with "+F['b_fbs']+" bootstrapped — a balance set by efficiency.",["current-drive","bootstrap-fraction","beam-driven-current"]),
     ("gamma-heating","Gamma Heating","Heat deposited by gamma rays from neutron reactions.","Beyond neutrons, the gamma rays produced when neutrons are captured deposit heat throughout the machine, including in the magnets. Gamma heating is part of the nuclear heating the cooling and shield must handle.",["kerma","nuclear-heating-of-magnets","shielding"]),
     ("monoblock","Divertor Monoblock","The tungsten-and-copper building block of a divertor target.","A monoblock is a tungsten block with a cooling tube through it, the standard high-heat-flux element of a divertor target. Many monoblocks make up the actively-cooled surface that takes the exhaust.",["divertor-cassette-component","tungsten-armor","critical-heat-flux"]),
     ("castellation","Surface Castellation","Grooves in plasma-facing armour that relieve thermal stress.","Plasma-facing armour is often castellated — cut into small blocks — so it can expand without cracking under intense heat. It is a design detail that extends component life.",["thermal-stress","tungsten-armor","first-wall-panel-component"]),
     ("cryopump-regeneration","Cryopump Regeneration","Periodically warming a cryopump to release captured gas.","A cryopump fills up as it freezes gas and must be periodically regenerated — warmed to release the gas for processing. Regeneration cycles are part of vacuum-system operation and tritium handling.",["cryopump","tritium-plant","vacuum-system"]),
     ("first-mirror","Diagnostic First Mirror","The exposed optic that optical diagnostics see the plasma through.","Optical diagnostics view the plasma through a first mirror exposed to the plasma edge, which erodes and deposits over time. Protecting and cleaning first mirrors is a real diagnostic-reliability challenge.",["plasma-diagnostics-integration","erosion","plasma-diagnostics"]),
     ("feedforward-control","Feedforward Control","Pre-planned control actions that anticipate a discharge's needs.","Feedforward applies pre-planned actuator trajectories based on the scenario, while feedback corrects deviations. Together they run the discharge. Feedforward encodes the operating scenario into action.",["real-time-control","plasma-startup-scenario","feedback-stabilization"]),
     ("end-of-life-criteria","End-of-Life Criteria","The limits that decide when a component must be replaced.","End-of-life criteria — accumulated damage, erosion, fatigue, dose — set when a component is retired and replaced. Defining them clearly underpins maintenance scheduling and availability.",["blanket-lifetime","fluence","maintenance-strategy"]),
     ("process-heat","Fusion Process Heat","High-grade heat for industrial processes.","A fusion plant's firm, high-grade heat can drive industrial processes directly, decarbonising heat-intensive industry that is hard to electrify. It is one of the non-electric applications of firm fusion output.",["industrial-heat-hydrogen","fusion-for-industry","combined-heat-power"]),
     ("hydrogen-electrolysis","Fusion-Powered Hydrogen","Making clean hydrogen with firm fusion electricity.","Abundant firm electricity can split water into clean hydrogen by electrolysis, and high-grade heat improves the efficiency. Fusion is well suited to producing green hydrogen at scale.",["industrial-heat-hydrogen","firm-power","process-heat"]),
     ("district-heating","District Heating","Using a plant's waste heat to warm nearby communities.","A plant's waste heat can warm district-heating networks, raising overall energy use. It is a combined-heat-and-power application relevant where a plant sits near demand.",["combined-heat-power","heat-rejection-system","baseload-power"]),
     ("occupational-safety","Occupational Safety","Protecting the workers who build and run the plant.","Beyond radiological protection, a fusion plant manages conventional industrial hazards — high fields, cryogens, high voltage, beryllium dust — through standard occupational-safety practice. It is part of a complete safety programme.",["radiation-protection","beryllium-handling","alara"]),
     ("worker-dose","Worker Dose Management","Keeping occupational radiation exposure as low as reasonably achievable.","Worker dose is managed by shielding, remote handling, dose planning and time limits, following the ALARA principle. Fusion's low activation and short-lived isotopes make this readily achievable.",["alara","dose-mapping","remote-handling"]),
     ("corrosion-control","Coolant Chemistry & Corrosion Control","Keeping coolant loops clean to protect components and control tritium.","Coolant chemistry is controlled to limit corrosion of structures and to manage tritium and activated corrosion products in the loop. It is routine but important power-plant water/coolant chemistry, with a tritium twist on the breeder.",["primary-coolant","water-detritiation","materials-qualification"]),
     ("mhd-pressure-drop","Liquid-Metal MHD Effects","How magnetic fields resist the flow of conducting coolants.","A conducting liquid-metal coolant flowing across a magnetic field experiences a strong braking force and pressure drop (magnetohydrodynamic effect). It is a defining challenge for liquid-metal blanket concepts.",["lead-lithium","self-cooled-blanket","primary-coolant"]),
     ("gas-injection-system","Gas Injection System","The valves and lines that puff gas for fuelling and control.","A gas injection system delivers precise puffs of fuel or impurity gas for density control, edge cooling and disruption mitigation. It is a fast, flexible actuator in the fuelling and control suite.",["gas-puffing","impurity-seeding","massive-gas-injection"]),
     ("plasma-startup-assist","Start-Up Assist Heating","Using RF power to help break down and ramp the plasma.","Electron-cyclotron power is often used to assist breakdown and early current ramp, easing start-up especially in machines with a small solenoid. It is a practical start-up aid.",["plasma-breakdown","tokamak-startup","electron-cyclotron-heating"]),
     ("current-hole","Current Hole & Profile Control","Extreme current profiles used in advanced scenarios.","Advanced scenarios can hollow the core current (a 'current hole') to shape the safety-factor profile for stability and confinement. It illustrates how finely the current profile can be tailored.",["current-profile","reversed-shear","advanced-tokamak"]),
     ("prompt-radiation","Prompt vs Delayed Radiation","Radiation during operation versus after shutdown.","Prompt radiation (neutrons and gammas) exists only while the plasma runs and stops instantly at shutdown; delayed radiation comes from activated material and decays over time. The distinction shapes shielding versus maintenance planning.",["gamma-heating","decay-heat","activation-products"]),
     ("diagnostic-neutron-monitor","Fusion Power Monitor","The calibrated neutron measurement that reports fusion power live.","A calibrated neutron monitor gives the real-time fusion power — the headline operational number on the breeder — feeding both control and the validation record. It directly measures what the machine is doing.",["neutron-yield-monitor","neutron-diagnostics","fusion-power-density"]),
     ("plant-integration","Reactor–Plant Integration","Coupling the fusion core to a working power plant.","Integrating the reactor core with the balance of plant — coolant loops, conversion, electrical, controls — turns a fusion machine into a generating facility. It is a major systems-engineering task on the path to build.",["balance-of-plant","the-power-plant-system","systems-integration"]),
     ("the-kronos-thesis","The Kronos Thesis","Match fuel to purpose, sell materials first, and prove it in the open.","The Kronos thesis in one line: split fusion into a fuel-and-neutron breeder and a clean-electricity burner, earn from materials before net electricity, and make the whole case openly reproducible. It is a distinct, evidence-first route to fusion's promise.",["the-breeder-first-strategy","innovation-two-machine-architecture","why-kronos-matters"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
