# -*- coding: utf-8 -*-
"""Glossary batch 9 — MHD modes, edge/exhaust detail, nuclear-reaction physics, grid."""
def register(cat, page, F):
    T = [
     ("rational-surface","Rational Surface","A flux surface where the safety factor is a simple fraction — where islands can grow.","A rational surface is one where field lines close on themselves after a whole number of turns (q = m/n). These surfaces are where tearing modes and magnetic islands preferentially form, so the current profile is shaped to manage them.",["safety-factor","magnetic-island","tearing-mode"]),
     ("magnetic-island","Magnetic Island","A region where field lines reconnect into a closed chain, short-circuiting confinement.","A magnetic island forms when field lines reconnect at a rational surface into a chain of closed loops that flatten the profile across them, degrading confinement. Neoclassical tearing modes are the most troublesome islands, suppressed by localised current drive.",["rational-surface","neoclassical-tearing-mode","tearing-mode"]),
     ("external-kink","External Kink Mode","A current-driven instability that displaces the whole plasma column.","The external kink bends the entire plasma column and is the most dangerous ideal instability; keeping the edge safety factor above about 2 avoids it. It sets a hard limit on plasma current for a given field.",["kink-instability","safety-factor","ideal-mhd"]),
     ("strike-point","Divertor Strike Point","Where the separatrix meets the divertor target — the focus of the heat load.","The strike point is where the separatrix intersects the divertor target and the exhaust heat concentrates. Sweeping it or detaching the plasma there spreads the load and protects the surface.",["separatrix","divertor","detachment"]),
     ("private-flux-region","Private-Flux Region","The area between the divertor legs, below the X-point.","The private-flux region is the magnetic zone enclosed below the X-point between the two divertor legs. Its geometry affects neutral recycling and detachment behaviour in the divertor.",["x-point","divertor","neutral-recycling"]),
     ("power-decay-length","Power Decay Length","How quickly exhaust power falls off across the scrape-off layer.","The power decay length sets the width over which exhaust heat spreads at the divertor; a short one means a fierce peak flux. It is a key parameter for divertor survivability and the case for radiative operation.",["lambda-q","parallel-heat-flux","detachment"]),
     ("sputtering","Sputtering","Erosion of wall material by ion bombardment.","Ions striking a surface eject atoms — sputtering — eroding plasma-facing components and releasing impurities into the plasma. Low-sputtering materials like tungsten are chosen to minimise both wear and contamination.",["erosion","tungsten-divertor","plasma-facing-armor"]),
     ("erosion","Wall Erosion","The gradual loss of plasma-facing material over a machine's life.","Erosion from sputtering and heat sets how often plasma-facing armour must be replaced, driving component lifetime and maintenance. Redeposition returns some material elsewhere, complicating the picture.",["sputtering","redeposition","maintainability"]),
     ("redeposition","Redeposition","Eroded material settling elsewhere on the wall.","Sputtered atoms often redeposit on other surfaces, forming co-deposited layers that can trap tritium and change surface properties. Managing redeposition and its tritium inventory is part of wall design.",["erosion","codeposition","wall-inventory"]),
     ("codeposition","Tritium Co-Deposition","Tritium trapped in redeposited wall layers — a tritium-inventory concern.","As eroded material redeposits it can trap tritium in co-deposited layers, building up wall inventory that must be tracked and recovered. It is a specific tritium-accountancy challenge on the breeder.",["redeposition","wall-inventory","tritium-inventory"]),
     ("wall-inventory","Wall Fuel Inventory","Fuel retained in the walls, which must be limited and accounted for.","Some fuel — including tritium — is retained in the walls through implantation and co-deposition. Keeping this inventory low and accounted for is important for both fuel efficiency and safety on the breeder.",["codeposition","tritium-inventory","wall-conditioning"]),
     ("critical-heat-flux","Critical Heat Flux","The heat-flux limit a cooled surface can take before failing.","Every actively-cooled surface has a critical heat flux above which cooling fails and the surface overheats. Divertor and first-wall design keeps peak loads safely below it, which is why spreading the load matters.",["heat-flux","divertor","power-decay-length"]),
     ("thermal-fatigue","Thermal Fatigue","Cracking from repeated thermal expansion and contraction.","Repeated heating and cooling cycles fatigue plasma-facing components through differential thermal expansion, limiting their cyclic life. It is a lifetime driver designed around with material choice and geometry.",["thermal-cycling","first-wall","plasma-facing-materials"]),
     ("gamow-factor","The Gamow Factor","The quantum-tunnelling probability that lets nuclei fuse below the classical barrier.","Nuclei fuse mainly by quantum-tunnelling through the Coulomb barrier, a probability captured by the Gamow factor. It explains why fusion proceeds at temperatures well below the classical barrier height and why reactivity rises so steeply with temperature.",["coulomb-barrier","reactivity","fusion-cross-section"]),
     ("q-value","Reaction Q-Value","The energy released by a fusion reaction.","The Q-value is the net energy a nuclear reaction releases — 17.6 MeV for D–T, 18.3 MeV for D–&sup3;He. It sets how much energy each reaction contributes and, with the neutron split, how that energy is distributed.",["the-dt-reaction","the-dhe3-reaction","mev-unit"]),
     ("branching-ratio","Branching Ratio","The split between a reaction's alternative outcomes, as in D–D.","When a reaction can proceed by more than one channel — like D–D's near-equal tritium and helium-3 branches — the branching ratio sets how often each occurs. It matters for fuel cycles and side-reaction neutron production.",["catalyzed-dd","d-he3-fuel","the-neutron-economy"]),
     ("neutron-yield","Neutron Yield","How many neutrons a reaction or plasma produces.","Neutron yield — per reaction and per second — sets the breeding rate, the damage rate and the diagnostic signal. The breeder's high yield is its product; the burner's low yield is its cleanliness.",["neutron-flux","neutron-diagnostics","the-neutron-economy"]),
     ("firm-power","Firm Power","Always-available generation the grid can count on.","Firm power is capacity a grid can rely on at any time, unlike intermittent renewables. Fusion's steady output is inherently firm, which is the core of the burner's value proposition for grids and data centres.",["baseload-power","dispatchable-power","grid-scale-power"]),
     ("capacity-credit","Capacity Credit","How much firm capacity a generator effectively adds to a grid.","Capacity credit measures the reliable capacity a generator contributes; firm sources like fusion score near their nameplate, while intermittent sources score much lower. It is part of why firm clean power is valuable.",["firm-power","baseload-power","fusion-vs-solar-wind"]),
     ("grid-inertia","Grid Inertia & Stability","The stabilising rotational energy that firm generators provide to a grid.","Large rotating generators give a grid inertia that resists frequency swings; as they retire, grids need new sources of stability. Firm fusion generation can help provide it, an ancillary value beyond energy.",["firm-power","power-quality","grid-interconnection"]),
     ("energy-storage-complement","Fusion and Energy Storage","How firm fusion reduces the storage a renewable grid needs.","Because it is firm, fusion reduces the amount of expensive storage a high-renewable grid needs to stay reliable. Fusion and storage are complements, each doing what the other cannot.",["firm-power","fusion-vs-solar-wind","baseload-power"]),
     ("neutron-multiplication-factor","Neutron Multiplication","Boosting neutron count in the blanket to ensure breeding self-sufficiency.","Because breeding needs more than one tritium per fusion neutron, blankets multiply neutrons using materials like beryllium or lead. The multiplication factor is tuned to reach the target breeding ratio with margin.",["neutron-multiplier","tritium-breeding","neutronics"]),
     ("energy-confinement-scaling-h98","The H98 Confinement Factor","A number expressing confinement relative to the standard H-mode scaling.","H<sub>98</sub> compares a plasma's energy confinement to the ITER IPB98(y,2) scaling; H<sub>98</sub> = 1 is standard H-mode. HYPERION's assumption of H<sub>98</sub> = "+F['b_H98']+" is deliberately at standard performance, not beyond it.",["confinement-scaling","h-mode","energy-confinement-time"]),
     ("plasma-purity","Plasma Purity","Keeping the fuel clean of impurities that radiate and dilute.","Plasma purity — low impurity content and low Z<sub>eff</sub> — preserves fusion power by limiting radiation and dilution. It is maintained by wall conditioning, controlled seeding and good exhaust.",["zeff","fuel-dilution","wall-conditioning"]),
     ("operational-envelope","Operational Envelope","The range of conditions a machine can safely and stably run within.","The operational envelope bounds the density, current, beta and heating a machine can run at while staying stable and within limits. Designing a comfortable envelope around the operating point is part of ensuring robust operation.",["the-operating-window","density-limit","beta-limit"]),
     ("plasma-scenario-development","Scenario Development","Designing and refining the discharge recipes a machine will run.","Scenario development creates the pre-planned discharge recipes — current, density and heating trajectories — that reach the operating point reliably. It is a major part of preparing any machine to operate well.",["plasma-startup-scenario","operational-envelope","real-time-control"]),
     ("fusion-power-density","Fusion Power Density","Fusion power produced per unit plasma volume — a compactness driver.","Fusion power density rises with pressure squared, so high-field, high-beta machines pack more power into less volume. It is what lets a compact machine like HYPERION rival a much larger one in output.",["plasma-pressure","specific-power","plasma-volume"]),
     ("tritium-self-sufficiency","Tritium Self-Sufficiency","A plant breeding at least as much tritium as it burns.","Tritium self-sufficiency means the blanket breeds enough tritium (breeding ratio above 1 with margin) to sustain the plant without external supply. HYPERION's TBR of "+F['b_TBR']+" is designed to achieve it while also exporting.",["tritium-breeding","fuel-cycle","tritium-supply"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
