# -*- coding: utf-8 -*-
"""Operations & commissioning — bringing the machine to life and running it."""
def register(cat, page, F):
    cat("operations", "Operations & Commissioning",
        "How a built machine is commissioned, operated, maintained and refuelled — from cold "
        "systems through first plasma to steady operation.", 4.6)
    P = [
     ("commissioning-overview","Commissioning a Fusion Machine","The staged turn-on from cold systems to first plasma to demonstrated performance.",
      ["Commissioning takes a built machine from individual cold systems, through integrated cold checks, to first plasma and then a staged climb to full performance. Each stage has entry and exit criteria, and nothing advances until the prior stage passes. It is the disciplined bridge between construction and operation.",
       "Kronos frames the commissioning sequence explicitly as part of its path to build."],
      [("Path","Cold &rarr; first plasma &rarr; power")],
      ["commissioning","first-plasma","the-path-to-build"]),
     ("cold-commissioning","Cold Commissioning","Proving every system works before any plasma exists.",
      ["Cold commissioning powers and tests each system — vacuum, cryogenics, magnets, cooling, controls — individually and then together, all before the first plasma. It verifies the machine is ready and safe to operate.",
       "Reaching base vacuum, cooling the magnets, and validating interlocks are the milestones of this stage."],
      [("Goal","Systems proven, no plasma yet")],
      ["commissioning-overview","cooldown-sequence","acceptance-testing"]),
     ("magnet-commissioning","Magnet Commissioning","Energising the superconducting magnets to full field for the first time.",
      [f"Magnet commissioning ramps the coils to full field in careful steps, validating quench detection and the energy-dump system along the way. Confirming the magnets hold {F['b_Bpeak']} safely, and quench-protect as designed, is a critical gate before plasma operation.",
       "It is where the magnet technology meets reality."],
      [("Milestone","Full field held + quench validated")],
      ["superconducting-magnets","quench-protection","cold-commissioning"]),
     ("first-plasma-campaign","The First-Plasma Campaign","The initial low-power discharges that prove integrated operation.",
      ["Once systems are proven cold, the first-plasma campaign achieves breakdown and low-power discharges, demonstrating that magnets, control, vacuum and fuelling work together. It is a headline milestone but only the start of physics operation.",
       "Reproducible plasma initiation is the exit criterion."],
      [("Milestone","Reproducible first plasma")],
      ["first-plasma","tokamak-startup","commissioning-overview"]),
     ("power-ascension","Power Ascension","Climbing in steps from first plasma toward the design operating point.",
      [f"After first plasma, operation ramps up in stages — more heating, higher density and temperature — toward the frozen design point (breeder Q = {F['b_Q']}). Each step checks stability and component loads before the next. It is a deliberate climb, not a leap.",
       "Performance is demonstrated, not assumed, along this ascent."],
      [("Path","Stepwise to design point")],
      ["the-breeder-design-point","operational-envelope","performance-demonstration"]),
     ("performance-demonstration","Performance Demonstration","Sustained operation at the design point, measured against the frozen targets.",
      [f"The final commissioning stage sustains operation at the design point and measures it against the frozen targets — the breeder's Q = {F['b_Q']} and {F['b_Pfus']}, the burner's Q<sub>E</sub> = {F['u_QE']} under its stated gate conditions. It is where computed design targets meet measured reality.",
       "Kronos frames these targets as the demonstration goal, not a present claim."],
      [("Goal","Meet frozen targets, measured")],
      ["the-breeder-design-point","the-burner-design-point","validation-suite-breeder"]),
     ("maintenance-strategy","Maintenance Strategy","Keeping an activated machine running through remote, modular maintenance.",
      ["Because an operated machine is activated, maintenance is remote and modular: replaceable blanket modules, divertor cassettes and first-wall panels swapped by remote handling. Fast, reliable maintenance is what turns a working machine into an available power plant.",
       "Maintainability is designed in from the start, not added later."],
      [("Approach","Remote, modular")],
      ["remote-handling","maintainability","plant-availability"]),
     ("fuel-cycle-operation","Operating the Fuel Cycle","Breeding, extracting, purifying and re-injecting tritium in steady operation.",
      [f"In operation the breeder continuously breeds tritium in the blanket, extracts and purifies it, accounts for every gram, and re-injects it — a closed loop running at TBR {F['b_TBR']} to make {F['b_T']} while exporting the surplus. It is the operational heart of the breeder's product.",
       "Tritium accountancy is a continuous, regulator-relevant operation."],
      [("Loop","Breed &rarr; extract &rarr; inject")],
      ["fuel-cycle","tritium-plant","tritium-supply"]),
     ("plasma-operation","Running the Plasma","The moment-to-moment task of holding the plasma at its operating point.",
      ["Operating the plasma means continuously steering heating, fuelling and coils to hold the operating point and head off instabilities, guided by diagnostics and guarded by the safety system. In a driven machine, this control is what makes the output steady and adjustable.",
       "It is where the control technology earns its place."],
      [("Task","Hold the operating point")],
      ["real-time-control","burn-control","plasma-control-system"]),
     ("availability-operation","Operating for Availability","Running the plant to maximise uptime — an explicit open study for Kronos.",
      ["Commercial value depends on availability — uptime between maintenance — which depends on component lifetimes and maintenance speed. Kronos treats early-life availability as a leading open study, expecting it to grow with experience rather than assuming a mature value.",
       "It is named as a key commercial study, not a settled number."],
      [("Driver","Lifetimes + maintenance speed")],
      ["plant-availability","capacity-factor","availability-growth"]),
    ]
    for slug,title,desc,paras,facts,rel in P:
        page(slug,title,"operations",desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
