# -*- coding: utf-8 -*-
"""Glossary — one DefinedTerm page per fusion / plasma / engineering term.
Each entry is real content, cross-linked. Numbers reference the frozen canon via F."""

def register(cat, page, F):
    cat("glossary", "Glossary of Fusion & Plasma Terms",
        "Plain-language, technically precise definitions of the physics, engineering and "
        "plasma terms that appear across the Kronos design record.", 8)

    # (slug, term, one-line-def, [body paragraphs], [related])
    T = [
     ("aspect-ratio","Aspect Ratio (A)","The ratio of a torus's major radius to its minor radius; low A means a 'fat', compact plasma.",
      [f"Aspect ratio A = R&#8320;/a compares the distance from the machine centre to the plasma centre (major radius) with the plasma's own radius (minor radius). Conventional tokamaks sit near A = 3; a <a href='./spherical-tokamak.html'>spherical tokamak</a> pushes A down toward 1.5–2.",
       f"HYPERION runs at A = {F['b_A']} (R&#8320; = {F['b_R0']}, a = {F['b_a']}). Low aspect ratio raises the achievable plasma pressure for a given field and improves stability, at the cost of a tight, highly-loaded central column."],
      ["spherical-tokamak","elongation","beta-limit"]),
     ("elongation","Elongation (&kappa;)","How vertically stretched the plasma cross-section is; taller plasmas carry more current and pressure.",
      [f"Elongation &kappa; is the ratio of the plasma's height to its width. A circular plasma has &kappa; = 1; shaping it into a tall D raises the current it can carry and the pressure it can hold.",
       f"HYPERION is designed at &kappa; = {F['b_kappa']}, a strong elongation that spherical tokamaks naturally support. Higher elongation must be balanced against vertical-stability control."],
      ["triangularity","aspect-ratio","plasma-shaping"]),
     ("triangularity","Triangularity (&delta;)","How D-shaped or reverse-D the plasma is; negative triangularity can suppress edge instabilities.",
      [f"Triangularity &delta; measures how the plasma's corners are pulled in or out relative to a pure ellipse. Positive &delta; gives the familiar D-shape; negative &delta; points the corners the other way.",
       f"HYPERION adopts negative triangularity, &delta; = {F['b_delta']}, a configuration that can suppress <a href='./edge-localized-modes.html'>edge-localised modes</a> while maintaining good confinement — a deliberate stability choice."],
      ["edge-localized-modes","elongation","plasma-shaping"]),
     ("safety-factor","Safety Factor (q)","A measure of magnetic field-line pitch that governs large-scale plasma stability.",
      [f"The safety factor q counts how many times a magnetic field line travels the long way around the torus for each time it goes the short way. It is central to stability: low-order rational values of q are where dangerous <a href='./mhd-stability.html'>MHD modes</a> can grow.",
       f"HYPERION targets q&#8329;&#8325; = {F['b_q95']} at the plasma edge, a standard, conservative value that keeps the current profile away from the most disruptive resonances."],
      ["mhd-stability","plasma-current","disruptions"]),
     ("plasma-beta","Plasma Beta (&beta;) and Beta-N","The ratio of plasma pressure to magnetic pressure; higher beta means a more economical machine.",
      [f"Beta is the ratio of the plasma's thermal pressure to the pressure of the confining magnetic field. It is an efficiency metric: a machine that holds more plasma pressure per tesla of field is cheaper to build. The normalised form &beta;<sub>N</sub> removes size and field to compare configurations.",
       f"HYPERION is designed at &beta;<sub>N</sub> = {F['b_bN']} — comfortably within the no-wall stability limits observed on spherical tokamaks such as NSTX. Its low aspect ratio is what lets it hold high beta."],
      ["beta-limit","aspect-ratio","spherical-tokamak"]),
     ("bootstrap-current","Bootstrap Current","A self-generated plasma current that reduces the external drive a machine needs.",
      [f"A pressure gradient in a magnetised plasma spontaneously drives a component of the toroidal current — the bootstrap current. The more of the total current a plasma bootstraps, the less external <a href='./current-drive.html'>current drive</a> power it needs, improving the energy ledger.",
       f"HYPERION runs {F['b_Ip']} of plasma current, of which the bootstrap fraction is {F['b_fbs']}; the remainder is externally driven. Raising the bootstrap fraction is a standard efficiency lever."],
      ["current-drive","plasma-current","bootstrap-fraction"]),
     ("energy-confinement-time","Energy Confinement Time (&tau;E)","How long a plasma retains its heat; longer confinement means less heating power for the same temperature.",
      [f"The energy confinement time &tau;<sub>E</sub> is the characteristic time over which a plasma would lose its stored energy if heating stopped. It is the single most important — and hardest to predict — performance parameter, usually estimated from empirical <a href='./confinement-scaling.html'>scaling laws</a>.",
       f"HYPERION is designed for &tau;<sub>E</sub> = {F['b_tauE']} at confinement quality H<sub>98</sub> = {F['b_H98']}, i.e. it assumes standard H-mode confinement, not an optimistic multiple of it."],
      ["confinement-scaling","lawson-criterion","h-mode"]),
     ("h-mode","H-mode (High-Confinement Mode)","A spontaneous transition to roughly doubled confinement, standard in modern tokamaks.",
      [f"Above a power threshold, tokamak plasmas jump into a high-confinement regime — H-mode — in which an edge transport barrier roughly doubles the energy confinement time relative to L-mode. The confinement multiplier H<sub>98</sub> = 1 denotes standard H-mode performance.",
       f"HYPERION's confinement target of H<sub>98</sub> = {F['b_H98']} places it squarely at established H-mode performance rather than beyond it — a deliberately unaggressive assumption."],
      ["energy-confinement-time","edge-localized-modes","confinement-scaling"]),
     ("edge-localized-modes","Edge-Localised Modes (ELMs)","Periodic bursts of energy from the plasma edge that can erode plasma-facing components.",
      [f"H-mode's edge barrier stores energy that is periodically expelled in bursts called ELMs. Large ELMs deposit heat on the <a href='./divertor.html'>divertor</a> and first wall in ways that can shorten component life.",
       f"HYPERION's negative triangularity (&delta; = {F['b_delta']}) is chosen in part to suppress ELMs — a real, physics-based benefit rather than an add-on control system."],
      ["triangularity","divertor","h-mode"]),
     ("disruptions","Disruptions","A sudden loss of plasma confinement; avoiding or mitigating them is a central tokamak safety task.",
      ["A disruption is a rapid, unplanned termination of the plasma current, dumping stored energy into the vessel and generating large electromagnetic forces. Managing disruption risk is a core part of tokamak engineering.",
       "Linear machines like the tandem-mirror burner do not disrupt in the tokamak sense — an architectural safety advantage of the burner that Kronos notes explicitly."],
      ["mhd-stability","safety-factor","tandem-mirror"]),
     ("greenwald-density","Greenwald Density Limit","An empirical ceiling on tokamak plasma density set by current and size.",
      ["The Greenwald limit is an empirical maximum density, proportional to plasma current divided by minor-radius area, above which tokamaks tend to disrupt. Operating below it is a standard design constraint.",
       "HYPERION's density is chosen to sit within the Greenwald limit; the burner, being a mirror, is not subject to it and instead operates at a design density of "+F['u_ne']+"."],
      ["plasma-current","disruptions","plasma-density"]),
     ("mhd-stability","Magnetohydrodynamic (MHD) Stability","The study of large-scale plasma instabilities that can degrade or end confinement.",
      ["Magnetohydrodynamics treats the plasma as a conducting fluid and predicts large-scale instabilities — kinks, tearing modes, ballooning modes — that can limit pressure or trigger <a href='./disruptions.html'>disruptions</a>. Staying MHD-stable bounds how much pressure and current a machine can safely run.",
       "Kronos's negative-triangularity, moderate-q&#8329;&#8325; design is a conservative point in MHD-stability space rather than an aggressive one."],
      ["safety-factor","plasma-beta","ballooning-modes"]),
     ("ballooning-modes","Ballooning Modes","Pressure-driven instabilities that balloon out where the field curvature is unfavourable.",
      ["Ballooning modes are short-wavelength instabilities driven by the plasma pressure gradient in regions of bad magnetic curvature. They set one of the ceilings on achievable beta.",
       "Design codes check the Kronos operating point against ballooning and Mercier criteria; the chosen beta sits below these limits."],
      ["mhd-stability","plasma-beta","beta-limit"]),
     ("neoclassical-transport","Neoclassical Transport","The irreducible, geometry-driven leakage of heat and particles across the field.",
      ["Even a perfectly stable plasma loses heat by collisional transport enhanced by the torus geometry — neoclassical transport. It sets a floor below which confinement cannot fall; real machines usually lose more, via turbulence.",
       "The bootstrap current is itself a neoclassical effect, which is why good confinement and self-driven current tend to come together."],
      ["turbulent-transport","bootstrap-current","energy-confinement-time"]),
     ("turbulent-transport","Turbulent (Anomalous) Transport","Micro-turbulence that leaks heat faster than collisions alone; the main confinement-limiter.",
      ["Small-scale drift-wave turbulence transports heat and particles across the confining field far faster than collisions would — 'anomalous' transport. Predicting and suppressing it is the central problem of confinement physics.",
       "Kronos's confinement targets are anchored to the empirical H-mode database, which already folds in typical turbulent losses, rather than to first-principles turbulence optimism."],
      ["neoclassical-transport","confinement-scaling","h-mode"]),
     ("current-drive","Current Drive","Externally sustaining the plasma current using beams or waves, beyond what the plasma self-generates.",
      [f"Steady-state tokamaks must drive part of their plasma current externally, using neutral beams or radio-frequency waves, to supplement the self-generated <a href='./bootstrap-current.html'>bootstrap current</a>. Current-drive efficiency directly affects the plant power ledger.",
       f"HYPERION drives the non-bootstrap share of its {F['b_Ip']} current with {F['b_Paux']} of auxiliary power."],
      ["bootstrap-current","heating-systems","plasma-current"]),
     ("divertor","Divertor","The component that exhausts heat and helium ash from a tokamak while protecting the wall.",
      ["The divertor channels the plasma's edge onto dedicated, actively cooled target plates, exhausting fusion 'ash' (helium) and heat away from the main wall. Handling its heat flux is one of the toughest engineering problems in tokamaks.",
       "HYPERION's divertor design leans on a high radiated fraction to spread the load — an approach with a real, named performance gate."],
      ["edge-localized-modes","first-wall","heat-flux"]),
     ("first-wall","First Wall","The plasma-facing surface that takes the reactor's radiation and particle load.",
      [f"The first wall is the innermost solid surface facing the plasma, absorbing radiation, neutrons and stray particles. Its heat-flux and neutron-damage tolerance set component lifetimes.",
       f"HYPERION's first wall is designed for {F['b_wall']}; the burner's first-wall loading is far lower because of its low neutron fraction."],
      ["divertor","blanket","neutron-damage-materials"]),
     ("blanket","Breeding Blanket","The layer that captures fusion neutrons to breed tritium and recover heat.",
      [f"Surrounding the plasma, the breeding blanket slows fusion neutrons, breeds tritium from lithium, and recovers the neutrons' energy as heat. Its tritium breeding ratio must exceed 1 for the plant to be fuel-self-sufficient.",
       f"HYPERION's blanket targets a breeding ratio of {F['b_TBR']} to produce {F['b_T']} of tritium while co-producing helium-3 for the burner."],
      ["tritium-breeding","first-wall","the-neutron-economy"]),
     ("tritium-breeding","Tritium Breeding Ratio (TBR)","Tritium atoms bred per tritium atom burned; must exceed 1 for self-sufficiency.",
      [f"Because tritium is not available in nature, a D–T plant must breed its own. The tritium breeding ratio is the number of tritium atoms produced in the blanket per atom consumed in the plasma; a value above 1 (with margin) is required for a self-sustaining fuel cycle.",
       f"HYPERION targets TBR = {F['b_TBR']}, breeding {F['b_T']} against a startup inventory of {F['b_startup']}."],
      ["blanket","dt-fuel","fuel-cycle"]),
     ("mirror-ratio","Mirror Ratio","The field-strength ratio between a mirror's throat and its centre; it sets how well particles are trapped.",
      [f"In a magnetic mirror, the field is stronger at the ends ('throats') than in the middle. The mirror ratio — throat field over central field — determines the range of particle velocities that are reflected and confined.",
       f"The Kronos burner uses high-field plug coils (throat field {F['u_Bm']}, plug/ion-end {F['u_Bplug']}) to raise the effective mirror ratio and, with an ambipolar potential, plug the ends."],
      ["tandem-mirror","ambipolar-potential","magnetic-mirror"]),
     ("ambipolar-potential","Ambipolar Potential","An electrostatic potential in a tandem mirror that plugs ion end-losses.",
      [f"In a tandem mirror, dense high-field plugs at each end build up an electrostatic potential that repels ions trying to escape from the central cell — an 'ambipolar' plug that confines ions electrostatically rather than only magnetically.",
       f"Establishing this potential requires the plug to reach a density well above the central cell — the burner's plug-density requirement of about n<sub>p</sub>/n<sub>c</sub> = {F['u_np']}."],
      ["tandem-mirror","plug-density-requirement","mirror-ratio"]),
     ("direct-energy-conversion","Direct Energy Conversion (DEC)","Turning charged-particle energy straight into electricity, skipping the steam cycle.",
      [f"Direct energy conversion decelerates the plasma's escaping charged particles against an electric field, recovering their kinetic energy as electricity without a thermal cycle. It only works when most of the fusion energy is in charged particles — as in D–&sup3;He.",
       f"The Kronos burner's DEC stage operates at about {F['u_dec']} efficiency, which is what lets it quote an engineering gain of Q<sub>E</sub> = {F['u_QE']}."],
      ["d-he3-fuel","tandem-mirror","fusion-gain-q"]),
     ("rebco","REBCO High-Temperature Superconductor","Rare-earth barium copper oxide tape that carries huge currents at high field; the enabling magnet material.",
      [f"REBCO — rare-earth barium copper oxide — is a high-temperature superconducting tape that sustains very high current densities in very high magnetic fields. It is the material that makes compact, high-field fusion magnets possible.",
       f"HYPERION's magnets reach a peak field of {F['b_Bpeak']} using REBCO; the burner's plug coils push to {F['u_Bplug']}. Kronos's REBCO study is deposited openly."],
      ["superconducting-magnets","high-field-magnets","quench-protection"]),
     ("quench-protection","Magnet Quench Protection","Systems that safely dump a superconducting magnet's energy if it loses superconductivity.",
      ["If any part of a superconducting magnet warms above its critical temperature it 'quenches', and the stored magnetic energy must be dumped safely to avoid damage. Quench detection and protection are essential magnet-safety systems.",
       "Kronos's magnet design is analysed for quench with an adiabatic hot-spot method and is reported as self-protecting within its design basis."],
      ["rebco","superconducting-magnets","high-field-magnets"]),
    ]

    def make(slug, term, oneliner, paras, rel):
        page(slug, term, "glossary", oneliner,
             oneliner,
             [('p', p) for p in paras],
             related=rel, jtype="DefinedTerm", kicker="Glossary")

    for slug, term, oneliner, paras, rel in T:
        make(slug, term, oneliner, paras, rel)
