# -*- coding: utf-8 -*-
"""Glossary depth batch B — plasma physics, transport, heating, edge."""
def register(cat, page, F, enrich):
    G = {
     "magnetic-confinement": "Magnetic confinement works because charged particles spiral tightly around field lines, so a suitably shaped field suspends a hot plasma away from any wall. The art is closing the field into surfaces that trap particles for long enough — the tokamak does it with a plasma current, the stellarator with shaped coils, and the mirror with end plugs plus an electrostatic barrier.",
     "inertial-confinement": "Inertial confinement takes the opposite approach to Kronos: instead of holding a diffuse plasma steadily, it compresses a tiny fuel pellet so violently that it fuses in nanoseconds before flying apart. NIF's 2022 target gain proved the principle, but the driver efficiency and repetition rate needed for a power plant are very different engineering problems from continuous magnetic confinement.",
     "fusion-cross-section": "The cross-section's steep energy dependence is why fuel choice dominates machine design: D–T's large, low-energy peak makes it the easiest fuel and sets the breeder's modest temperature, while D–&sup3;He's higher-energy peak forces the burner to run far hotter. Everything downstream — confinement, heating, materials — follows from that curve.",
     "maxwellian-distribution": "Fusion is driven mostly by the fast tail of the Maxwellian distribution, not the average particle, which is why reaction rate is so sensitive to temperature and why maintaining a hot, clean bulk plasma matters. It also means injected fast ions and fusion products live temporarily outside the Maxwellian until they slow down and thermalise.",
     "larmor-radius": "The Larmor radius shrinks as field rises, so stronger magnets confine more tightly and average over smaller-scale turbulence — one more reason Kronos's high-field approach helps. It also sets the natural scale of drift-wave turbulence and the width of particle orbits that determine neoclassical transport.",
     "scrape-off-layer": "The scrape-off layer is a thin, ferociously-loaded region: its width, often only millimetres, decides how concentrated the divertor heat flux is. Because a narrow layer implies a fierce peak, understanding and widening it — or radiating the power away before it lands — is central to protecting the divertor.",
     "separatrix": "The separatrix is the boundary between the confined plasma and the open field lines that lead to the divertor, and its shape — especially the X-point geometry — is a primary design lever. Its exact position is reconstructed in real time from magnetic measurements so the control system can hold the plasma steady.",
     "bremsstrahlung": "Bremsstrahlung is an unavoidable loss that grows with density and with impurity charge, and it sets a floor on the temperature a given fuel needs to stay net-positive. It matters most for the hot, high-Z-sensitive D–&sup3;He burner, which is one reason plasma purity and a reflective liner are central to closing its power balance.",
     "radiated-power-fraction": "Deliberately radiating a large share of the exhaust power is the primary tool for protecting the divertor, spreading heat over the whole wall instead of a small target. HYPERION's divertor design depends on a high radiated fraction, which Kronos flags as a performance gate because achieving it while keeping the core clean is a genuine balance.",
     "impurity-seeding": "Seeding a trace of neon or nitrogen makes the plasma edge radiate more and cushions the divertor, but every seeded ion also dilutes the fuel and can radiate from the core. Getting the balance right — enough edge radiation, not too much core contamination — is an active control problem tied to the divertor's radiated-fraction target.",
     "zeff": f"Z<sub>eff</sub> is a compact proxy for how dirty a plasma is: higher values mean more bremsstrahlung and more fuel dilution. HYPERION is designed at a clean Z<sub>eff</sub> of {F['b_Zeff']}, which its heating budget and power balance assume — keeping it there is a job for wall conditioning, controlled seeding and good exhaust.",
     "neutral-beam-injection": f"Neutral beams are the workhorse heating method: energetic neutral atoms cross the confining field, ionise inside the plasma, and deposit both heat and current-driving momentum. They are part of HYPERION's {F['b_Paux']} auxiliary budget, and their efficiency and geometry feed directly into the steady-state current and the plant power ledger.",
     "electron-cyclotron-heating": "ECRH's great virtue is precision: microwaves tuned to the electron-cyclotron frequency deposit power in a narrow, steerable location, useful not only for heating but for driving local current to suppress a specific tearing mode. That surgical control makes it a key tool for stability as well as heating.",
     "alpha-heating": "In D–T fusion the 3.5 MeV helium nucleus stays confined and heats the plasma, and strong alpha heating is what makes ignition possible. Kronos's driven designs do not rely on alpha heating dominating, which is a deliberately conservative posture — the machine stays controllable because its power tracks the external heating.",
     "fast-ions": "Fast ions from beams or fusion carry energy and drive current, but only if they stay confined long enough to slow down; if they escape early they waste heating and load the wall. They can also excite Alfvén and energetic-particle modes, so managing the fast-ion population is a real part of heating and, in D–T, alpha physics.",
     "turbulent-transport": "Micro-turbulence, driven by the plasma's own gradients, leaks heat far faster than collisions alone and is the dominant reason confinement is hard to predict. Kronos sidesteps the prediction problem by anchoring its confinement to the empirical H-mode database, which already folds in typical turbulent losses, rather than to first-principles optimism.",
     "neoclassical-transport": "Neoclassical transport is the irreducible collisional leakage enhanced by the torus geometry; real machines usually lose more, via turbulence, but it sets the theoretical floor. It is also the source of the bootstrap current, which is why good confinement and self-driven current tend to come together in a well-designed plasma.",
     "spherical-tokamak-not": "",
     "confinement-scaling": f"Scaling laws like IPB98 are how the field turns decades of multi-machine data into a usable prediction of confinement time. Kronos designs to H<sub>98</sub> = {F['b_H98']} — standard scaling, not a hopeful multiple of it — so its {F['b_tauE']} confinement target rests on demonstrated behaviour rather than extrapolation.",
     "plasma-current": f"The plasma current does double duty: its poloidal field is essential to confinement, and its profile shapes stability through the safety factor. Sustaining {F['b_Ip']} indefinitely in steady state means combining the {F['b_fbs']} bootstrap fraction with efficient external drive — the balance that keeps the recirculating power low.",
     "plasma-density": f"Fusion power scales roughly with density squared, so density is a powerful lever — bounded above by the Greenwald limit in a tokamak. The burner, free of that limit, runs at a design density of {F['u_ne']} set by its fuel trajectory, while the breeder operates comfortably within Greenwald.",
     "steam-cycle": "The thermal cycle is mature and reliable but Carnot-limited, converting the breeder's heat to electricity at a bounded efficiency. The burner avoids it entirely with direct conversion — the single biggest reason its plant-level efficiency can exceed a conventional thermal fusion plant's.",
     "carnot-efficiency": f"The Carnot limit is why every thermal power plant, fusion included, tops out well short of unity: efficiency is bounded by the ratio of its temperatures. Direct energy conversion is attractive precisely because it never turns the energy into heat, recovering charged-particle energy at about {F['u_dec']} and sidestepping the ceiling.",
     "beta-limit": f"Beta limits are the stability ceilings on plasma pressure, and running below them with margin is what separates a robust design from a fragile one. HYPERION's &beta;<sub>N</sub> = {F['b_bN']} sits below the no-wall limit, so it does not depend on a conducting wall or active feedback to stay stable — a conservative choice reflected across the design.",
     "high-field-magnets": f"High field is the master lever of compact fusion because machine size and cost fall steeply as field rises. Reaching {F['b_Bpeak']} in the breeder and {F['u_Bplug']} in the burner plug is only possible with REBCO, and the trade is mechanical: higher field means larger forces and tighter fatigue margins — the magnet's binding gate.",
     "magnetic-mirror": "The magnetic mirror is the simplest confinement idea — a straight field stronger at its ends — but simple mirrors leak through the loss cone. Decades of physics (minimum-B stabilisation, the tandem plug, thermal barriers) fixed the leaks, and modern high-field superconductors make the required plug fields attainable, which is what revived the concept for the Kronos burner.",
     "helium-ash": "Helium ash is fusion's exhaust: the helium produced must be pumped out before it dilutes the fuel and cools the plasma. Ash removal ties core physics to the divertor and vacuum systems, and its efficiency sets a practical ceiling on sustainable fusion power — one reason the divertor and cryopumps are performance-critical, not merely protective.",
    }
    G.pop("spherical-tokamak-not", None)
    for slug, para in G.items():
        if para: enrich(slug, add_body=[('p', para)])
