# -*- coding: utf-8 -*-
"""Glossary batch 10 — heating & fast ions, stability control, diagnostics hardware."""
def register(cat, page, F):
    T = [
     ("negative-ion-source","Negative-Ion Beam Source","The ion source that enables high-energy neutral beams.","High-energy neutral beams for large machines use negative ions, because they neutralise efficiently at the required energies. The negative-ion source is a demanding, specialised component of the beam injector.",["nbi-injector","neutral-beam-injection","beam-neutralizer"]),
     ("beam-neutralizer","Beam Neutralizer","Converts accelerated ions into the neutral atoms a beam injects.","After acceleration, the ion beam passes through a neutraliser (a gas or plasma cell) that strips or adds electrons to make neutral atoms, which can then cross the confining field into the plasma. Its efficiency affects overall beam power.",["negative-ion-source","nbi-injector","neutral-beam-injection"]),
     ("beam-shinethrough","Beam Shine-Through","Beam power that passes through the plasma without depositing.","If the plasma is too thin, some neutral-beam power passes straight through ('shine-through') and strikes the far wall instead of heating the plasma. Density and beam energy are matched to minimise it.",["neutral-beam-injection","plasma-density","first-wall"]),
     ("fast-ion-slowing-down","Fast-Ion Slowing-Down","How injected fast ions gradually share their energy with the plasma.","Fast ions from beams or fusion slow down over a characteristic time as they collide, transferring energy to bulk ions and electrons. The slowing-down physics sets how heating and current drive actually deposit.",["fast-ions","neutral-beam-injection","alpha-heating"]),
     ("toroidal-field-ripple","Toroidal-Field Ripple","Small field variations between discrete coils that can lose fast ions.","Because toroidal-field coils are discrete, the field ripples slightly between them, which can let fast ions drift out and strike the wall. Coil number and ferritic inserts are used to limit ripple losses.",["toroidal-field-coil","fast-ions","ripple-loss"]),
     ("ripple-loss","Ripple Loss","Fast-particle losses caused by toroidal-field ripple.","Ripple loss is the escape of fast ions trapped in the field ripple between coils, a localised heat load and a loss of heating efficiency. It is managed by minimising ripple and shaping the field.",["toroidal-field-ripple","fast-ions","first-wall"]),
     ("wall-stabilization","Wall Stabilisation","Using a conducting wall to slow down certain instabilities.","A nearby conducting wall induces currents that stabilise some MHD modes — for a while. Because the wall is resistive, the stabilisation eventually decays into a resistive-wall mode that rotation or feedback must control.",["resistive-wall-mode","plasma-rotation","feedback-stabilization"]),
     ("feedback-stabilization","Feedback Stabilisation","Active coils that sense and cancel a growing instability.","Feedback stabilisation uses sensors and control coils to detect a growing mode and apply a cancelling field in real time. It extends the stable operating space beyond passive limits, at the cost of control complexity.",["wall-stabilization","resistive-wall-mode","real-time-control"]),
     ("mercier-criterion","The Mercier Criterion","A local stability condition for pressure-driven interchange modes.","The Mercier criterion is a local test for stability against pressure-driven interchange modes; passing it everywhere is a basic requirement. Design codes check the Kronos operating point against it.",["ballooning-modes","mhd-stability","plasma-beta"]),
     ("no-wall-limit","The No-Wall Beta Limit","The pressure limit without help from a conducting wall.","The no-wall limit is the maximum stable beta assuming no stabilising wall. Operating below it (as HYPERION does at &beta;<sub>N</sub> = "+F['b_bN']+") is conservative; exceeding it requires wall or feedback stabilisation.",["plasma-beta","beta-limit","wall-stabilization"]),
     ("charge-exchange-spectroscopy","Charge-Exchange Spectroscopy","A beam-based diagnostic of ion temperature and rotation.","By reading light emitted when beam neutrals charge-exchange with plasma ions, this diagnostic measures ion temperature, rotation and impurity density locally. It is a core beam-based measurement.",["spectroscopy","ion-temperature","plasma-rotation"]),
     ("motional-stark-effect","Motional Stark Effect Diagnostic","A beam diagnostic that measures the internal magnetic-field pitch.","The motional Stark effect diagnostic reads polarised beam light to infer the internal magnetic-field-line pitch, giving the current profile — otherwise very hard to measure. It informs stability and scenario control.",["current-profile","q-profile","charge-exchange-spectroscopy"]),
     ("soft-x-ray-array","Soft X-Ray Diagnostics","Detector arrays that image core fluctuations and instabilities.","Soft X-ray detector arrays image the plasma core's emission, revealing MHD modes, sawteeth and islands with high time resolution. They are key to studying and controlling instabilities.",["sawtooth-oscillation","magnetic-island","plasma-diagnostics"]),
     ("bolometer-array","Bolometer Array","A ring of detectors that maps total radiated power.","An array of bolometers views the plasma from many angles to reconstruct where and how much power is radiated — essential for the power balance and for radiative divertor control.",["bolometry","radiated-power-fraction","power-exhaust"]),
     ("neutron-spectrometer","Neutron Spectrometer","Measures the neutron energy spectrum to diagnose the plasma.","A neutron spectrometer resolves the energy of fusion neutrons, revealing ion temperature and fast-ion behaviour from the spectrum's shape and width. It complements simple neutron counting.",["neutron-diagnostics","neutron-spectrum","ion-temperature"]),
     ("mach-probe","Mach Probe","An edge probe that measures plasma flow speed.","A Mach probe measures the flow velocity of edge plasma from the asymmetry of ion current to its faces. It helps characterise scrape-off-layer flows and their effect on exhaust.",["langmuir-probe","sol-flow","scrape-off-layer"]),
     ("dose-rate","Dose Rate","The radiation-exposure rate that governs access and maintenance timing.","Dose rate from activated components sets when and how maintenance can be done — hands-on after decay, or remote otherwise. It follows from the neutron activation and decay of materials.",["activation-products","contact-dose","remote-handling"]),
     ("contact-dose","Contact Dose","The radiation dose at a component's surface after shutdown.","Contact dose is the exposure right at an activated component's surface at a given cooling time; low-activation materials aim to bring it to hands-on levels within decades. It drives maintenance planning.",["dose-rate","low-activation-steel","waste-classification"]),
     ("waste-classification","Waste Classification","Sorting decommissioned material by its radioactivity level.","End-of-life material is classified by activity level, which determines its handling and disposal. Fusion's low-activation strategy aims to keep material in the lowest classes, decaying to clearance in decades.",["fusion-waste","contact-dose","clearance-level"]),
     ("clearance-level","Clearance Level","The activity threshold below which material is no longer regulated as radioactive.","Below a clearance level, material can be recycled or disposed of as ordinary waste. A goal of low-activation design is that most decommissioned material reaches clearance within a manageable time.",["waste-classification","fusion-waste","low-activation-steel"]),
     ("decay-chain","Decay Chain","The sequence by which an activation product relaxes to stability.","Radioactive activation products relax through decay chains of characteristic half-lives. Choosing materials whose decay chains are short and low-hazard is central to the low-activation strategy.",["activation-products","beta-decay","waste-classification"]),
     ("ferritic-insert","Ferritic Inserts","Magnetic inserts used to smooth toroidal-field ripple.","Ferritic steel inserts placed between coils reduce toroidal-field ripple, cutting fast-ion ripple losses. They are a practical fix that improves fast-ion confinement.",["toroidal-field-ripple","ripple-loss","fast-ions"]),
     ("orbit-loss","Orbit Loss","Fast particles lost because their orbits intersect the wall.","Some fast ions have drift orbits wide enough to strike the wall before thermalising — an orbit loss that wastes heating and loads the wall. It is minimised through field design and is worse in small machines.",["fast-ions","banana-orbit","ripple-loss"]),
     ("plasma-facing-lifetime","Component Lifetime","How long plasma-facing and structural parts last before replacement.","Component lifetime — set by heat flux, erosion, neutron damage and fatigue — determines maintenance frequency and thus plant availability. Kronos reports the loadings that drive it rather than assuming long life.",["erosion","dpa","plant-availability"]),
     ("beam-power-balance","Auxiliary Power Balance","Accounting for the heating power a machine draws and where it goes.","The auxiliary power a machine draws (HYPERION's "+F['b_Paux']+") must be tracked against what reaches the plasma and what is lost in the systems — part of the honest plant-level energy ledger.",["heating-systems","recirculating-power","power-balance"]),
     ("plasma-control-system","Plant & Plasma Control System","The integrated system that runs the machine safely and reproducibly.","The control system fuses diagnostics and actuators to run the plasma at its operating point and the plant around it, with the independent safety system beneath it. It is where physics, engineering and software meet.",["real-time-control","instrumentation-control","sis-controller"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
