# -*- coding: utf-8 -*-
"""FAQ batch 4 — product and concept questions."""
def register(cat, page, F):
    Q = [
     ("what-is-hyperion","What is HYPERION?","Kronos's breeder — a compact spherical tokamak that makes neutrons, tritium and helium-3.",
      [f"HYPERION is Kronos's breeder machine: a compact spherical tokamak (Q = {F['b_Q']}, {F['b_Pfus']}) whose product is neutrons, tritium ({F['b_T']}/yr) and helium-3, not grid electricity. It fuels the burner and is a saleable neutron source in its own right.",
       "Building it first is what lets Kronos earn before net electricity is proven."],
      ["hyperion-breeder","spherical-tokamak","the-breeder-first-strategy"]),
     ("what-are-metrovolt-and-aegis","What are MetroVolt and AEGIS?","Two housings of the same D–&sup3;He burner — MetroVolt for grid/data-centre power, AEGIS for defence installations.",
      [f"MetroVolt and AEGIS are the same low-neutron D–&sup3;He burner in different lengths: MetroVolt ({F['u_mv_len']}, {F['u_mv_net']} net) for grid and data-centre power, AEGIS ({F['u_aeg_len']}, {F['u_aeg_net']} net) for fixed defence installations. One physics core, packaged for two markets.",
       "The same reproducible physics underlies both."],
      ["metrovolt","aegis","innovation-modular-housings"]),
     ("how-hot-is-the-plasma","How hot is a Kronos plasma?","Tens to a hundred million degrees — hotter than the Sun's core.",
      [f"HYPERION runs its ions near {F['b_Ti']} (about 170 million K); the D–&sup3;He burner far hotter, around {F['u_Ti']} (over a billion K), because its fuel needs it. Both are far hotter than the Sun's core — which is why magnetic confinement, not material walls, holds them.",
       "The temperature is set by each fuel's reactivity, not chosen arbitrarily."],
      ["ion-temperature","kev-unit","reactivity"]),
     ("what-is-a-tandem-mirror","What is a tandem mirror?","A straight fusion machine plugged at both ends by high-field magnets and an electric potential.",
      [f"A tandem mirror confines plasma in a straight central cell capped by high-field magnetic plugs whose electric potential holds the ions in. The Kronos burner is one, running D–&sup3;He with direct conversion — disruption-free and modular in length. Its plug-density requirement (~{F['u_np']}) is its honest open item.",
       "It is a linear alternative to the doughnut-shaped tokamak."],
      ["tandem-mirror","ambipolar-potential","mirror-approach"]),
     ("is-fusion-radioactive","Is fusion radioactive at all?","Mildly and briefly — activated structure and tritium, but no long-lived high-level waste.",
      ["Fusion's fuels are barely radioactive (tritium, mildly) and it makes no long-lived high-level waste. Its neutrons do activate structural metal, but low-activation materials keep that short-lived, decaying to hands-on levels in decades. The breeder carries most of this; the burner very little.",
       "It is a bounded, manageable issue, not the long-lived legacy of fission."],
      ["fusion-waste","tritium-safety","activation-products"]),
     ("what-can-i-do-with-the-open-data","What can I do with Kronos's open data?","Download it, re-run it, verify the numbers, and cite it — it is CC BY 4.0.",
      ["You can download the five Zenodo deposits, set up the pinned environment, re-run the engines, and reproduce the published numbers yourself — then cite them under CC BY 4.0. The physics also runs live in your browser if you just want to explore.",
       "That openness is the point: check Kronos rather than trust it."],
      ["the-open-deposits","how-to-reproduce","how-to-cite"]),
     ("why-should-a-lab-care","Why should a national lab care about Kronos?","Because everything is reproducible, honestly graded, and anchored to the shared physics database.",
      ["For a national lab, Kronos offers what is easy to evaluate: open, reproducible engines; assumptions anchored to the multi-machine database rather than optimism; per-result fidelity grading; and clearly named gates. It is designed to be scrutinised by exactly that audience.",
       "The team also brings decades of programme experience to the conservative assumptions."],
      ["reproducibility-overview","the-public-programmes","the-scientific-approach"]),
     ("what-is-the-single-biggest-risk","What is the single biggest technical risk?","The burner's plug-density requirement — the one item that most gates net electric power.",
      [f"On the electricity side, the biggest single risk is the burner's plug-density requirement (n_p/n_c &asymp; {F['u_np']}): net power depends on it, and it must be demonstrated. Kronos labels the burner's net power requirement-class for exactly this reason, and the breeder's value does not depend on it.",
       "Naming it as the top risk is part of the honesty framework."],
      ["plug-density-requirement","what-are-the-open-questions","the-breeder-first-strategy"]),
     ("does-kronos-need-lunar-helium3","Does Kronos need helium-3 from the Moon?","No — the breeder makes its own helium-3; lunar sourcing is a long-term option, not a dependency.",
      [f"No. The breeder co-produces about {F['b_He3']} of helium-3 as part of its fuel cycle, giving Kronos an internal terrestrial supply. Lunar helium-3 is a much-discussed long-term resource, but Kronos's plans do not depend on it.",
       "Helium-3's value is framed as strategic, distinct from near-term revenue."],
      ["helium-3-supply","space-power-context","the-neutron-economy"]),
     ("how-does-kronos-make-money-before-electricity","How does Kronos create value before net electricity?","By selling the breeder's products — tritium, neutrons, isotopes and helium-3.",
      [f"The breeder's outputs are valuable in themselves: scarce tritium ({F['b_T']}/yr), a high neutron flux for isotopes and testing, and strategic helium-3. These give Kronos a materials-and-isotopes business independent of solving grid-scale net electricity.",
       "It is the core of the breeder-first strategy and the honest commercial wedge."],
      ["the-breeder-first-strategy","the-neutron-economy","tritium-supply"]),
     ("is-this-like-iter","Is Kronos just a smaller ITER?","No — it is a different architecture and business model, though it builds on the same shared science.",
      ["No. ITER is a large public experiment proving D–T burning-plasma physics; Kronos is a compact, high-field, breeder-first commercial approach with a low-neutron electricity machine. It stands on the shared physics database ITER helped build, but takes a structurally different path to value.",
       "The two are complementary points in the field, not the same thing at different scale."],
      ["kronos-vs-iter","compact-vs-conventional","where-kronos-fits"]),
    ]
    for slug,q,one,ans,rel in Q:
        page(slug,q,"faq",one,one,[('qa',[(q," ".join(f"<p>{a}</p>" for a in ans))])],related=rel,jtype="FAQPage",kicker="Question")
