# -*- coding: utf-8 -*-
"""Glossary batch 24 — plasma waves & speeds, pinch concepts, thermal engineering."""
def register(cat, page, F):
    T = [
     ("alfven-speed","Alfvén Speed","The speed of magnetic waves in a plasma, set by field and density.","The Alfvén speed is how fast magnetohydrodynamic waves travel along field lines, rising with field and falling with density. It sets the timescale of ideal instabilities and Alfvén-eigenmode frequencies.",["alfven-wave","alfven-time","alfven-eigenmodes"]),
     ("ion-sound-speed","Ion Sound Speed","The speed of pressure waves in a plasma, important at the edge.","The ion sound speed governs how pressure disturbances propagate along field lines and sets the flow speed at which plasma enters the divertor sheath. It is a basic edge-physics quantity.",["plasma-sheath","scrape-off-layer","parallel-heat-flux"]),
     ("theta-pinch","Theta and Screw Pinches","Early pinch concepts that compress plasma with induced currents.","Theta and screw pinches compress plasma using azimuthal or combined currents — early confinement ideas that informed later concepts. They are part of the historical toolkit from which mirrors and tokamaks emerged.",["z-pinch","field-reversed-configuration","history-of-fusion"]),
     ("reversed-field-pinch","Reversed-Field Pinch","A toroidal concept with a self-organised, reversed edge field.","The reversed-field pinch confines plasma with a mostly self-generated field that reverses direction at the edge, a relaxed state related to Taylor relaxation. It is an alternative toroidal concept distinct from the tokamak.",["taylor-relaxation","self-organization","the-three-approaches"]),
     ("finite-larmor-radius","Finite-Larmor-Radius Effects","Stabilising effects from a particle's orbit having real size.","Because a particle's gyro-orbit has finite size, it averages over small-scale fluctuations, which can stabilise short-wavelength instabilities. Finite-Larmor-radius effects are part of turbulence and stability theory.",["larmor-radius","micro-instability","gyrokinetics"]),
     ("charge-state","Ion Charge States","How many electrons an impurity ion has lost — it drives radiation.","An impurity's charge state (how ionised it is) depends on temperature and sets which lines it radiates and how much energy it costs the plasma. Tracking charge states is part of impurity and radiation modelling.",["impurity-transport","spectroscopy","radiated-power-fraction"]),
     ("pellet-ablation","Pellet Ablation","How an injected fuel pellet evaporates into the plasma.","As a frozen pellet flies into the plasma it ablates — its surface boils off and ionises — depositing fuel along its path. How deeply it penetrates before fully ablating sets the fuelling profile.",["fueling-pellet","density-peaking","fueling-efficiency"]),
     ("coolant-temperature","Coolant Inlet/Outlet Temperatures","The temperature rise of coolant that sets conversion efficiency.","The difference between coolant inlet and outlet temperatures determines how much energy is carried to conversion and, via the cycle's top temperature, the achievable efficiency. It is a core thermal-hydraulic design parameter.",["primary-coolant","thermal-efficiency","heat-exchanger-component"]),
     ("thermal-stress","Thermal Stress","Stress from temperature gradients across a component.","Temperature differences across a component make it expand unevenly, generating thermal stress that adds to mechanical loads. Managing it — especially in plasma-facing parts — is central to component design and lifetime.",["thermal-fatigue","structural-analysis","plasma-facing-heat-sink"]),
     ("thermal-gradient","Thermal Gradients","Steep temperature changes that drive heat flow and stress.","Steep thermal gradients — from a hot plasma-facing surface to a cooled sink — drive the heat removal that keeps components alive, but also the thermal stress that can crack them. Component design balances the two.",["thermal-stress","critical-heat-flux","first-wall-panel-component"]),
     ("neutral-density","Edge Neutral Density","The population of neutral atoms at the plasma edge.","Neutral atoms from recycling and fuelling populate the edge, fuelling the plasma and enabling detachment through charge exchange and ionisation. Edge neutral density is a key parameter for exhaust and fuelling.",["neutral-recycling","detachment","gas-puffing"]),
     ("plasma-facing-heat-flux","Surface Heat Flux","The heat per area a plasma-facing surface must shed.","Surface heat flux — the power per unit area on the first wall and divertor — sets cooling requirements and lifetime. HYPERION's first wall is designed for "+F['b_wall']+"; the divertor peak is handled by spreading and detachment.",["heat-flux","critical-heat-flux","radiative-divertor"]),
     ("radial-electric-field","Radial Electric Field","An internal electric field that shears flows and improves confinement.","A radial electric field builds up in confined plasmas and, through its shear, suppresses turbulence — a key ingredient of transport barriers and H-mode. It links equilibrium, rotation and confinement.",["exb-shear","transport-barrier","h-mode"]),
     ("plasma-rotation-shear","Rotation Shear","Differential plasma rotation that tears apart turbulence.","Sheared rotation — plasma spinning at different rates across the radius — breaks up turbulent eddies and stabilises some modes, improving confinement. It is one of the main knobs for accessing high performance.",["plasma-rotation","exb-shear","resistive-wall-mode"]),
     ("scrape-off-width","SOL Power Width","The narrow layer that determines divertor heat concentration.","The scrape-off-layer power width sets how tightly exhaust heat is focused at the divertor; a narrow width demands more radiative spreading. It is a critical, actively-studied exhaust parameter.",["lambda-q","power-decay-length","parallel-heat-flux"]),
     ("magnetic-configuration","The Magnetic Configuration","The overall arrangement of fields that confines a given machine.","A machine's magnetic configuration — toroidal plus poloidal in a tokamak, axial plus plugs in a mirror — is the specific field arrangement that confines its plasma. Kronos uses two: a spherical-tokamak field and a tandem-mirror field.",["spherical-tokamak","tandem-mirror","magnetic-confinement"]),
     ("plasma-parameters","Plasma Parameters","The set of numbers that define a plasma's state.","A plasma is characterised by parameters — density, temperature, current, beta, confinement time — whose values define its performance. Kronos's frozen design point is exactly such a set, deposited and reproducible.",["the-breeder-design-point","fusion-triple-product","the-freeze-discipline"]),
     ("operating-point","The Operating Point","The specific set of conditions a machine is designed to run at.","The operating point is the particular combination of density, temperature, current and heating a machine is designed for — the frozen point every Kronos artefact reproduces. Designing a robust window around it is the goal.",["the-breeder-design-point","the-operating-window","the-freeze-discipline"]),
     ("plasma-performance","Plasma Performance","The overall measure of how well a plasma does its job.","Plasma performance rolls up confinement, stability, pressure and purity into how much fusion power a plasma makes and sustains. It is what the triple product and gain figures ultimately express.",["fusion-triple-product","fusion-gain-q","fusion-power-density"]),
     ("design-integration","Design Integration","Bringing physics, engineering and operations into one coherent design.","Design integration reconciles the competing demands of physics, engineering, safety and operations into a single coherent machine. It is the systems-level work that turns a physics point into a buildable, operable plant.",["systems-integration","radial-build","the-path-to-build"]),
     ("plasma-facing-cooling","Active Cooling of Components","Continuously removing heat from plasma-facing and structural parts.","Active cooling circulates coolant through channels in plasma-facing and structural components to remove heat continuously, keeping temperatures within limits. Its adequacy is proven by thermal-hydraulic analysis and testing.",["thermal-hydraulics","primary-coolant","critical-heat-flux"]),
     ("the-power-plant-system","The Integrated Power Plant","How all the systems combine into a generating facility.","An integrated fusion power plant unites the reactor core, magnets, blanket, fuel cycle, conversion, cooling, controls and safety into a facility that reliably generates. Kronos's record spans this whole system, honestly graded by maturity.",["fusion-power-plant","balance-of-plant","technology-readiness"]),
     ("the-kronos-record","The Kronos Public Record","Everything Kronos puts in the open — deposits, model, simulator, library.",
      "The Kronos public record spans five open deposits, an interactive 3D model, a live in-browser simulator, and this technical library — all fed by one frozen design point. It is built so anyone can check the work rather than trust it.",
      ["reproducibility-overview","the-open-deposits","the-3d-model"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
