# -*- coding: utf-8 -*-
"""Glossary batch 26 — closing terms."""
def register(cat, page, F):
    T = [
     ("plasma-beta-toroidal","Toroidal Beta","Plasma pressure compared to the toroidal-field pressure.","Toroidal beta compares plasma pressure to the pressure of the main toroidal field; with poloidal beta it characterises how efficiently a machine uses its field. High total beta at low aspect ratio is HYPERION's advantage.",["plasma-beta","beta-poloidal","spherical-tokamak"]),
     ("plasma-facing-first-mirror-cleaning","First-Mirror Cleaning","Keeping diagnostic optics clear in an eroding, depositing environment.","Because deposition clouds diagnostic first mirrors, in-situ cleaning (plasma or laser based) keeps optical diagnostics working over a campaign. It is part of keeping the diagnostic suite reliable.",["first-mirror","plasma-diagnostics","erosion"]),
     ("neutron-economy-optimization","Optimising the Neutron Economy","Making the most of every fusion neutron — breed, capture, or protect.","Optimising the neutron economy arranges the blanket and shield so each neutron is used well — breeding tritium, making isotopes, or protecting the magnets. On the breeder, whose neutrons are the product, this is a core design goal.",["the-neutron-economy","neutronics-optimization","tbr-margin"]),
     ("plant-availability-target","Availability Targets","The uptime a commercial plant must reach to be viable.","A commercial plant needs high availability, reached as reliability and maintenance mature. Kronos treats early availability as an open study with growth expected, rather than assuming a mature target at first operation.",["availability-factor","availability-growth","rami"]),
     ("the-two-deposits","The Breeder and Burner Deposits","The two core open records behind the two machines.","The breeder and burner each have their own open, reproducible Zenodo deposit — the primary records behind HYPERION's Q = "+F['b_Q']+" and the burner's Q_E = "+F['u_QE']+". Three further deposits cover REBCO, direct conversion and the AI/quantum record.",["the-open-deposits","validation-suite-breeder","validation-suite-burner"]),
     ("the-frozen-point","The Frozen Design Point","The single canonical operating point behind the whole record.","The frozen design point is the one operating point every Kronos artefact reproduces — breeder config 22021 and burner Mode M. Freezing it is what keeps the papers, model, simulator and this library mutually consistent.",["the-freeze-discipline","operating-point","plasma-parameters"]),
     ("reading-this-library","How to Read This Library","A guide to navigating the Kronos technical library.","This library is organised by theme — physics, components, engineering, materials, validation, methodology, safety, applications and more — with a glossary defining every term and dense cross-links. Every figure traces to the frozen design point and the open deposits.",["the-kronos-record","the-open-deposits","reproducibility-overview"]),
     ("plasma-current-alignment","Bootstrap Alignment","Matching the self-driven current to the profile you want.","Advanced steady-state operation aligns the bootstrap current with the desired total current profile, minimising external drive. Good alignment is central to an efficient, high-performance steady-state scenario.",["bootstrap-fraction","advanced-tokamak","current-profile"]),
     ("plasma-facing-replacement-time","Replacement Downtime","How long swapping in-vessel components takes — a key availability driver.","The time to remotely replace worn in-vessel components is a major contributor to planned downtime and thus availability. Modular design and fast remote handling shorten it.",["mean-time-to-repair","remote-handling","plasma-facing-replacement"]),
     ("the-open-model","The Open, Checkable Model","Why Kronos publishes a model anyone can inspect and run.","Kronos publishes an interactive, physics-grounded model and a live solver precisely so anyone can inspect and run the design rather than take it on faith. It is the public expression of a checkable, honest engineering record.",["the-3d-model","the-live-simulator","reproducibility-overview"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
