# -*- coding: utf-8 -*-
"""Glossary batch 23 — final terms: scenarios, plant systems, program concepts."""
def register(cat, page, F):
    T = [
     ("plasma-scenario","Reference Operating Scenario","The canonical discharge a machine is designed to run.","The reference scenario is the canonical discharge — the trajectory and operating point — a machine is designed around, from which variations are developed. For Kronos it is the frozen design point brought to life.",["plasma-startup-scenario","the-breeder-design-point","the-freeze-discipline"]),
     ("plasma-facing-heat-sink","Actively-Cooled Heat Sinks","The cooled structures that carry heat away behind the armour.","Behind the plasma-facing armour, actively-cooled heat sinks (often CuCrZr) conduct heat into the coolant, keeping surface temperatures survivable. They are integral to first-wall and divertor components.",["cucrzr","first-wall-panel-component","thermal-hydraulics"]),
     ("plasma-heating-mix","The Heating Mix","Combining beams and RF to heat, drive current and control the plasma.","Real machines combine heating methods — neutral beams for bulk heating and current, RF for localised control — into a mix tuned to the scenario. HYPERION's "+F['b_Paux']+" is delivered this way.",["heating-systems","neutral-beam-injection","wave-heating"]),
     ("machine-protection","Machine Protection System","The system that shields the hardware from damaging plasma events.","A machine-protection system watches for conditions that could damage hardware — excess heat, stray beams, imminent disruption — and acts to prevent harm, distinct from the personnel safety system. It preserves availability.",["real-time-control","disruption-mitigation","sis-controller"]),
     ("interlock-logic","Interlock Logic","The rules that force the machine to a safe state on fault.","Interlock logic defines the conditions under which the safety system trips heating, fuelling or magnets to reach a safe state. Its independence and integrity are governed by functional-safety standards.",["sis-controller","functional-safety-standards","machine-protection"]),
     ("plasma-termination","Controlled Plasma Termination","Ending a discharge safely and on purpose.","A controlled termination ramps the plasma down safely at the end of a discharge or on command, avoiding a disruption. Reliable termination is part of safe operation, especially for the tokamak breeder.",["current-quench","disruptions","operating-modes"]),
     ("power-handling","Power-Handling Capability","How much power the exhaust systems can take before limits.","Power handling is the exhaust system's capacity to take fusion power without exceeding heat-flux limits — a ceiling on power density set by the divertor. Radiative operation raises it.",["power-exhaust","critical-heat-flux","radiative-divertor"]),
     ("plasma-facing-inventory","In-Vessel Tritium Inventory","Tritium held in the vessel walls, kept low and tracked.","Part of the tritium inventory resides in the in-vessel components through retention and co-deposition. Keeping it low and accounted for is a safety and accountancy priority on the breeder.",["wall-inventory","tritium-accountancy","codeposition"]),
     ("magnet-feeder-system","Magnet Feeder System","The routes that bring power and cryogen to the coils.","The feeder system combines bus-bars, current leads and cryolines that bring electrical power and cooling to the magnets through the cryostat boundary. It is a complex, integrated interface.",["bus-bar","hts-current-lead","cryoline"]),
     ("plasma-diagnostics-integration","Diagnostic Integration","Fitting dozens of instruments into a shielded, activated machine.","Integrating diagnostics means placing many instruments at ports and in the vessel while preserving shielding, vacuum and remote maintainability. It is a demanding systems-integration task.",["diagnostic-port-plug","systems-integration","plasma-diagnostics-suite"]),
     ("fusion-power-plant","The Fusion Power Plant","The complete facility — core, plant, controls — that turns fusion into power.","A fusion power plant integrates the reactor core, the balance of plant, fuel cycle, controls and safety into a working facility. Kronos's design record spans this whole system, honestly graded by maturity.",["balance-of-plant","the-path-to-build","technology-readiness"]),
     ("demonstration-plant","Demonstration vs Commercial Plant","The step from proving the concept to selling the product.","A demonstration plant proves the integrated system works; commercial plants that follow are optimised for cost and availability. Kronos frames its roadmap across this progression, with each step gated.",["prototype-plant","scale-up","deployment-roadmap"]),
     ("plasma-facing-replacement","Component Replacement Cycle","The scheduled swap-out of worn in-vessel parts.","In-vessel components are replaced on a cycle set by their neutron and heat lifetimes, through remote handling. Planning the replacement cycle is central to sustaining availability over plant life.",["blanket-lifetime","maintenance-strategy","remote-handling"]),
     ("energy-multiplication","Blanket Energy Multiplication","Extra heat released by neutron reactions in the blanket.","Exothermic neutron reactions in the blanket release additional energy beyond the fusion neutron's, multiplying the recoverable heat somewhat. It is accounted for in the breeder's thermal power.",["neutronics","gross-thermal-power","blanket"]),
     ("plasma-current-flat-top-duration","Pulse Length & Flat-Top Duration","How long a machine can hold its operating point.","For experiments, flat-top duration measures how long the operating point is sustained; a power plant needs it effectively unlimited — true steady state. It is why non-inductive current sustainment matters.",["flat-top","steady-state-operation","duty-cycle"]),
     ("diagnostic-neutron-shielding","Diagnostic Shielding","Protecting sensitive instruments from radiation.","Diagnostics near the plasma need local shielding so radiation does not blind or damage them, while still allowing them to see the plasma. It is part of diagnostic integration in an activated machine.",["diagnostic-port-plug","shielding","neutron-streaming"]),
     ("plant-electrical-system","Plant Electrical System","The high-power electrical backbone of the facility.","The plant electrical system distributes power to magnets, heating, cryo and auxiliaries, and exports generation to the grid, with protection throughout. It is large but conventional high-voltage engineering.",["electrical-standards","power-supply-converter","grid-interconnection"]),
     ("plasma-fueling-system","The Fuelling System","The combined gas and pellet systems that feed the plasma.","The fuelling system combines gas injection for edge control and pellet injection for core fuelling, feeding the plasma at the rate the fuel cycle and density control require. It links the fuel cycle to the plasma.",["gas-puffing","fueling-pellet","density-control"]),
     ("program-roadmap","The Kronos Programme","The overall arc from open design record to fielded fusion products.","The Kronos programme runs from today's open, frozen design record through component demonstrations and an integrated prototype to the AEGIS and MetroVolt products — each stage gated on evidence. Construction of the HYPERION breeder is scheduled to begin in Q2 2027; the later stages are presented as a staged, honest path rather than a promise of dates.",["deployment-roadmap","gate-reviews","the-breeder-first-strategy"]),
     ("why-kronos-matters","Why the Kronos Approach Matters","A firm, clean, staged path to fusion value — argued in the open.","Kronos matters because it offers a different, verifiable route to fusion's promise: a breeder that earns before net electricity, a clean direct-conversion burner, and a fully open, reproducible record. It is fusion argued on evidence, with its caveats in plain sight.",["the-breeder-first-strategy","honesty-framework","reproducibility-overview"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
