# -*- coding: utf-8 -*-
"""Glossary batch 20 — RAMI, deployment, supply chain, diagnostics, magnet detail."""
def register(cat, page, F):
    T = [
     ("availability-factor","Availability Factor","The fraction of time a plant is available to generate.","The availability factor is the share of time a plant can run, excluding outages — the driver behind capacity factor and revenue. Kronos treats early-life availability as a leading open study.",["capacity-factor","plant-availability","rami"]),
     ("rami","RAMI Analysis","Reliability, Availability, Maintainability and Inspectability — the discipline behind uptime.","RAMI analysis systematically assesses reliability, availability, maintainability and inspectability to predict and improve plant uptime. It turns 'availability' from a hope into an engineered property.",["availability-factor","maintainability","mean-time-to-repair"]),
     ("mean-time-between-failures","Mean Time Between Failures","How long, on average, components run before failing.","MTBF measures component reliability; higher values mean fewer outages. Aggregated across systems, it feeds the availability prediction that sets commercial performance.",["rami","forced-outage","reliability-engineering"]),
     ("mean-time-to-repair","Mean Time to Repair","How quickly a failed component can be restored — driven by remote handling.","MTTR measures how fast maintenance restores a failed component; for an activated machine it is dominated by remote-handling speed and modularity. Short MTTR is essential to high availability.",["rami","remote-handling","maintainability"]),
     ("forced-outage","Forced vs Planned Outages","Unscheduled failures versus scheduled maintenance downtime.","Forced outages are unscheduled failures; planned outages are scheduled maintenance. Minimising forced outages and shortening planned ones together maximise availability.",["availability-factor","maintenance-window","rami"]),
     ("reliability-engineering","Reliability Engineering","Designing systems to fail rarely and safely.","Reliability engineering builds in redundancy, derating and robust design so systems fail rarely and, when they do, safely. It underpins both availability and the safety case.",["redundancy","rami","mean-time-between-failures"]),
     ("supply-chain","The Fusion Supply Chain","The vendors and long-lead items a plant depends on.","A fusion plant draws on a supply chain of specialised vendors — REBCO tape, cryoplants, vessel forgings, heating sources — much of it shared with big science and identified by industry bodies. Managing long-lead items is a real programme task.",["long-lead-items","factory-fabrication","the-path-to-build"]),
     ("long-lead-items","Long-Lead Items","Components whose procurement time paces the build.","Long-lead items — HTS tape, the cold box, vessel forgings, heating sources — take years to procure and pace the construction schedule. Identifying and ordering them early is central to any build plan.",["supply-chain","cold-box","vacuum-vessel-sector"]),
     ("standardization","Standardisation","Repeating proven designs to cut cost and risk.","Standardising components and designs across units cuts cost, shortens schedules and improves reliability. The burner's modular, repeated central-cell units are built for standardisation.",["factory-fabrication","innovation-modular-housings","first-of-a-kind"]),
     ("neutron-yield-monitor","Neutron Yield Monitors","Instruments that continuously measure fusion power via neutrons.","Fission chambers and other neutron monitors count fusion neutrons continuously, giving a real-time, calibrated measure of fusion power. They are core to both control and validation on the breeder.",["neutron-diagnostics","neutron-camera","fusion-power-density"]),
     ("in-vessel-calibration","Diagnostic Calibration","Calibrating instruments so their readings can be trusted.","Diagnostics are calibrated — often with in-vessel sources and cross-checks — so their readings are quantitatively reliable. Calibration is what turns a signal into a trustworthy measurement for control and validation.",["plasma-diagnostics","neutron-yield-monitor","metrology-asbuilt"]),
     ("coil-grading","Conductor Grading","Tailoring conductor along a coil to match the local field.","Grading uses more superconductor where the field is highest and less where it is lower, optimising cost and performance across a coil. It is a magnet-design efficiency applied to high-field windings.",["winding-pack","critical-current-envelope","field-quality"]),
     ("coil-subdivision","Coil Subdivision","Splitting a magnet electrically to ease protection.","Subdividing a large coil into sections eases quench protection and voltage management by limiting the energy and voltage in any one part. It is a protection-oriented magnet-design choice.",["quench-protection","stored-magnetic-energy","quench-heater"]),
     ("valve-box","Cryogenic Valve Box","The hub that distributes and controls cryogen flow.","A valve box houses the valves and manifolds that route cold helium from the cold box to the magnets and shields, controlling the distribution. It is part of the cryogenic distribution system.",["cryoline","cold-box","cryogenic-system"]),
     ("current-lead-optimization","Current-Lead Heat Leak","Minimising the heat the current leads bring into the cold mass.","Current leads inevitably conduct some heat into the cold system; HTS leads and careful design minimise this leak, which otherwise dominates the refrigeration load. It is a key cryogenic-efficiency detail.",["hts-current-lead","thermal-anchoring","cryogenic-system"]),
     ("plasma-facing-qualification","PFC Qualification Testing","High-heat-flux testing that proves plasma-facing components.","Plasma-facing components are proven in high-heat-flux test facilities that reproduce the loads they will see, before installation. It is part of demonstrating the machine can survive operation.",["component-testing","critical-heat-flux","materials-qualification"]),
     ("blanket-testing","Blanket Test Modules","Testing breeding-blanket concepts before full deployment.","Breeding-blanket concepts are proven in test modules that verify breeding, heat recovery and tritium extraction under real conditions. It is how the fuel-cycle technology is matured.",["blanket-module-component","tritium-breeding","component-testing"]),
     ("licensing-pathway","The Licensing Pathway","The regulatory route from design to permitted construction.","Licensing takes a design through a regulatory framework — increasingly a fusion-specific one — to a construction and operating permit. Kronos treats confirming the pathway and filing the safety case as defined steps on the path to build.",["iaea-framework","accident-analysis","the-path-to-build"]),
     ("safety-analysis-report","The Safety Analysis Report","The document that demonstrates a plant is safe to license.","A safety analysis report assembles the accident analyses, source term and defence-in-depth case to demonstrate the plant is safe. Preparing it is a major licensing deliverable on the path to build.",["accident-analysis","licensing-pathway","defense-in-depth"]),
     ("environmental-review","Environmental Review","The assessment of a plant's environmental effects for permitting.","An environmental review assesses water, waste, land and lifecycle effects for permitting. Kronos's environmental screening — with its honestly-flagged uncomputed items — is the technical basis for such a review.",["lifecycle-assessment","water-use","fusion-waste"]),
     ("public-engagement","Public Engagement","Explaining fusion openly to the communities it will serve.","Deploying any energy technology requires engaging the public honestly about its safety, benefits and impacts. Kronos's open, reproducible, caveat-forward record is built for exactly that kind of scrutiny.",["honesty-framework","inherent-safety","reproducibility-overview"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
