# -*- coding: utf-8 -*-
"""Glossary batch 14 — alternative concepts, plasma loads, irradiation effects, energy."""
def register(cat, page, F):
    T = [
     ("field-reversed-configuration","Field-Reversed Configuration","A compact toroid held together by its own current — an alternative confinement concept.","A field-reversed configuration is a self-organised compact toroid confined by its own plasma current with little external field. It is one of several alternative concepts in the field; Kronos uses the more established spherical tokamak and tandem mirror.",["spheromak","the-three-approaches","magnetic-confinement"]),
     ("spheromak","Spheromak","A self-organised plasma ring formed with minimal external coils.","A spheromak is a compact, self-organised plasma torus needing minimal external field. Like the FRC it is an alternative confinement line; it frames the diversity of approaches the field is exploring.",["field-reversed-configuration","the-three-approaches","stellarator"]),
     ("z-pinch","Z-Pinch","Compressing plasma with its own axial current — a pulsed alternative.","A Z-pinch drives a strong axial current whose magnetic field compresses the plasma. Modern sheared-flow-stabilised variants revived interest; it is a distinct, pulsed route from Kronos's steady magnetic approach.",["magneto-inertial","the-three-approaches","inertial-confinement"]),
     ("magneto-inertial","Magneto-Inertial Fusion","A hybrid that magnetises fuel and then compresses it.","Magneto-inertial fusion magnetises a plasma target and then compresses it, blending magnetic and inertial ideas. It is one of the hybrid approaches in the landscape, distinct from Kronos's continuous magnetic confinement.",["z-pinch","inertial-confinement","the-three-approaches"]),
     ("elm-heat-load","ELM Heat Loads","The transient heat pulses ELMs deposit on the divertor.","Each edge-localised mode dumps a burst of energy onto the divertor; large ones can erode or damage it. Suppressing ELMs — as HYPERION's negative triangularity aims to — protects the divertor's life.",["edge-localized-modes","negative-triangularity","heat-flux"]),
     ("disruption-load","Disruption Loads","The heat and force loads a disruption imposes on the machine.","A disruption imposes intense transient heat on the wall and large electromagnetic forces on the structure via halo and eddy currents. Designing to withstand these loads is a major breeder engineering task the burner avoids.",["disruption-physics","halo-current","electromagnetic-analysis"]),
     ("runaway-mitigation","Runaway-Electron Mitigation","Preventing or dissipating the electron beam a disruption can create.","Mitigation systems suppress or dissipate runaway electrons generated in disruptions before they can damage the wall, using injected material to collide with and scatter them. It is part of disruption management on tokamaks.",["runaway-electrons","disruption-mitigation","shattered-pellet"]),
     ("irradiation-hardening","Irradiation Hardening","Neutron damage making structural metals stronger but less ductile.","Neutron irradiation can harden structural metals while reducing their ductility, changing how they respond to stress over life. Managing the hardening–embrittlement trade is part of materials qualification.",["radiation-embrittlement","neutron-damage-materials","materials-qualification"]),
     ("tritium-retention","Tritium Retention in Materials","Tritium trapped in walls that must be limited and recovered.","Plasma-facing and structural materials retain some tritium through implantation and trapping, adding to inventory and needing recovery. Low-retention materials and detritiation manage it — a specific breeder concern.",["wall-inventory","codeposition","detritiation"]),
     ("thermal-conductivity-degradation","Thermal-Conductivity Degradation","Neutron damage lowering a material's ability to conduct heat.","Irradiation can reduce the thermal conductivity of materials over time, worsening their ability to shed heat and shortening component life. It is one of the neutron-damage effects designers account for.",["neutron-damage-materials","dpa","critical-heat-flux"]),
     ("hot-cell","Hot Cell","A shielded facility for handling and examining activated components.","A hot cell is a heavily shielded room where activated components are handled, examined and processed remotely. It supports maintenance, inspection and waste processing for an operated machine.",["remote-handling","waste-processing","decommissioning"]),
     ("waste-processing","Radioactive Waste Processing","Preparing decommissioned material for disposal or recycling.","Waste processing sorts, treats and packages activated material by class, aiming to recycle or clear as much as possible. Fusion's low-activation strategy keeps most material in low, manageable classes.",["waste-classification","clearance-level","hot-cell"]),
     ("energy-return-on-investment","Energy Return on Investment","The energy a plant delivers versus the energy to build and run it.","Energy return on investment compares lifetime energy output to the energy invested in construction and operation. A high value is part of a source being genuinely sustainable, and firm high-output plants tend to score well.",["net-energy-gain","embodied-energy","lifecycle-assessment"]),
     ("embodied-energy","Embodied Energy","The energy locked up in a plant's construction materials.","Embodied energy is the energy used to produce and build a plant's materials — the fair denominator for judging a low-carbon source. Kronos frames its environmental case on this full-lifecycle basis.",["energy-return-on-investment","fusion-carbon-footprint","lifecycle-assessment"]),
     ("deep-decarbonization","Deep Decarbonisation","Eliminating the last, hardest emissions — where firm clean power is decisive.","Deep decarbonisation must address the firm-power, industrial-heat and hard-to-electrify emissions that renewables alone struggle with. Firm, clean fusion is aimed squarely at that hardest part of the problem.",["firm-power","industrial-heat-hydrogen","fusion-vs-solar-wind"]),
     ("disruption-prediction","Disruption Prediction","Using models and machine learning to foresee and avoid disruptions.","Disruption prediction uses physics models and machine learning on diagnostic data to warn of an impending disruption in time to avoid or mitigate it. It is part of the AI/ML control layer, with human oversight.",["disruption-physics","the-ai-ml-stack","anomaly-detection"]),
     ("anomaly-detection","Anomaly Detection","Automatically spotting off-normal machine behaviour early.","Anomaly-detection algorithms watch diagnostic streams for off-normal patterns, flagging problems before they escalate. In Kronos's stack it sits under a human-on-the-loop posture with deterministic safety nets beneath.",["the-ai-ml-stack","disruption-prediction","condition-monitoring"]),
     ("model-predictive-control","Model-Predictive Control","Control that plans ahead using a model of the plasma.","Model-predictive control uses a fast model to anticipate how the plasma will respond and choose actuator moves that keep it on target. It is an advanced control approach for holding a demanding operating point.",["real-time-control","the-simulation-stack","actuator"]),
     ("plasma-state-estimation","Plasma State Estimation","Fusing diagnostics into a real-time picture of the plasma.","State estimation combines many diagnostics into a coherent, real-time reconstruction of the plasma's condition for control to act on. It is the perception layer beneath plasma control.",["real-time-control","plasma-diagnostics-suite","magnetic-diagnostics"]),
     ("beam-target-fusion","Beam–Target vs Thermonuclear Fusion","Fusing a beam into a target versus a hot thermal plasma.","Firing energetic ions at a target produces some fusion but is energy-inefficient; useful power requires thermonuclear fusion in a hot, confined plasma where the whole fuel reacts. Kronos's machines are thermonuclear, not beam-target.",["maxwellian-distribution","reactivity","fusion-basics"]),
     ("fusion-neutron-source","The Fusion Neutron Source","A fusion machine used chiefly to produce neutrons — exactly the breeder's role.","A fusion neutron source is a machine valued for its neutron output rather than net electricity — for breeding, isotopes and materials testing. HYPERION is precisely this: a compact fusion neutron source that is a business in itself.",["hyperion-breeder","the-neutron-economy","neutron-source-product"]),
     ("maintenance-window","Maintenance Windows","The planned outages that bound plant availability.","Availability is set largely by how long and how frequent the maintenance windows are. Fast, remote, modular maintenance shrinks them; Kronos treats this as a key availability driver and open study.",["maintenance-strategy","plant-availability","remote-handling"]),
     ("in-vessel-viewing","In-Vessel Inspection","Remotely viewing the vessel interior to assess component condition.","Between campaigns, remote in-vessel viewing systems inspect the first wall and divertor for erosion and damage, informing maintenance. It is part of operating an activated machine safely.",["in-service-inspection","remote-handling","condition-monitoring"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
