# -*- coding: utf-8 -*-
"""Glossary batch 21 — lifetime neutronics, magnet insulation, cryo heat budget."""
def register(cat, page, F):
    T = [
     ("full-power-year","Full-Power Year","A year of equivalent full-power operation — the unit of accumulated dose.","A full-power year is the exposure a component gets from a year at full power; damage and fluence are quoted in these units. It normalises lifetime across machines with different availability.",["fluence","dpa","blanket-lifetime"]),
     ("magnet-dose-limit","Magnet Radiation Dose Limit","The neutron dose the superconducting magnets can tolerate.","Superconductors and their insulation degrade under neutron dose, so shielding is designed to keep the magnets below a lifetime dose limit. Meeting it in a compact machine is a real neutronics constraint.",["shielding","insulation-dose","fluence"]),
     ("insulation-dose","Insulation Radiation Limit","The radiation dose a magnet's electrical insulation can take.","Organic magnet insulation (epoxies, cyanate esters) tolerates only a limited radiation dose before degrading, often setting the magnet's lifetime dose limit. Radiation-hard insulation and shielding address it.",["magnet-dose-limit","radiation-hard-insulation","shielding"]),
     ("radiation-hard-insulation","Radiation-Hard Insulation","Magnet insulation formulated to survive neutron dose.","Magnet insulation systems — cyanate-ester blends and inorganic options — are chosen to survive the neutron dose behind the shield. Insulation radiation tolerance is a quiet but real magnet-design driver.",["insulation-dose","magnet-dose-limit","winding-pack"]),
     ("static-heat-load","Static Heat Load","The steady heat leak into the cold mass the cryoplant must remove.","The static heat load is the constant heat leaking into the cold system through supports, leads, radiation and residual conduction. Minimising it with insulation and anchoring lowers the refrigeration needed.",["cryogenic-system","mli-insulation","thermal-anchoring"]),
     ("dynamic-heat-load","Dynamic Heat Load","Extra cryogenic load from AC losses, nuclear heating and ramps.","The dynamic heat load is the extra, time-varying cryogenic load from AC losses, eddy currents, nuclear heating and magnet ramps. With the static load it sizes the cryoplant.",["static-heat-load","ac-loss","neutron-heating-rate"]),
     ("nuclear-heating-of-magnets","Nuclear Heating of the Magnets","Neutron and gamma heat deposited in the cold coils, which the shield limits.","Neutrons and gammas reaching the magnets deposit heat directly in the cold mass — an expensive load at cryogenic temperature that the shield is designed to minimise. It is a key reason shielding is so important in a compact breeder.",["kerma","shielding","dynamic-heat-load"]),
     ("wall-conditioning-discharge","Conditioning Discharges","Low-power discharges that clean and prepare the walls.","Conditioning discharges — helium glow, low-power plasmas — clean and prepare the vessel walls between campaigns, controlling impurities and recycling. They are routine operational preparation.",["wall-conditioning","boronization","neutral-recycling"]),
     ("boronization","Boronisation","Coating the walls with boron to reduce oxygen impurities.","Boronisation deposits a thin boron film on the walls to getter oxygen and lower impurity influx, improving plasma purity. It is a common wall-conditioning technique.",["wall-conditioning","zeff","plasma-purity"]),
     ("tungsten-recrystallization","Tungsten Recrystallisation","High-temperature change in tungsten armour that can embrittle it.","Prolonged high temperature can recrystallise tungsten armour, changing its structure and increasing brittleness and cracking risk. Managing surface temperature protects plasma-facing component life.",["tungsten-armor","thermal-fatigue","plasma-facing-lifetime"]),
     ("beryllium-handling","Beryllium Handling","Managing the toxicity of beryllium used as a neutron multiplier.","Beryllium, useful as a neutron multiplier and low-Z material, is toxic as a dust and requires careful industrial handling. It is a conventional occupational-safety consideration in fabrication and maintenance.",["neutron-multiplier","beryllium","radiation-protection"]),
     ("activation-inventory","Activation Inventory","The total radioactive material a machine accumulates over life.","The activation inventory is the total radioactivity built up in structures over the plant's life, dominated by the neutron-rich breeder. Low-activation materials keep it low-hazard and short-lived.",["activation-products","waste-classification","low-activation-steel"]),
     ("gross-thermal-power","Gross Thermal Power","The total heat a fusion plant produces before conversion.","Gross thermal power is the total heat generated — fusion power plus any multiplication — before conversion to electricity. It is the starting point of the power ledger, converted thermally in the breeder or directly in the burner.",["power-balance","power-conversion","net-electric-power"]),
     ("plant-thermal-efficiency","Plant Thermal Efficiency","How much of the gross thermal power becomes net electricity.","Plant thermal efficiency is the ratio of net electricity to gross thermal power, folding in conversion efficiency and parasitic loads. The burner's direct conversion raises it by skipping the Carnot-limited steam cycle.",["thermal-efficiency","direct-energy-conversion","parasitic-load"]),
     ("visible-spectroscopy","Visible & UV Spectroscopy","Reading visible and ultraviolet lines to monitor impurities and the edge.","Visible and ultraviolet spectroscopy identify impurity species and edge conditions from their characteristic emission lines. They are workhorse diagnostics for plasma purity and edge behaviour.",["spectroscopy","zeff","edge-physics"]),
     ("xray-crystal-spectrometer","X-Ray Crystal Spectroscopy","Precise ion-temperature and rotation measurement from X-ray lines.","An X-ray crystal spectrometer resolves the emission lines of highly-ionised impurities to measure ion temperature and rotation precisely in the core. It is a high-accuracy core diagnostic.",["spectroscopy","ion-temperature","plasma-rotation"]),
     ("bremsstrahlung-monitor","Bremsstrahlung Monitor","Measuring continuum radiation to infer Z_eff.","Measuring the visible bremsstrahlung continuum gives a line-averaged Z<sub>eff</sub>, monitoring plasma purity continuously. It complements spectroscopy for impurity assessment.",["bremsstrahlung","zeff","visible-spectroscopy"]),
     ("fleet-deployment","Fleet Deployment","Scaling from single plants to a fleet — where breeding margin matters.","Deploying a fleet of fusion plants requires enough tritium breeding margin (and short doubling time) to fuel new plants, plus standardised, factory-built units. Kronos's breeding surplus and modular burner are designed with fleet growth in mind.",["doubling-time","standardization","tbr-margin"]),
     ("energy-transition-role","Fusion's Role in the Energy Transition","Where firm, clean fusion fits in decarbonising the whole system.","Fusion's role is to provide the firm, clean, dispatchable power that fully decarbonising a grid — including industry and hard-to-electrify demand — ultimately needs. It complements, rather than replaces, cheap renewables.",["deep-decarbonization","firm-power","fusion-vs-solar-wind"]),
     ("classical-transport","Classical Transport","The baseline collisional transport across a magnetic field.","Classical transport is the simplest cross-field leakage, from particles' collisional random walk. Real machines lose far more via neoclassical and turbulent transport, but classical sets the theoretical floor.",["neoclassical-transport","turbulent-transport","cross-field-transport"]),
     ("peeling-ballooning","Peeling-Ballooning Modes","The edge instabilities that trigger ELMs.","Peeling-ballooning modes are the current- and pressure-driven edge instabilities that set the pedestal limit and trigger ELMs. Understanding them guides ELM-control strategies like negative triangularity.",["pedestal","edge-localized-modes","ballooning-modes"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
