# -*- coding: utf-8 -*-
"""Glossary batch 16 — equilibrium detail, neutronics, safety, plant lifetime."""
def register(cat, page, F):
    T = [
     ("shafranov-shift","The Shafranov Shift","The outward shift of a plasma's core as its pressure rises.","As plasma pressure increases, the magnetic axis shifts outward — the Shafranov shift — which the equilibrium and control must accommodate. It links pressure, current and shaping in the force balance.",["plasma-equilibrium","plasma-beta","magnetic-axis"]),
     ("internal-inductance","Internal Inductance","A measure of how peaked the plasma current profile is.","Internal inductance characterises the current-profile shape; a peaked profile has high internal inductance and affects both stability and vertical control. It is a standard equilibrium parameter.",["current-profile","plasma-equilibrium","vertical-displacement-event"]),
     ("safety-factor-on-axis","On-Axis Safety Factor (q0)","The safety factor at the plasma centre, key to sawtooth behaviour.","The central safety factor q&#8320; governs sawtooth activity: when it drops below one, sawteeth appear. Controlling it shapes core stability and performance.",["safety-factor","sawtooth-oscillation","q-profile"]),
     ("sawtooth-period","Sawtooth Period & Inversion Radius","The timing and extent of core sawtooth crashes.","The sawtooth period sets how often the core temperature crashes, and the inversion radius how far out the crash reaches. Both are managed to avoid seeding larger tearing modes.",["sawtooth-oscillation","neoclassical-tearing-mode","safety-factor-on-axis"]),
     ("plasma-diamagnetism","Plasma Diamagnetism","The plasma's tendency to weaken the field within it, sensed for stored energy.","A pressurised plasma is diamagnetic, slightly reducing the internal field; measuring this gives the stored energy via the diamagnetic loop. It is a basic manifestation of plasma pressure.",["plasma-beta","diamagnetic-loop","stored-plasma-energy"]),
     ("l-mode","L-mode (Low-Confinement Mode)","The baseline confinement regime before the H-mode transition.","L-mode is the lower-confinement regime a plasma sits in below the H-mode power threshold, with no edge barrier. The confinement multiplier H<sub>98</sub> is defined relative to H-mode, which roughly doubles L-mode confinement.",["h-mode","l-h-transition","confinement-scaling"]),
     ("power-degradation","Confinement Power Degradation","The empirical fact that confinement worsens as heating rises.","Confinement time falls with increasing heating power (roughly as a negative power), so simply adding heat gives diminishing returns. This degradation is built into the scaling laws Kronos designs against.",["confinement-scaling","energy-confinement-time","profile-stiffness"]),
     ("neutron-albedo","Neutron Reflection & Albedo","Neutrons scattered back from shielding, affecting the neutron budget.","Some neutrons scatter back from surrounding materials (albedo), returning to the breeding zone or reaching unintended places. Accounting for it is part of accurate neutronics.",["neutronics","neutron-streaming","shielding"]),
     ("gas-production-neutronics","Gas Production in Materials","Neutron reactions creating hydrogen and helium gas in structures.","Beyond displacement damage, neutrons create hydrogen and helium gas inside materials via transmutation, driving swelling and embrittlement. Gas-production rates are key neutronics outputs for lifetime.",["helium-production-metals","radiation-swelling","transmutation-rate"]),
     ("shielding-effectiveness","Shielding Effectiveness","How well a shield attenuates neutrons and gammas.","Shielding effectiveness measures how strongly a shield reduces radiation reaching the magnets and outside world. In a compact machine, achieving it in limited space is a real neutronics constraint.",["shielding","biological-shield","neutron-streaming"]),
     ("blanket-lifetime","Blanket & Divertor Lifetime","How long in-vessel components last before replacement.","Neutron damage and heat set how many years the blanket and divertor survive before replacement, driving maintenance scheduling and availability. Kronos reports the loadings that determine it.",["plasma-facing-lifetime","dpa","maintenance-strategy"]),
     ("plant-lifetime","Plant Lifetime","The design service life of the whole facility.","Plant lifetime — decades for the permanent structures, with periodic replacement of in-vessel components — sets the basis for cost and environmental accounting. Long-lived structures with replaceable internals is the design intent.",["blanket-lifetime","lifecycle-assessment","refurbishment"]),
     ("refurbishment","Refurbishment","Periodic renewal of components to extend plant life.","Refurbishment replaces worn in-vessel components and services long-lived systems to extend the plant's productive life. Designing for it is part of the availability and lifecycle story.",["blanket-lifetime","maintenance-strategy","plant-lifetime"]),
     ("mobilizable-inventory","Mobilisable Inventory","The radioactive material that could actually be released in an accident.","Only a fraction of a plant's radioactive inventory is mobilisable — able to be released — chiefly tritium and dust. Fusion's small mobilisable inventory is why its worst-case accident is bounded and mild.",["source-term","tritium-inventory","accident-analysis"]),
     ("accident-analysis","Accident Analysis","Bounding the worst credible events and showing they stay safe.","Accident analysis works through the worst credible events — loss of coolant, loss of vacuum, fires — and shows fusion's physics keeps consequences small and local. It is central to the licensing case.",["loss-of-coolant","loss-of-vacuum","no-evacuation"]),
     ("no-evacuation","The No-Evacuation Goal","Designing so no off-site emergency response is ever needed.","A guiding fusion safety goal is that even a worst-case accident requires no public evacuation — achievable because of the small, bounded source term. It is a defining safety advantage over fission.",["accident-analysis","mobilizable-inventory","inherent-safety"]),
     ("defense-in-depth","Defence in Depth","Layered, independent safety measures so no single failure causes harm.","Defence in depth stacks independent barriers and safety systems so that no single failure leads to harm. Applied to fusion's already-favourable hazards, it makes the safety case robust.",["confinement-barriers","redundancy","passive-safety"]),
     ("dose-to-public","Public Dose Limits","Keeping any public radiation exposure far below regulatory limits.","A plant is designed so routine and accident doses to the public stay well within — typically far below — regulatory limits. Fusion's low source term makes this readily achievable.",["radiation-protection","source-term","no-evacuation"]),
     ("greenwald-scaling","Density-Limit Scaling","How the density limit scales with current and size.","The Greenwald density limit scales with plasma current over minor-radius area, so higher-current, more compact plasmas can run denser. It bounds the operating density on the breeder.",["greenwald-density","plasma-current","operational-envelope"]),
     ("ohmic-confinement","Ohmic Confinement","The confinement regime of an unheated, ohmically-driven plasma.","Before auxiliary heating, a plasma sits in ohmic confinement, whose scaling saturates at higher density. It is the starting regime from which heated scenarios are developed.",["ohmic-heating","l-mode","confinement-scaling"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
