# -*- coding: utf-8 -*-
"""Glossary batch 5 — reactor engineering, power-plant and units vocabulary."""

def register(cat, page, F):
    T = [
     ("neutron-flux","Neutron Flux","How many neutrons cross a unit area per second — the driver of damage and breeding.",
      [f"Neutron flux measures the intensity of the neutron field. It sets both the tritium breeding rate in the blanket and the damage rate in structures. The breeder's {F['b_Pn']} of neutron power makes its flux the design driver; the burner's is far lower."],
      ["neutron-wall-loading","the-neutron-economy","dpa"]),
     ("fusion-triple-product","Fusion Triple Product","Density &times; temperature &times; confinement time — the single figure of merit for fusion performance.",
      ["The triple product combines the three levers of fusion into one number; exceeding a threshold means net power. Kronos designs to it explicitly and reports where each machine sits, rather than quoting temperature alone."],
      ["lawson-criterion","energy-confinement-time","plasma-density"]),
     ("net-electric-power","Net Electric Power","Electricity delivered to the grid after the plant's own consumption.",
      [f"Net electric power is what a plant delivers after subtracting everything it consumes — magnets, cryo, heating, pumps. Kronos reports it per burner housing ({F['u_ref_net']}, {F['u_aeg_net']}, {F['u_mv_net']}) rather than letting plasma gain stand in for it."],
      ["fusion-gain-q","the-burner-design-point","metrovolt"]),
     ("recirculating-power","Recirculating Power","The share of a plant's output it must feed back to run itself.",
      ["Recirculating power is the fraction of gross output consumed by the plant's own systems. Keeping it low is essential to net output, and direct energy conversion helps by cutting conversion losses. It is a core term in the engineering-gain ledger."],
      ["net-electric-power","fusion-gain-q","direct-energy-conversion"]),
     ("blanket-module","Blanket Module","A replaceable segment of the breeding blanket.",
      [f"The breeding blanket is built from modular segments that can be maintained or replaced remotely. Each captures neutrons to breed tritium (toward TBR {F['b_TBR']}) and recover heat. Modularity is central to plant availability."],
      ["blanket","remote-handling","tritium-breeding"]),
     ("first-wall-panel","First-Wall Panel","A replaceable armoured tile assembly facing the plasma.",
      [f"The first wall is assembled from panels — armour bonded to actively-cooled heat sinks — that face the plasma and can be replaced remotely as they wear. HYPERION's panels are rated for {F['b_wall']}."],
      ["first-wall","plasma-facing-materials","cucrzr"]),
     ("divertor-cassette","Divertor Cassette","A remotely-replaceable divertor unit carrying the target plates.",
      ["The divertor is built from cassettes that can be swapped by remote handling. Each carries the high-heat-flux targets that exhaust the plasma. Cassette design balances heat handling against maintainability."],
      ["divertor","remote-handling","tungsten-divertor"]),
     ("heat-exchanger","Heat Exchanger","Transfers fusion heat from the primary loop to the power cycle.",
      ["A heat exchanger passes heat from the blanket's primary coolant to the power-conversion cycle while keeping the loops separate — important for tritium containment on the breeder side. It is conventional power-plant equipment."],
      ["power-conversion","steam-cycle","balance-of-plant"]),
     ("primary-coolant","Primary Coolant","The fluid that carries fusion heat out of the blanket and first wall.",
      ["The primary coolant — water, helium or a liquid metal — removes heat from the blanket and first wall and carries it to power conversion. Its choice couples to breeding, temperature and tritium control."],
      ["blanket","heat-exchanger","fuel-cycle"]),
     ("quench-detection","Quench Detection","Sensing the onset of a magnet quench fast enough to protect it.",
      ["Quench detection watches for the voltage signature of a coil going normal and triggers the energy dump before a hot spot forms. Fast, reliable detection is the first half of quench protection."],
      ["quench-protection","quench-protection-detail","critical-current"]),
     ("cold-mass","Magnet Cold Mass","The assembly of coils and structure held at cryogenic temperature.",
      ["The cold mass is everything kept cold — the superconducting coils and their supporting structure — insulated by the cryostat and cooled by the cryoplant. Its thermal mass and heat leaks set the refrigeration load."],
      ["cryostat","cryogenic-system","magnet-structure"]),
     ("gravity-support","Gravity Supports","The structure that carries the machine's weight while allowing thermal movement.",
      ["Gravity supports hold up the cold mass and vessel while accommodating the large contractions of cool-down and the forces of operation. They are a key structural interface."],
      ["cold-mass","magnet-structure","vacuum-vessel"]),
     ("plant-availability","Plant Availability","The fraction of time a plant can operate — a first-order commercial driver Kronos flags as open.",
      ["Availability depends on component lifetimes and maintenance speed, both driven by remote handling and materials. Kronos treats plant availability as a leading open study rather than an assumed number — a deliberately honest position."],
      ["availability","capacity-factor","remote-handling"]),
     ("mega-ampere","Mega-Ampere (MA)","The unit of the large currents a tokamak plasma carries.",
      [f"Plasma currents are measured in mega-amperes (millions of amperes). HYPERION carries {F['b_Ip']} — a large current in a compact machine, enabled by its shaping and field."],
      ["plasma-current","tesla-unit","spherical-tokamak"]),
     ("tesla-unit","Tesla (T)","The unit of magnetic field strength; higher tesla means a more compact machine.",
      [f"Magnetic field is measured in tesla. Compact fusion is a race to higher tesla: HYPERION reaches {F['b_Bpeak']} at the coil, the burner plug {F['u_Bplug']} — fields only high-temperature superconductors can sustain."],
      ["high-field-magnets","mega-ampere","superconducting-magnets"]),
     ("kev-unit","Kilo-Electron-Volt (keV)","The energy unit for plasma temperature; 1 keV is about 11.6 million kelvin.",
      [f"Plasma temperatures are quoted in keV, where 1 keV &asymp; 11.6 million kelvin. HYPERION runs near {F['b_Ti']}; the D–&sup3;He burner far hotter at {F['u_Ti']}, because its fuel's reactivity peaks higher."],
      ["ion-temperature","reactivity","d-he3-fuel"]),
     ("mev-unit","Mega-Electron-Volt (MeV)","The energy unit for fusion reaction products and neutrons.",
      ["Fusion energies are quoted in MeV. D–T releases 17.6 MeV (14.1 in the neutron); D–&sup3;He 18.3 MeV, all in charged particles. These per-reaction energies are why fusion is so energy-dense."],
      ["the-dt-reaction","the-dhe3-reaction","fusion-basics"]),
     ("neutron-wall-load","Neutron Wall Load","Fusion-neutron power per unit first-wall area — a lifetime driver.",
      [f"The neutron wall load — {F['b_wall']} on HYPERION's first wall — combines with the neutron spectrum to set damage rate and component lifetime. The low-neutron burner's is far gentler."],
      ["neutron-wall-loading","dpa","first-wall"]),
     ("stored-magnetic-energy","Stored Magnetic Energy","The energy held in the magnets, which quench protection must safely remove.",
      ["A high-field magnet stores enormous energy in its field; if it quenches, that energy must be dumped safely. The stored energy sizes the protection circuit and is a key magnet-safety parameter."],
      ["quench-protection","quench-detection","stored-plasma-energy"]),
     ("stored-plasma-energy","Stored Plasma Energy","The thermal energy in the plasma, released during a disruption.",
      ["The plasma's stored thermal energy is what a disruption dumps into the vessel. Its magnitude sets disruption loads on the breeder; the burner, which does not disrupt, avoids this concern."],
      ["disruptions","stored-magnetic-energy","disruption-mitigation"]),
     ("duty-cycle","Duty Cycle","The fraction of time a pulsed machine actually produces power.",
      ["For any machine that pulses, the duty cycle is the on-fraction. A power plant needs a duty cycle near 100% — true steady state — which is why Kronos designs for continuous rather than pulsed operation."],
      ["steady-state-operation","flat-top","plant-availability"]),
    ]
    def make(slug, term, oneliner, paras, rel):
        page(slug, term, "glossary", oneliner, oneliner, [('p', p) for p in paras],
             related=rel, jtype="DefinedTerm", kicker="Glossary")
    for row in T:
        make(row[0], row[1], row[2], row[3], row[4])
