# -*- coding: utf-8 -*-
"""Glossary depth batch F — operations, control, deployment, safety, energy."""
def register(cat, page, F, enrich):
    G = {
     "plasma-breakdown": "Breakdown is the delicate first step of every discharge: a loop voltage ionises the fill gas into a conducting plasma before the current can be ramped. In a compact machine with a small solenoid it is often assisted by electron-cyclotron power, and reliable low-voltage breakdown is a design requirement for operability.",
     "tokamak-startup": "Start-up takes the plasma from breakdown through current ramp-up to the steady flat-top where fusion conditions are held, all while keeping the current and density profiles stable and within the flux budget. It is a physics-rich sequence, especially in a compact machine, and a robust start-up scenario is part of proving the design can actually operate.",
     "flat-top": "The flat-top is the sustained portion of a discharge at constant current where fusion power is produced, and for a power plant it must extend effectively without limit — true steady state. That requirement is why non-inductive current sustainment and a healthy bootstrap fraction matter so much to the breeder.",
     "steady-state-operation": f"A power plant must run continuously, which for the breeder means sustaining its {F['b_Ip']} current indefinitely by combining the {F['b_fbs']} bootstrap fraction with efficient external drive. The burner, driven continuously by heating, is naturally steady-state — one more way its linear architecture simplifies the path to a plant.",
     "first-plasma": "First plasma is a new machine's inaugural discharge — the moment integrated commissioning has succeeded and physics operation can begin. It is a headline milestone but only the start; a stepwise power-ascension campaign then climbs toward the design point, demonstrating performance rather than assuming it.",
     "real-time-control": "A real-time control system fuses diagnostics and actuators — heating, fuelling, current drive, coils — to hold the plasma at its operating point and trip on faults within milliseconds. It is where plasma physics meets control engineering, and in a driven machine it is what makes the output both steady and adjustable.",
     "burn-control": "Burn control keeps fusion power at its set point by trimming fuelling and heating, and in a driven machine it is straightforward: turn the heating down and the power follows. That controllability is a direct consequence of Kronos choosing driven operation over ignition.",
     "machine-protection": "A machine-protection system watches for conditions that could damage hardware — excess heat, stray beams, an impending disruption — and acts to prevent harm, distinct from the personnel safety system. By catching problems before they escalate it preserves both the machine and its availability.",
     "commissioning": "Commissioning bridges construction and operation, taking each system cold, then integrating them — energising magnets, pumping down, validating interlocks — up to first plasma. Each stage has entry and exit criteria and nothing advances until the prior stage passes, which is how a complex new machine is safely brought to life.",
     "maintainability": "Because an operated machine is activated, maintainability — remote-handling access, modular components, replaceable panels — is designed in from the start rather than added later. It is a first-order driver of plant availability, since how quickly worn components can be swapped ultimately sets how much of the time the plant generates.",
     "plant-availability": "Availability — the fraction of time a plant can generate — depends on component lifetimes and maintenance speed, and Kronos treats early-life availability as a leading open study rather than an assumed number. Expecting it to grow with operating experience, rather than starting mature, is part of the honest commercial picture.",
     "the-path-to-build": "The path runs from today's frozen design through closing the binding gates, high-fidelity analysis, material and fabrication qualification, and component demonstration, to licensing and construction. Kronos maps this distance rather than claiming it is already covered — and with breeder construction scheduled to begin in Q2 2027, detailed design and qualification proceed in parallel with the build.",
     "gate-reviews": "The programme advances through evidence-based go/no-go gates — G1 physics freeze (done), then component demonstration, an integrated prototype, and a first product — each with explicit criteria. The binding criteria are the design's largest open items, and naming them as gates is what keeps the roadmap honest rather than aspirational.",
     "technology-readiness": "Technology-readiness assessment grades each subsystem from concept to demonstrated hardware, and Kronos maps its subsystems this way rather than claiming uniform maturity. Most conventional plant is ready for detailed design; the binding gates are named; and no subsystem is claimed construction-ready that is not — the map of the distance left, stated plainly.",
     "deployment-roadmap": "The roadmap runs design study, then component demonstration, an integrated prototype, and commercial products (AEGIS and MetroVolt), gated at each step. Construction of the HYPERION breeder is scheduled to begin in Q2 2027; the later stages Kronos presents as targets with named gates rather than firm dates or guarantees.",
     "inherent-safety": "Fusion's safety is physics, not a bolted-on system: the plasma holds only seconds of fuel and depends on precisely maintained conditions, so any fault makes it cool and stop. There is no chain reaction, no critical mass and no stored energy to drive a runaway — and the linear burner additionally lacks the tokamak's disruption failure mode.",
     "fusion-waste": f"Fusion produces no long-lived high-level waste and no spent fuel — only structural metal made mildly radioactive by neutrons, which low-activation materials keep short-lived. The neutron-rich breeder ({F['b_fn']}) carries most of it and the burner ({F['u_fn']}) very little, and Kronos screens waste class and volume per component rather than assuming the problem away.",
     "tritium-safety": f"Tritium is the breeder's one genuinely radioactive material, a low-energy beta emitter managed with low inventories ({F['b_startup']} startup), permeation barriers, layered containment and continuous monitoring. Because the burner runs low-neutron D–&sup3;He, tritium handling is overwhelmingly a breeder consideration, and Kronos names it as a licensing-relevant gate.",
     "no-proliferation": "A fusion plant produces no plutonium and needs no enriched uranium; its fuels are hydrogen isotopes and helium-3, so fission's proliferation concerns do not arise in the same way. A high neutron flux is a safeguards-and-siting consideration handled by design and oversight, which Kronos treats as part of responsible deployment rather than an empty topic.",
     "firm-power": "Firm power — capacity a grid can rely on at any hour — is the scarce, valuable commodity as grids fill with intermittent renewables, and fusion's steady output is inherently firm. That firmness, delivered by the burner, is the core of its value proposition for grids and data centres, complementing rather than competing with cheap renewables.",
     "baseload-power": "Baseload is the continuous power a grid needs beneath its peaks, and fusion's steady output suits it naturally. The burner is aimed at exactly this firm, point-of-use role, and because it is driven it can also follow load — combining baseload reliability with a degree of dispatchability that intermittent sources cannot offer.",
     "dispatchable-power": "Dispatchable generation can ramp on demand to follow load, and a driven fusion machine — steered by its heating — is dispatchable in principle, an operational advantage over intermittent renewables. Combined with firm baseload capability, it lets a fusion plant play the flexible role gas plays today, without the carbon or fuel-price risk.",
     "capacity-factor": "Capacity factor — energy actually produced over what the plant could produce flat-out — depends on availability, which depends in turn on component lifetimes and maintenance speed. Kronos flags availability, and therefore capacity factor, as a key open study rather than an assumed number, expecting it to improve with operating experience.",
     "energy-transition-role": "Fusion's role in the energy transition is to provide the firm, clean, dispatchable power that fully decarbonising a grid — including industry and hard-to-electrify demand — ultimately needs. It complements cheap renewables rather than replacing them, targeting the hardest, last part of the decarbonisation problem where firmness is decisive.",
     "deep-decarbonization": "Deep decarbonisation must address the firm-power, industrial-heat and hard-to-electrify emissions that renewables alone struggle with, and firm clean fusion is aimed squarely at that hardest part. The burner's firm electricity and the plant's high-grade heat together reach demand that intermittent sources cannot cover.",
     "reduced-order-modeling": "Kronos's deposited engines are reduced-order models — fast, transparent, physics-based calculators that capture the essential balances without the cost of full simulation. They are what make large design-space scans and open reproduction practical, and they run live in the public browser solver; where a claim needs full FEA, CFD or neutronics, Kronos says so.",
     "high-fidelity-analysis": "Beyond the reduced-order engines lies the detailed-design work: full structural and fatigue FEA, thermal-hydraulic CFD, and MCNP-class neutronics that replace scoping estimates with high-fidelity results. Kronos places this on the path to build as scheduled work, the honest distinction between a design study and an engineered machine.",
     "the-open-deposits": f"Kronos publishes its reduced-order engines, inputs and expected outputs as five open Zenodo deposits under CC BY 4.0 — breeder ({F['doi_b']}), burner ({F['doi_u']}), REBCO magnets, direct conversion, and the AI/quantum record. Publishing the engines, not just the conclusions, is what lets a reviewer check Kronos rather than trust it.",
     "reproducibility-overview": "The Kronos answer to 'how do we know?' is a download: the engines, inputs and expected outputs are open and reproduce, byte-exact for deterministic results and within a stated tolerance otherwise. Reproducing a computation proves the number follows from the model and inputs — not that an unbuilt machine will match it, which is why every figure is a computed design target.",
    }
    for slug, para in G.items():
        if para: enrich(slug, add_body=[('p', para)])
