# -*- coding: utf-8 -*-
"""Glossary batch 2 — additional real fusion / plasma / nuclear / engineering terms."""

def register(cat, page, F):
    # (slug, term, one-liner, paragraph(s) as list, related)
    T = [
     ("plasma","Plasma","The fourth state of matter — an ionised gas of free electrons and ions that responds to magnetic fields.",
      ["A plasma is a gas heated until its atoms ionise, separating into free electrons and positively charged ions. Because its charges respond collectively to electric and magnetic fields, a plasma can be shaped, confined and heated magnetically — the basis of every magnetic-confinement fusion machine."],
      ["magnetic-confinement","tokamak","plasma-frequency"]),
     ("tokamak","Tokamak","A toroidal magnetic-confinement device; the most-studied fusion configuration.",
      ["A tokamak confines plasma in a doughnut-shaped magnetic field made from external toroidal-field coils and a current driven through the plasma itself. It is the most experimentally mature fusion configuration. HYPERION is a compact, low-aspect-ratio tokamak — a spherical tokamak."],
      ["spherical-tokamak","stellarator","magnetic-confinement"]),
     ("stellarator","Stellarator","A toroidal device that confines plasma with external coils alone, needing no plasma current.",
      ["A stellarator twists its magnetic field entirely with shaped external coils, so it needs no driven plasma current and does not disrupt. The trade is intricate coil geometry. Kronos does not use a stellarator, but the concept frames why the tokamak's plasma current matters."],
      ["tokamak","magnetic-confinement","disruptions"]),
     ("magnetic-confinement","Magnetic Confinement","Using magnetic fields to hold a hot plasma away from material walls.",
      ["Charged particles spiral along magnetic field lines, so a suitably shaped field can hold a hot plasma suspended away from any wall. Magnetic confinement is the approach behind tokamaks and mirrors alike — both Kronos machines confine magnetically, the burner adding an electrostatic plug."],
      ["inertial-confinement","tokamak","tandem-mirror"]),
     ("inertial-confinement","Inertial Confinement","Compressing fuel so fast it fuses before it can fly apart; the alternative to magnetic confinement.",
      ["Inertial confinement fusion compresses a fuel pellet with lasers or ion beams until it briefly fuses under its own inertia. It is the approach used at the National Ignition Facility. Kronos uses magnetic confinement, a continuous rather than pulsed approach."],
      ["magnetic-confinement","fusion-basics"]),
     ("coulomb-barrier","Coulomb Barrier","The electrostatic repulsion two nuclei must overcome to fuse.",
      ["Nuclei are positively charged and repel each other; the Coulomb barrier is the energy hill they must climb (or quantum-tunnel through) to get close enough for the strong force to bind them. Higher temperature gives nuclei the speed to cross it, which is why fusion needs tens to hundreds of millions of degrees."],
      ["fusion-basics","reactivity","fusion-cross-section"]),
     ("fusion-cross-section","Fusion Cross-Section","A measure of how likely two nuclei are to fuse at a given energy.",
      ["The fusion cross-section quantifies the probability that a collision at a given energy results in fusion. D–T has the largest cross-section at the lowest energy, which is why it is the easiest fuel; D–&sup3;He peaks higher, demanding the burner's "+F['u_Ti']+" operation."],
      ["reactivity","coulomb-barrier","fusion-fuels-overview"]),
     ("reactivity","Reactivity","The temperature-averaged fusion reaction rate for a fuel.",
      ["Reactivity averages the fusion cross-section over the plasma's velocity distribution, giving the reactions-per-second per pair of nuclei at a given temperature. It rises steeply with temperature and is what makes D–T practical at "+F['b_Ti']+" while D–&sup3;He needs far more."],
      ["fusion-cross-section","maxwellian-distribution","fusion-fuels-overview"]),
     ("maxwellian-distribution","Maxwellian Distribution","The bell-curve of particle speeds in a plasma at thermal equilibrium.",
      ["A plasma in thermal equilibrium has a Maxwellian spread of particle velocities. Fusion is driven mostly by the fast tail of that distribution, which is why average temperature is such a sensitive lever on reaction rate."],
      ["reactivity","ion-temperature","thermal-equilibrium"]),
     ("larmor-radius","Larmor Radius","The radius of a charged particle's spiral around a magnetic field line.",
      ["Charged particles gyrate around magnetic field lines at the Larmor (gyro) radius, set by their momentum and the field strength. Small Larmor radii mean tight confinement; higher field shrinks them, one more reason strong magnets help."],
      ["gyrofrequency","magnetic-confinement","high-field-magnets"]),
     ("gyrofrequency","Gyrofrequency","How fast a charged particle spirals around a field line; the basis of cyclotron heating.",
      ["The gyrofrequency is the rate at which a particle orbits a magnetic field line, proportional to field strength. Radio waves tuned to it resonantly heat the plasma — the principle of ion- and electron-cyclotron heating."],
      ["larmor-radius","ion-cyclotron-heating","electron-cyclotron-heating"]),
     ("plasma-frequency","Plasma Frequency","The natural oscillation rate of a plasma's electrons; it sets which waves can propagate.",
      ["Disturb a plasma's electrons and they oscillate at the plasma frequency, set by density. It determines which electromagnetic waves a plasma reflects or transmits, which matters for both heating and diagnostics."],
      ["plasma","plasma-density","electron-cyclotron-heating"]),
     ("scrape-off-layer","Scrape-Off Layer","The thin edge region where field lines lead to the divertor rather than closing on themselves.",
      ["Just outside the confined plasma, magnetic field lines are 'open' — they intersect the divertor. This scrape-off layer carries the exhaust heat and particles to the targets, and its width sets how concentrated that load is."],
      ["divertor","separatrix","heat-flux"]),
     ("separatrix","Separatrix","The boundary between confined, closed flux surfaces and open scrape-off field lines.",
      ["The separatrix is the last closed magnetic surface; inside it the plasma is confined, outside it field lines lead to the divertor. Its shape, including the X-point, is central to divertor design."],
      ["scrape-off-layer","x-point","divertor"]),
     ("x-point","X-Point","The magnetic null where the separatrix crosses itself, steering exhaust to the divertor.",
      ["At the X-point the poloidal magnetic field vanishes and the separatrix forms a cross, directing edge plasma down the legs to the divertor targets. Its position is a key shaping parameter."],
      ["separatrix","divertor","plasma-shaping"]),
     ("toroidal-field","Toroidal Field","The main confining field that runs the long way around a tokamak.",
      [f"The toroidal field, produced by external coils, is the dominant confining field in a tokamak, running the long way around the torus. HYPERION's on-axis toroidal field is {F['b_B0']}, rising to {F['b_Bpeak']} at the coils."],
      [("poloidal-field"),"toroidal-field-coil","high-field-magnets"][:3] if False else ["poloidal-field","toroidal-field-coil","high-field-magnets"]),
     ("poloidal-field","Poloidal Field","The field that runs the short way around, produced mainly by the plasma current.",
      ["The poloidal field wraps the short way around the torus and is produced chiefly by the plasma current, with poloidal-field coils for shaping and position control. Combined with the toroidal field it makes the helical field lines that confine the plasma."],
      ["toroidal-field","plasma-current","central-solenoid"]),
     ("magnetic-shear","Magnetic Shear","How the field-line pitch changes across the plasma; it stabilises turbulence and modes.",
      ["Magnetic shear is the variation of field-line pitch (the safety factor) from the plasma core to edge. Sheared field lines tear apart small instabilities and turbulent eddies, so shear is a stabilising design knob."],
      ["safety-factor","mhd-stability","turbulent-transport"]),
     ("trapped-particles","Trapped Particles","Particles that bounce back and forth in the field's low-field region, tracing banana orbits.",
      ["In a torus the field is weaker on the outboard side, so some particles are magnetically mirrored and bounce rather than circulate, tracing 'banana' orbits. Trapped particles drive both neoclassical transport and the bootstrap current."],
      ["banana-orbit","neoclassical-transport","bootstrap-current"]),
     ("banana-orbit","Banana Orbit","The banana-shaped path a trapped particle traces in a tokamak.",
      ["Projected onto the poloidal plane, a trapped particle's path looks like a banana. The width of these orbits sets the scale of neoclassical transport and underlies the bootstrap current."],
      ["trapped-particles","neoclassical-transport","bootstrap-current"]),
     ("collisionality","Collisionality","How often plasma particles collide; it governs which transport regime a plasma is in.",
      ["Collisionality measures how frequently particles collide relative to their orbital motion. It sets whether a plasma is in the collisional or banana (low-collisionality) regime, which in turn sets the bootstrap current and transport."],
      ["neoclassical-transport","banana-orbit","bootstrap-current"]),
     ("bremsstrahlung","Bremsstrahlung Radiation","Braking radiation from electrons deflected by ions; an unavoidable plasma energy loss.",
      ["When electrons are deflected by ions they emit bremsstrahlung ('braking radiation'). It is an intrinsic energy loss that grows with density and impurity charge, and it sets a floor on the temperature a given fuel needs — especially important for high-temperature fuels like D–&sup3;He."],
      ["synchrotron-radiation","zeff","d-he3-fuel"]),
     ("synchrotron-radiation","Synchrotron Radiation","Radiation from electrons gyrating in the magnetic field; significant at high temperature and field.",
      ["Electrons spiralling in the magnetic field radiate synchrotron emission, a loss that grows with temperature and field. In high-field, high-temperature regimes it must be accounted for, and reflective walls can return much of it to the plasma."],
      ["bremsstrahlung","reflector-liner","high-field-magnets"]),
     ("radiated-power-fraction","Radiated Power Fraction","The share of exhaust power radiated before it reaches the divertor targets.",
      ["Deliberately radiating a large fraction of the exhaust power spreads it over the whole wall instead of concentrating it on the divertor. HYPERION's divertor design relies on a high radiated fraction — an effective technique with a real performance gate attached."],
      ["divertor","impurity-seeding","heat-flux"]),
     ("impurity-seeding","Impurity Seeding","Injecting trace impurities to radiate exhaust power and protect the divertor.",
      ["Seeding small amounts of impurities (such as neon or nitrogen) makes the plasma edge radiate more, cushioning the divertor. It must be balanced against fuel dilution and core radiation — a controlled trade-off."],
      ["radiated-power-fraction","zeff","fuel-dilution"]),
     ("zeff","Effective Charge (Z_eff)","A measure of plasma impurity content; higher Z_eff means more radiation and dilution.",
      [f"Z<sub>eff</sub> is the density-weighted average ion charge, a proxy for impurity content. Higher Z<sub>eff</sub> increases bremsstrahlung losses and dilutes the fuel. HYPERION is designed at a clean Z<sub>eff</sub> of {F['b_Zeff']}."],
      ["bremsstrahlung","fuel-dilution","impurity-seeding"]),
     ("fuel-dilution","Fuel Dilution","The reduction in fusion fuel density caused by impurities and helium ash.",
      ["Every impurity ion and every helium 'ash' nucleus displaces fuel and adds electrons, diluting the reacting mixture. Managing dilution — by exhausting ash and limiting impurities — is essential to sustaining fusion power."],
      ["helium-ash","zeff","impurity-seeding"]),
     ("helium-ash","Helium Ash","The helium produced by fusion, which must be exhausted before it chokes the reaction.",
      ["Fusion produces helium, which accumulates as 'ash'. If not exhausted through the divertor it dilutes the fuel and cools the plasma. Ash removal is a core function of the divertor and pumping systems."],
      ["fuel-dilution","divertor","vacuum-system"]),
     ("neutral-beam-injection","Neutral Beam Injection (NBI)","Firing energetic neutral atoms into the plasma to heat it and drive current.",
      [f"NBI injects a beam of high-energy neutral atoms that ionise inside the plasma, depositing heat and momentum and driving current. It is one of HYPERION's heating methods within its {F['b_Paux']} auxiliary budget."],
      ["heating-systems","current-drive","ion-cyclotron-heating"]),
     ("ion-cyclotron-heating","Ion-Cyclotron Heating (ICRH)","Radio waves tuned to the ion gyrofrequency that heat plasma ions.",
      ["ICRH launches radio-frequency waves at the ion gyrofrequency, resonantly heating the ions. It is a mature, efficient heating method used alongside neutral beams."],
      ["gyrofrequency","heating-systems","electron-cyclotron-heating"]),
     ("electron-cyclotron-heating","Electron-Cyclotron Heating (ECRH)","Microwaves tuned to the electron gyrofrequency for precise, localised heating.",
      ["ECRH uses high-frequency microwaves at the electron gyrofrequency to deposit heat in a narrow, steerable location — useful for heating, current drive and stabilising instabilities."],
      ["gyrofrequency","heating-systems","ion-cyclotron-heating"]),
     ("alpha-heating","Alpha Heating","Self-heating of the plasma by the energetic helium nuclei that fusion produces.",
      ["In D–T fusion the 3.5 MeV helium ('alpha') nucleus stays confined and deposits its energy back into the plasma. Strong alpha heating is what makes ignition possible; Kronos's driven design does not rely on it dominating."],
      ["ignition-vs-driven","fast-ions","dt-fuel"]),
     ("fast-ions","Fast Ions","Energetic ions from heating or fusion that must stay confined to deposit their energy.",
      ["Fast ions — from neutral beams or fusion products — carry energy and current but can drive instabilities if not well confined. Their behaviour is a key part of heating and current-drive physics."],
      ["neutral-beam-injection","alpha-heating","alfven-eigenmodes"]),
     ("alfven-eigenmodes","Alfvén Eigenmodes","Waves that fast ions can excite, potentially expelling them before they deposit energy.",
      ["Fast ions can resonantly drive Alfvén waves that, if strong, transport the fast ions out before they heat the plasma. Keeping these modes benign is part of fast-ion management."],
      ["fast-ions","alfven-wave","mhd-stability"]),
     ("alfven-wave","Alfvén Wave","A fundamental magnetohydrodynamic wave travelling along magnetic field lines.",
      ["Alfvén waves are transverse oscillations of the magnetic field and plasma together, travelling along field lines. They underlie several fast-ion instabilities and are a basic building block of plasma dynamics."],
      ["alfven-eigenmodes","mhd-stability","magnetic-reconnection"]),
     ("magnetic-reconnection","Magnetic Reconnection","The rearrangement of field-line topology that releases magnetic energy, e.g. in sawteeth.",
      ["Reconnection lets magnetic field lines break and reconnect, converting magnetic energy to heat and motion. In tokamaks it underlies sawtooth crashes and tearing modes."],
      ["sawtooth-oscillation","tearing-mode","mhd-stability"]),
     ("sawtooth-oscillation","Sawtooth Oscillations","Periodic core temperature crashes from a central instability; usually benign but can trigger other modes.",
      ["Sawteeth are repetitive collapses of the plasma core temperature caused by an internal kink and reconnection. Usually tolerable, they can seed larger neoclassical tearing modes, so they are managed."],
      ["magnetic-reconnection","tearing-mode","kink-instability"]),
     ("tearing-mode","Tearing Modes","Resistive instabilities that tear magnetic surfaces into islands, degrading confinement.",
      ["Tearing modes let magnetic surfaces reconnect into islands that short-circuit confinement across them. Neoclassical tearing modes are a common performance limiter, controllable with localised current drive."],
      ["neoclassical-tearing-mode","magnetic-reconnection","electron-cyclotron-heating"]),
     ("neoclassical-tearing-mode","Neoclassical Tearing Mode (NTM)","A pressure-driven magnetic island that can cap achievable beta.",
      ["NTMs are magnetic islands sustained by the loss of bootstrap current inside them. They are a leading beta-limiting instability and are suppressed by driving replacement current at the island with ECRH."],
      ["tearing-mode","beta-limit","electron-cyclotron-heating"]),
     ("kink-instability","Kink Instability","A current-driven mode that bends the plasma column; bounded by the safety factor.",
      ["The kink instability bends or helically distorts the plasma column when the current is too high for the field. Keeping the edge safety factor above about 2–3 avoids the most dangerous kinks."],
      ["safety-factor","mhd-stability","disruptions"]),
     ("resistive-wall-mode","Resistive Wall Mode","A slow instability that grows when a conducting wall's stabilisation leaks away resistively.",
      ["A nearby conducting wall can stabilise some modes, but on the wall's resistive timescale that stabilisation decays, allowing a slow resistive-wall mode to grow. Rotation and feedback control keep it in check."],
      ["mhd-stability","plasma-beta","beta-limit"]),
     ("vertical-displacement-event","Vertical Displacement Event (VDE)","Loss of vertical position control in an elongated plasma, a disruption pathway.",
      [f"Strongly elongated plasmas (HYPERION runs &kappa; = {F['b_kappa']}) are vertically unstable and need active control. A loss of that control is a vertical displacement event, which can lead to a disruption — hence robust position control is essential."],
      ["elongation","disruptions","halo-current"]),
     ("runaway-electrons","Runaway Electrons","Electrons accelerated to high energy during disruptions that can damage the wall.",
      ["In a disrupting plasma, electric fields can accelerate a beam of electrons to tens of MeV. Uncontrolled, this runaway beam can damage the wall, so disruption mitigation aims to avoid or dissipate it."],
      ["disruptions","disruption-mitigation","halo-current"]),
     ("halo-current","Halo Currents","Currents that flow through the vessel during disruptions, exerting large forces.",
      ["During a disruption, part of the plasma current can flow through the surrounding structure as 'halo' current, producing large mechanical forces the vessel must withstand. Their magnitude sets structural design loads."],
      ["disruptions","vertical-displacement-event","vacuum-vessel"]),
     ("disruption-mitigation","Disruption Mitigation","Systems that soften an unavoidable disruption to protect the machine.",
      ["When a disruption cannot be avoided, mitigation systems — massive gas or shattered-pellet injection — radiate the energy away quickly and controllably, limiting heat loads, forces and runaway electrons. Linear mirrors like the burner avoid this failure mode altogether."],
      ["massive-gas-injection","shattered-pellet","disruptions"]),
     ("massive-gas-injection","Massive Gas Injection","Firing a large gas puff to radiate a disruption's energy safely.",
      ["Massive gas injection floods the plasma with impurity gas so the stored energy radiates uniformly rather than striking one spot. It is a primary disruption-mitigation tool."],
      ["disruption-mitigation","shattered-pellet","radiated-power-fraction"]),
     ("shattered-pellet","Shattered Pellet Injection","Shattering a frozen pellet into the plasma to mitigate disruptions.",
      ["A cryogenic pellet is fired and shattered just before entering the plasma, delivering material deep and fast to radiate a disruption's energy. It is the reference mitigation method for large tokamaks."],
      ["disruption-mitigation","massive-gas-injection","fueling-pellet"]),
     ("fueling-pellet","Pellet Fuelling","Injecting frozen fuel pellets to refuel the plasma core efficiently.",
      ["Firing frozen deuterium (or D–T) pellets deposits fuel deeper in the plasma than gas puffing can reach, improving fuelling efficiency and density control."],
      ["gas-puffing","plasma-density","fuel-cycle"]),
     ("gas-puffing","Gas Puffing","Refuelling and controlling edge density by injecting gas.",
      ["Puffing neutral gas at the edge is the simplest fuelling and density-control method; it also feeds impurity seeding. Deeper fuelling uses pellets."],
      ["fueling-pellet","plasma-density","impurity-seeding"]),
     ("decay-heat","Decay Heat","Residual heat from activated materials after shutdown; small for fusion but not zero.",
      ["After shutdown, neutron-activated materials release decay heat as they relax. In fusion it is far smaller than in fission and cannot cause a runaway, but it is accounted for in safety and cooling design."],
      ["activation-products","neutron-damage-materials","can-a-fusion-plant-melt-down"]),
     ("activation-products","Activation Products","Radioactive isotopes created when neutrons transmute structural materials.",
      ["Fusion neutrons can transmute structural atoms into radioactive isotopes. Choosing low-activation materials keeps the resulting waste short-lived and low-hazard — a key materials-selection driver."],
      ["low-activation-steel","neutron-damage-materials","decay-heat"]),
     ("low-activation-steel","Low-Activation Steel (RAFM)","Reduced-activation ferritic-martensitic steel designed to decay quickly after irradiation.",
      ["RAFM steels replace elements that would form long-lived isotopes, so that after irradiation the material decays to hands-on levels in decades rather than millennia. They are a leading structural choice for the neutron-heavy breeder."],
      ["activation-products","neutron-damage-materials","magnet-structure"]),
     ("dpa","Displacements Per Atom (dpa)","A measure of neutron damage — how many times each atom is knocked from its lattice site.",
      ["dpa counts, on average, how many times each atom in a material has been displaced by neutron impacts. It is the standard metric for radiation damage and helps set component lifetimes, especially at the breeder's first wall."],
      ["neutron-damage-materials","first-wall","neutron-wall-loading"]),
     ("neutron-wall-loading","Neutron Wall Loading","The neutron power per unit area striking the first wall.",
      [f"Neutron wall loading is the fusion-neutron power per square metre on the first wall — a driver of damage rate and heat. HYPERION's first-wall load is {F['b_wall']}; the burner's is far lower thanks to its {F['u_fn']} neutron fraction."],
      ["dpa","first-wall","the-neutron-economy"]),
     ("central-solenoid","Central Solenoid","The core magnet that induces and ramps the plasma current.",
      ["The central solenoid acts like a transformer primary, its changing current inducing the plasma current. In a compact spherical tokamak, space for it is tight — part of the centre-column challenge."],
      ["plasma-current","toroidal-field-coil","spherical-tokamak"]),
     ("toroidal-field-coil","Toroidal-Field Coil","The D-shaped coils that generate the main confining field.",
      [f"Toroidal-field coils, wound from REBCO tape, produce the main confining field — up to {F['b_Bpeak']} at the conductor in HYPERION. Their shape and structure must resist enormous magnetic forces."],
      ["toroidal-field","superconducting-magnets","lorentz-force"]),
     ("lorentz-force","Lorentz Force","The force on a current in a magnetic field; what tries to tear a magnet apart.",
      ["A conductor carrying current in a magnetic field feels the Lorentz force. In a high-field magnet these forces are immense, producing hoop stresses the structure must contain — the origin of the magnet's fatigue gate."],
      ["hoop-stress","magnet-structure","magnet-fatigue"]),
     ("hoop-stress","Hoop Stress","The outward tension in a magnet coil from its own Lorentz forces.",
      ["Like pressure in a pipe, the Lorentz forces in a magnet create hoop stress that tries to expand the coil. Containing it drives the choice of high-strength structural alloys and sets the fatigue limit."],
      ["lorentz-force","magnet-structure","magnet-fatigue"]),
     ("magnet-fatigue","Magnet Fatigue","Cyclic stress that can crack a magnet over many pulses — the burner's binding magnet gate.",
      ["Repeated energising cycles fatigue a magnet's structure even when a single cycle is safe. For the burner's high-field plug coil, static loads are acceptable but cyclic fatigue is the binding engineering gate — a limit Kronos states openly."],
      ["hoop-stress","superconducting-magnets","plug-density-requirement"]),
     ("critical-current","Critical Current","The maximum current a superconductor carries before it goes resistive.",
      ["Above its critical current (which falls with field and temperature) a superconductor quenches back to normal resistance. Magnet design keeps operation safely below the critical surface; the REBCO study maps it."],
      ["rebco-tape","critical-field","quench-protection"]),
     ("critical-field","Critical Field","The magnetic field above which a superconductor stops superconducting.",
      ["Each superconductor has a critical field beyond which superconductivity collapses. REBCO's is exceptionally high, which is what lets it reach the "+F['b_Bpeak']+" and "+F['u_Bplug']+" fields Kronos needs."],
      ["rebco-tape","critical-current","high-field-magnets"]),
     ("vacuum-vessel","Vacuum Vessel","The sealed chamber that holds the plasma's ultra-high vacuum.",
      ["The vacuum vessel is the primary containment: a welded, ported chamber holding ultra-high vacuum and providing the first structural boundary. It must withstand disruption forces and provide access for heating and diagnostics."],
      ["vacuum-system","port-plug","halo-current"]),
     ("port-plug","Ports & Port Plugs","Vessel openings that carry heating, diagnostics and maintenance access.",
      ["Ports pierce the vessel and blanket to admit heating beams, diagnostics and remote-handling tools. Their placement trades access against shielding and structural integrity."],
      ["vacuum-vessel","remote-handling","heating-systems"]),
     ("remote-handling","Remote Handling","Robotic maintenance of activated components no human can approach.",
      ["Once a machine has operated, its interior is too activated for hands-on work, so maintenance is done by remote-handling robots through the ports. Designing for remote maintainability is a first-order constraint."],
      ["port-plug","activation-products","the-path-to-build"]),
     ("cryostat","Cryostat","The vacuum enclosure that thermally insulates the cold magnets.",
      ["The cryostat is a large vacuum vessel surrounding the magnets, insulating the cold mass from room-temperature surroundings so the cryoplant only has to remove residual heat leaks."],
      ["cryogenic-system","thermal-shield","superconducting-magnets"]),
     ("thermal-shield","Thermal Shield","An actively-cooled shield that intercepts heat before it reaches the cold magnets.",
      ["Between the cryostat and the cold mass, an actively-cooled thermal shield intercepts radiant heat, cutting the load the cryoplant must remove at the coldest temperature."],
      ["cryostat","cryogenic-system","superconducting-magnets"]),
     ("capacity-factor","Capacity Factor","The fraction of nameplate power a plant actually delivers over time.",
      ["Capacity factor is the ratio of energy actually produced to what the plant could produce running flat-out. For any fusion plant it depends on availability — uptime between maintenance — which Kronos flags as a key open study rather than an assumption."],
      ["availability","baseload-power","the-path-to-build"]),
     ("availability","Availability","The share of time a plant is able to operate; a first-order economic driver.",
      ["Availability — the fraction of time a plant is up and generating — depends on component lifetimes and maintenance. Kronos treats plant availability as a leading open question to be studied, not a number to be assumed."],
      ["capacity-factor","remote-handling","baseload-power"]),
     ("baseload-power","Baseload Power","Steady, always-on generation — a natural fit for firm fusion output.",
      ["Baseload is the continuous, always-on power a grid needs beneath its peaks. Fusion's steady output suits baseload, and the burner's firm, point-of-use character is aimed squarely at it."],
      ["availability","dispatchable-power","metrovolt"]),
     ("dispatchable-power","Dispatchable Power","Generation that can ramp on demand to follow load.",
      ["Dispatchable generation can raise or lower output to follow demand. A driven fusion machine, steered by its heating, is in principle dispatchable — an operational advantage over intermittent sources."],
      ["baseload-power","ignition-vs-driven","capacity-factor"]),
    ]
    def make(slug, term, oneliner, paras, rel):
        page(slug, term, "glossary", oneliner, oneliner, [('p', p) for p in paras],
             related=rel, jtype="DefinedTerm", kicker="Glossary")
    for row in T:
        make(row[0], row[1], row[2], row[3], row[4])
