# -*- coding: utf-8 -*-
"""Physics batch 3 — equilibrium, edge, exhaust, and machine-specific physics."""
def register(cat, page, F):
    P = [
     ("plasma-equilibrium","Plasma Equilibrium","physics","The force balance between plasma pressure and magnetic field that holds a steady plasma.",
      ["A confined plasma sits in equilibrium when the outward push of its pressure balances the inward force of the magnetic field everywhere. In a tokamak this balance is described by the Grad–Shafranov equation, whose solutions are the nested flux surfaces. Finding and controlling equilibrium is the starting point of operation.",
       "The equilibrium sets the plasma's shape, and holding it is the job of the poloidal-field control system."],
      [("Balance","Pressure vs magnetic force")],
      ["magnetic-flux-surface","plasma-shaping","plasma-position-control"]),
     ("power-exhaust","The Power-Exhaust Problem","physics","Getting the fusion power out without destroying the components it flows through.",
      [f"All the power a plasma produces must eventually leave through its surfaces — and concentrating it on a small divertor can exceed material limits. Managing power exhaust, chiefly by radiating a large fraction before it reaches the target, is one of fusion's hardest engineering problems. HYPERION leans on a high radiated fraction, a named gate.",
       "The low-neutron burner's linear geometry gives it a gentler exhaust problem."],
      [("Challenge","Concentrated heat flux")],
      ["divertor","radiated-power-fraction","detachment"]),
     ("edge-physics","Plasma Edge Physics","physics","The thin, complex boundary region that disproportionately sets overall performance.",
      ["The plasma edge — the pedestal and scrape-off layer — punches above its weight: the pedestal height strongly sets core performance (through profile stiffness), and the scrape-off layer governs exhaust. Edge physics is where confinement, stability and exhaust all meet.",
       "HYPERION's negative triangularity is an edge-physics choice aimed at benign ELM behaviour."],
      [("Why it matters","Sets core performance & exhaust")],
      ["pedestal","scrape-off-layer","negative-triangularity"]),
     ("impurity-transport","Impurity Transport","physics","How impurities move through the plasma — to be controlled for purity and radiation.",
      [f"Impurities entering from the wall or seeded for radiation must not accumulate in the core, where they would dilute fuel and radiate away energy. Impurity transport physics governs where they go, and controlling it keeps Z<sub>eff</sub> low (HYPERION targets {F['b_Zeff']}).",
       "It couples edge radiation (good for the divertor) against core contamination (bad for fusion)."],
      [("Goal","Low core impurities")],
      ["zeff","impurity-seeding","fuel-dilution"]),
     ("helium-transport","Helium Ash Transport","physics","How fusion-produced helium moves and must be exhausted.",
      ["Helium 'ash' from fusion must be transported to the edge and pumped out before it dilutes the fuel. Helium transport and exhaust efficiency set a limit on sustainable fusion power, tying core physics to the pumping system.",
       "It is one reason the divertor and vacuum pumping are performance-critical, not just protective."],
      [("Goal","Exhaust ash, avoid dilution")],
      ["helium-ash","fuel-dilution","cryopump"]),
     ("mirror-confinement-physics","Mirror Confinement Physics","physics","How a magnetic mirror traps particles — and why it needs plugging.",
      [f"A magnetic mirror traps particles whose velocity is mostly perpendicular to the field, reflecting them from high-field throats; particles moving too parallel escape through a 'loss cone'. This end loss is the mirror's defining challenge, which the tandem-mirror plug addresses electrostatically — the burner's plug-density requirement.",
       "Understanding the loss cone is understanding why the burner needs its plugs."],
      [("Trap","High-field throats"),("Leak","Loss cone")],
      ["magnetic-mirror","mirror-ratio","end-loss-and-plugging"]),
     ("ambipolar-physics","Ambipolar Confinement Physics","physics","How an electrostatic potential confines a tandem mirror's ions.",
      [f"Because electrons escape a mirror faster than ions, a positive potential builds that then confines the ions electrostatically — ambipolar confinement. In a tandem mirror, dense end plugs deepen this potential deliberately, requiring a plug-to-central density ratio near {F['u_np']} to confine the central-cell ions.",
       "It is the physical mechanism at the heart of the Kronos burner."],
      [("Mechanism","Electrostatic ion confinement")],
      ["ambipolar-potential","plug-density-requirement","tandem-mirror"]),
     ("neutronics","Neutronics","physics","Tracking where fusion neutrons go — to breed, heat, damage or be shielded.",
      [f"Neutronics follows fusion neutrons through the blanket and shield: how many breed tritium, how much energy they deposit as heat, how much damage they do, and how well the magnets are shielded. It ties the plasma's {F['b_Pn']} of neutron power to breeding ratio, heat and component life.",
       "It is central to blanket and shield design on the neutron-rich breeder."],
      [("Tracks","Neutron fate & energy")],
      ["the-neutron-economy","tritium-breeding","shielding"]),
     ("radiation-balance","Plasma Radiation Balance","physics","Balancing useful radiation against radiated energy loss.",
      ["A plasma radiates via bremsstrahlung, synchrotron and line emission. Some radiation is useful (protecting the divertor), some is pure loss (especially at high temperature or impurity content). Balancing the radiation budget is part of closing the power balance, and it especially matters for the hot D–&sup3;He burner.",
       "The burner's reflective liner returns synchrotron radiation to help this balance."],
      [("Balance","Useful vs lost radiation")],
      ["bremsstrahlung","synchrotron-radiation","reflector-liner"]),
     ("startup-physics","Plasma Start-Up Physics","physics","The delicate sequence of breakdown, ramp-up and reaching the operating point.",
      ["Start-up must break down the gas, ramp the current while keeping the profile stable, and reach the operating point without tripping instabilities — all within the flux budget. It is a physics-rich sequence, especially in a compact machine with a small solenoid.",
       "A robust start-up scenario is part of demonstrating operability."],
      [("Sequence","Breakdown &rarr; ramp &rarr; flat-top")],
      ["plasma-breakdown","tokamak-startup","volt-seconds"]),
     ("current-diffusion","Current Diffusion","physics","How the plasma current profile relaxes and evolves over time.",
      ["After the current is driven, it diffuses resistively toward a relaxed profile over a characteristic time. Controlling this evolution — with heating and current drive — keeps the safety-factor profile in a stable, high-performance shape.",
       "It links current drive to stability and advanced scenarios."],
      [("Governs","Current-profile evolution")],
      ["current-profile","q-profile","current-drive"]),
     ("disruption-physics","Disruption Physics","physics","What actually happens in a disruption, and why avoiding it matters.",
      ["A disruption chains together a thermal quench (heat dumped in under a millisecond) and a current quench (current collapsing in milliseconds), generating heat loads, electromagnetic forces and runaway electrons. Understanding the chain is what enables avoidance and mitigation — and why the disruption-free burner is architecturally attractive.",
       "Kronos designs the breeder conservatively to minimise disruption risk."],
      [("Phases","Thermal + current quench")],
      ["disruptions","thermal-quench","disruption-mitigation"]),
    ]
    for slug,title,catk,desc,paras,facts,rel in P:
        page(slug,title,catk,desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
