# -*- coding: utf-8 -*-
"""Cross-category depth batch — materials, methodology, applications, safety, products, engineering."""
def register(cat, page, F):
    def art(slug,title,catk,desc,paras,facts=None,rel=None):
        page(slug,title,catk,desc,desc,[('p',p) for p in paras],facts=facts,related=rel or [],jtype="TechArticle")
    A = [
     # materials
     ("tungsten-armor","Tungsten as Plasma-Facing Armour","materials",
      "The refractory metal of choice for the highest heat-flux surfaces.",
      ["Tungsten has the highest melting point of any metal, low erosion and low tritium retention, making it the reference armour for divertor targets and high-flux first-wall areas. Its brittleness and activation are managed through design and grade selection.",
       "It faces the harshest conditions in the machine and is designed to be inspected and replaced."],
      [("Use","High-flux armour"),("Property","Highest melting point")],
      ["plasma-facing-materials","tungsten-divertor","erosion"]),
     ("copper-alloys","Copper Alloys in Fusion","materials",
      "High-conductivity alloys that carry heat away behind the armour.",
      ["Copper alloys such as CuCrZr combine excellent thermal conductivity with enough strength to serve as actively-cooled heat sinks beneath plasma-facing armour. They are standard in divertor and first-wall heat-removal structures.",
       "On the burner side, copper's reflectivity is also relevant to the liner, traded against activation."],
      [("Use","Heat sinks"),("Alloy","CuCrZr")],
      ["cucrzr","plasma-facing-materials","reflector-liner"]),
     ("structural-alloys","Cryogenic Structural Alloys","materials",
      "High-strength alloys that stay tough at the temperature of superconducting magnets.",
      ["Magnet cases and cold-mass structure use alloys that keep high strength and toughness at cryogenic temperatures — austenitic stainless steels and specialised nickel alloys — to contain immense Lorentz forces. Their fatigue behaviour is the binding magnet gate.",
       "Material choice here is inseparable from the magnet's structural integrity."],
      [("Use","Magnet structure"),("Requirement","Cryogenic toughness")],
      ["magnet-structure","hoop-stress","magnet-fatigue"]),
     ("neutron-multiplier-materials","Neutron-Multiplier Materials","materials",
      "Beryllium and lead used to boost the blanket's neutron count.",
      ["Beryllium and lead multiply neutrons through (n,2n) reactions, raising the blanket's neutron budget so it can breed enough tritium with margin. The choice trades neutron economy against activation and resource considerations.",
       "Multiplier selection is part of closing the breeding balance in a compact machine."],
      [("Materials","Beryllium, lead"),("Role","Raise breeding")],
      ["neutron-multiplier","tritium-breeding","lead-lithium"]),
     # methodology
     ("sensitivity-analysis","Sensitivity & Tornado Analysis","methodology",
      "Ranking which assumptions a result actually depends on.",
      ["Sensitivity analysis varies each input to see how much the result moves, ranking assumptions by influence (often shown as a tornado chart). It tells Kronos — and reviewers — which numbers matter most and where to focus scrutiny.",
       "It is deposited alongside the design point so the dependencies are transparent."],
      [("Output","Ranked dependencies")],
      ["uncertainty-quantification","design-space-exploration","reduced-order-modeling"]),
     ("benchmarking","Benchmarking Against Experiment","methodology",
      "Checking models against real machines before trusting them.",
      ["Kronos benchmarks its models against published experimental results — magnet fields against demonstrated coils, quench against measured cases, confinement against the multi-machine database. Anchoring to experiment is what separates conservative design from optimism.",
       "Benchmarks are reported so the anchoring can be checked."],
      [("Basis","Published experiments")],
      ["confinement-scaling","reproducibility-overview","the-scientific-approach"]),
     ("design-margins","Designing with Margins","methodology",
      "Building in safety factors so a design point is robust, not fragile.",
      ["Good design leaves margin — on stress, temperature, stability and performance — so that real-world variation does not tip the machine out of its envelope. Kronos reports operating windows, not just peaks, precisely to show the margin around its point.",
       "Margin is the difference between a hero number and a buildable design."],
      [("Principle","Robust, not fragile")],
      ["factor-of-safety","the-operating-window","design-basis"]),
     # applications
     ("space-power-context","Fusion and Space Power","applications",
      "A long-term prospect — compact fusion and helium-3 have obvious appeal beyond Earth, framed honestly.",
      ["Compact fusion and helium-3 have clear long-term appeal for space power and propulsion, and lunar helium-3 is often discussed as a resource. Kronos frames space applications as a genuine long-horizon prospect that follows from its terrestrial machines, not a near-term product.",
       "The near-term business is firm power and materials on Earth."],
      [("Horizon","Long-term prospect")],
      ["helium-3","helium-3-for-quantum","the-neutron-economy"]),
     ("desalination-context","Fusion for Desalination","applications",
      "Firm clean power and heat can drive large-scale water desalination.",
      ["Desalination is energy-intensive and increasingly vital; firm, clean fusion power and heat could drive it at scale without carbon. It is one of several applications of the burner's firm output beyond electricity markets.",
       "Like all such applications, it inherits the design-stage status of the generators."],
      [("Input","Firm power + heat")],
      ["industrial-heat-hydrogen","grid-scale-power","baseload-power"]),
     # safety / environment
     ("lifecycle-assessment","Lifecycle Environmental Assessment","safety",
      "Judging fusion on its whole lifecycle, not just clean operation.",
      ["An honest environmental case looks at the whole lifecycle — construction materials and embodied carbon, operation (zero-carbon, low waste), and decommissioning (short-lived activated material). Kronos frames its environmental screening this way, flagging the items still to be computed.",
       "Zero operational carbon is not the whole story, and Kronos says so."],
      [("Scope","Cradle to grave")],
      ["fusion-carbon-footprint","fusion-waste","water-use"]),
     ("decommissioning","Decommissioning a Fusion Plant","safety",
      "Taking a plant apart at end of life — easier than fission, with mostly short-lived waste.",
      ["At end of life, a fusion plant's activated structure decays far faster than fission waste; with low-activation materials, most of it reaches clearance levels within decades. Decommissioning is a manageable, planned process rather than a millennia-long liability.",
       "It is part of the honest lifecycle picture."],
      [("Waste","Mostly short-lived")],
      ["fusion-waste","clearance-level","low-activation-steel"]),
     ("radiation-protection","Radiation Protection","safety",
      "Keeping doses to workers and public well within limits by design.",
      ["Radiation protection uses shielding, containment and remote handling to keep worker and public doses well within regulatory limits. Fusion's lack of long-lived waste and chain reactions makes this more tractable than in fission, though tritium and activation still require rigour.",
       "Kronos designs to established radiological standards."],
      [("Approach","Shield, contain, remote-handle")],
      ["biological-shield","tritium-safety","tritium-standards"]),
     # products
     ("firm-clean-power-product","The Firm Clean Power Product","products",
      "What Kronos ultimately sells to grids: steady, dispatchable, zero-carbon electricity.",
      [f"The burner's product is firm, dispatchable, zero-carbon electricity — the scarce commodity in a renewable-heavy grid. Delivered by MetroVolt at {F['u_mv_gw']} class or AEGIS for resilient installations, it is generation you can count on at any hour.",
       "It competes on firmness and cleanliness, with cost as the acknowledged open study."],
      [("Product","Firm clean electricity")],
      ["metrovolt","firm-power","grid-scale-power"]),
     ("neutron-source-product","The Neutron-Source Product","products",
      "The breeder as a sellable high-flux neutron source in its own right.",
      [f"Independent of electricity, HYPERION is a high-flux neutron source — {F['b_Pn']} of neutron power — valuable for tritium, isotopes and materials testing. Selling neutron-derived products is the breeder's near-term business.",
       "It is the clearest example of Kronos having a product before net electricity."],
      [("Product","Neutrons & derivatives")],
      ["the-neutron-economy","hyperion-breeder","isotope-platform"]),
     # engineering
     ("interface-control","Interface Control","engineering",
      "Managing every boundary where two subsystems meet.",
      ["Interface control documents and manages the boundaries between subsystems — dimensions, loads, signals, flows — so that independently designed parts fit and function together. The vacuum vessel and control system are the busiest interface hubs.",
       "It is the discipline that keeps a complex machine coherent through detailed design."],
      [("Discipline","Boundary management")],
      ["systems-integration","general-arrangement","the-path-to-build"]),
     ("assembly-sequence","Assembly Sequence","engineering",
      "The ordered plan for building the machine, piece by piece.",
      ["A machine this integrated must be assembled in a strict sequence — base and supports, lower magnets, vessel sectors, in-vessel components, upper magnets, cryostat close, then hook-ups — each step enabling the next. Planning it is part of proving the design is buildable.",
       "The assembly sequence connects the components to the construction path."],
      [("Plan","Ordered build sequence")],
      ["systems-integration","the-path-to-build","remote-handling"]),
    ]
    for slug,title,catk,desc,paras,facts,rel in A:
        art(slug,title,catk,desc,paras,facts,rel)
