# -*- coding: utf-8 -*-
"""Technology — the Kronos engineering and digital technology stack."""
def register(cat, page, F):
    cat("technology", "The Technology Stack",
        "The enabling technologies behind Kronos — high-field magnets, direct conversion, the "
        "plasma and fuel technology, and the digital, AI and simulation stack that designs it.", 3.8)
    P = [
     ("hts-magnet-technology","High-Temperature Superconducting Magnet Technology","REBCO-based magnets are the enabling technology of the whole machine.",
      [f"Kronos's magnet technology is built on REBCO high-temperature superconductor, engineered into winding packs, cases and structure that reach {F['b_Bpeak']} in the breeder and {F['u_Bplug']} in the burner plug. The technology package — conductor, joints, current leads, quench protection, structure — is documented in an open study, benchmarked against demonstrated coils.",
       "High field is the master lever of compact fusion, so this is the technology everything else follows from."],
      [("Conductor","REBCO"),("Peak field",F["b_Bpeak"]),("Study","DOI "+F["doi_rebco"])],
      ["rebco-tape","high-field-magnets","winding-pack"]),
     ("direct-conversion-technology","Direct Energy Conversion Technology","Turning charged-particle energy straight into electricity, the burner's signature technology.",
      [f"The burner's direct-conversion technology decelerates escaping ions against a biased electrode array ('venetian-blind' collector), recovering their energy as electricity at about {F['u_dec']} — no steam cycle. It is backed by its own open deposit and underpins the burner's engineering gain of Q<sub>E</sub> = {F['u_QE']}."],
      [("Efficiency",F["u_dec"]),("Deposit","DOI "+F["doi_dec"])],
      ["direct-energy-conversion","dec-collector-ring","the-dec-record"]),
     ("plasma-technology","Plasma Heating & Control Technology","The heating, current-drive and control technology that runs the plasma.",
      [f"Running a fusion plasma takes a technology suite: neutral beams and RF systems for heating and current drive ({F['b_Paux']} in the breeder), a diagnostic ensemble to see the plasma, and a real-time control system to steer it. Kronos assembles established methods rather than betting on unproven ones."],
      [("Heating",F["b_Paux"]),("Methods","NBI + RF + real-time control")],
      ["heating-systems","real-time-control","plasma-diagnostics-suite"]),
     ("fuel-cycle-technology","Fuel-Cycle Technology","Breeding, extracting and recycling fuel — the technology that makes the plant self-sufficient.",
      [f"The breeder's fuel-cycle technology breeds {F['b_T']} of tritium at TBR {F['b_TBR']}, extracts and purifies it with permeation control and accountancy, and co-produces {F['b_He3']} of helium-3 for the burner. It is a licensing-relevant technology treated as a named gate."],
      [("Tritium",F["b_T"]),("He-3",F["b_He3"])],
      ["fuel-cycle","tritium-extraction-unit","the-neutron-economy"]),
     ("the-simulation-stack","The Simulation Stack","The reduced-order engines and scans that design and validate the machines.",
      ["Kronos's simulation technology is a stack of fast, physics-based reduced-order engines that scan tens of thousands of configurations, quantify uncertainty, and reproduce the frozen point — and that run live in the public model's in-browser solver. Where high-fidelity FEA/CFD/neutronics is needed, it is flagged as scheduled work.",
       "The engines are deposited openly so the simulation stack itself is reproducible."],
      [("Engines","Reduced-order, open"),("Scan","25,000+ configs")],
      ["reduced-order-modeling","design-space-exploration","the-3d-model"]),
     ("the-ai-ml-stack","The AI & ML Stack","The machine-learning layers that support design, control and analysis — openly recorded.",
      [f"Kronos's AI/ML technology spans sensing, control, prediction and orchestration layers, with deterministic safety nets and a human-on-the-loop posture. Its reproducibility record — including an honest quantum resource estimate that finds no near-term crossover — is deposited openly (DOI {F['doi_ai']})."],
      [("Deposit","DOI "+F["doi_ai"]),("Posture","Human-on-the-loop")],
      ["the-ai-quantum-record","reduced-order-modeling","real-time-control"]),
     ("the-live-simulator","The Live In-Browser Simulator","The public tool that runs Kronos's actual physics engine in your browser.",
      ["Kronos's live-simulation technology runs the deposited reduced-order engines directly in a web browser, letting anyone reproduce the breeder and burner numbers interactively. It is the public face of the reproducibility strategy — the engine, not a mock-up.",
       "It shares its physics with the deposits and the 3D model, all fed by the frozen design point."],
      [("Runs","The actual engines")],
      ["reproducibility-overview","the-3d-model","the-simulation-stack"]),
     ("the-digital-model-technology","The Interactive 3D Model Technology","The public, physics-grounded 3D model of both machines.",
      [f"The 3D-model technology renders both machines interactively — rotatable geometry, layer controls, an in-browser solver, and the full frozen point (Q {F['b_Q']} / Q<sub>E</sub> {F['u_QE']}). It is a schematic design instrument, stage one of a model &rarr; shadow &rarr; digital-twin path, and is labelled as such."],
      [("Type","Schematic design instrument")],
      ["the-3d-model","model-shadow-twin","the-live-simulator"]),
     ("materials-technology","Materials Technology","The superconductors, structures and plasma-facing materials the machine depends on.",
      [f"Kronos's materials technology spans REBCO superconductor, high-strength cryogenic structural alloys, refractory plasma-facing armour rated for {F['b_wall']}, and low-activation steels for the neutron-heavy breeder. Material choices are stated with their honest qualification gates — notably magnet cyclic fatigue."],
      [("Superconductor","REBCO"),("First-wall load",F["b_wall"])],
      ["materials-qualification","plasma-facing-materials","low-activation-steel"]),
     ("manufacturing-technology","Manufacturing & Assembly Technology","How the major components are fabricated and integrated.",
      ["The manufacturing technology covers REBCO winding-pack fabrication and impregnation, sector welding and dimensional control of the vessel, PFC bonding, and remote-handling-compatible assembly. Kronos frames fabrication-grade drawings and material qualification as scheduled work on the path to build.",
       "Representative engineering drawings make the build legible without claiming as-built precision."],
      [("Scope","Winding, welding, bonding, assembly")],
      ["materials-qualification","the-path-to-build","remote-handling"]),
    ]
    for slug,title,desc,paras,facts,rel in P:
        page(slug,title,"technology",desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
