# -*- coding: utf-8 -*-
"""Innovations — what is genuinely distinctive about the Kronos approach."""
def register(cat, page, F):
    cat("innovations", "Innovations & Distinctives",
        "What Kronos does differently — the architectural, commercial and cultural choices that "
        "set the breeder–burner approach apart from the rest of the field.", 3.5)
    P = [
     ("innovation-two-machine-architecture","The Two-Machine Architecture","One machine breeds fuel and neutrons; a second burns clean fuel for electricity. Splitting the job is the core innovation.",
      ["Kronos's foundational innovation is refusing to make one machine do everything. A compact D–T breeder is optimised to make tritium, neutrons and helium-3; a separate low-neutron D–&sup3;He burner is optimised to make electricity by direct conversion. Each machine is simpler and better-suited to its job than a single do-it-all reactor.",
       "The principle — 'fuel follows purpose, not platform' — reshapes both the physics and the business model."],
      [("Breeder","Fuel & neutrons"),("Burner","Clean electricity")],
      ["the-breeder-first-strategy","fusion-fuels-overview","innovation-neutron-economy"]),
     ("innovation-neutron-economy","Selling Materials, Not Just Electricity","Kronos's breeder has a product — tritium, neutrons, isotopes, helium-3 — before net electricity is ever proven.",
      ["The decisive commercial innovation is that the breeder's outputs are valuable in themselves. Where most fusion ventures must solve net electricity before they have anything to sell, Kronos has a materials-and-isotopes business that does not wait on the field's hardest milestone. Economics do not hinge on first achieving net-electric gain.",
       "This 'neutron economy' is the honest wedge that lets Kronos build revenue while the electricity machine matures."],
      [("Products","Tritium, neutrons, isotopes, He-3")],
      ["the-neutron-economy","the-breeder-first-strategy","tritium-supply"]),
     ("innovation-low-neutron-burner","The Low-Neutron Direct-Conversion Burner","A D–&sup3;He tandem mirror that makes electricity directly — low-neutron, disruption-free, modular.",
      [f"Combining a low-neutron fuel (D–&sup3;He, {F['u_fn']} neutrons) with a linear tandem-mirror geometry and direct energy conversion ({F['u_dec']}) is a distinctive package: clean electricity without a steam cycle, no disruptions, and a length that scales to the job ({F['u_ref_len']}/{F['u_aeg_len']}/{F['u_mv_len']}).",
       "It is a deliberately different bet from the mainstream single D–T tokamak."],
      [("Fuel","D–&sup3;He"),("Conversion","Direct, "+F["u_dec"]),("Neutron fraction",F["u_fn"])],
      ["tandem-mirror","direct-energy-conversion","kronos-vs-dt-tokamak"]),
     ("innovation-negative-triangularity","Negative Triangularity by Design","Shaping the plasma the 'wrong' way to suppress edge instabilities without extra control systems.",
      [f"HYPERION's negative triangularity (&delta; = {F['b_delta']}) is a distinctive stability choice: it can access good confinement while naturally suppressing edge-localised modes, easing the divertor's life without a bolt-on ELM-control system. It reflects a design philosophy of solving problems through configuration rather than added machinery."],
      [("Triangularity",F["b_delta"]),("Benefit","Passive ELM suppression")],
      ["negative-triangularity","edge-localized-modes","plasma-shaping"]),
     ("innovation-high-field-compact","The High-Field Compact Core","Using REBCO superconductors to reach fields that make a small, economical machine credible.",
      [f"By building its magnets from REBCO high-temperature superconductor, Kronos reaches {F['b_Bpeak']} in the breeder and {F['u_Bplug']} in the burner plug — fields that let a compact machine reach useful performance. High field is the master lever of compact fusion, and Kronos is built around it."],
      [("Breeder field",F["b_Bpeak"]),("Burner plug",F["u_Bplug"])],
      ["high-field-magnets","rebco-tape","compact-vs-conventional"]),
     ("innovation-open-record","Radical Reproducibility as Strategy","Publishing the engines, not just the results — so anyone can check Kronos rather than trust it.",
      ["In a field with a history of over-promising, Kronos treats verifiable openness as a competitive asset: five open Zenodo deposits with the actual reduced-order engines, a public interactive 3D model, and a live in-browser solver. Reproducibility is not a gesture — it is the credibility strategy.",
       "The wager is that serious audiences — labs, technical investors, reviewers — reward what they can independently check."],
      [("Deposits","5, CC BY 4.0")],
      ["reproducibility-overview","the-open-deposits","the-3d-model"]),
     ("innovation-honesty-framework","Honesty as a Moat","Stating every caveat on the same page as every claim — turning candour into credibility.",
      ["Kronos's most unusual innovation may be cultural: low-neutron is never called aneutronic; burner net power is labelled requirement-class; the machines are stated to be unbuilt; economics stay off public technical pages. Diligence finds caveats anyway, so stating them first converts honesty into trust — a durable advantage.",
       "It is a deliberate framework, not a disclaimer bolted on at the end."],
      [("Principle","Caveats with claims")],
      ["honesty-framework","the-scientific-approach","what-are-the-open-questions"]),
     ("innovation-modular-housings","Modular Product Housings","One burner physics, three lengths — grid, defence and data-centre products from the same core.",
      [f"Because the burner's gain and neutron fraction are largely length-independent, the same physics core serves three products by changing length: {F['u_ref_len']} (reference), {F['u_aeg_len']} (AEGIS defence), and {F['u_mv_len']} (MetroVolt grid/data-centre). Product differentiation without redesigning the physics is a distinctive commercial lever."],
      [("Housings","55 / 440 / 1400 m"),("Net","+104 / +850 / +2832 MWe")],
      ["metrovolt","aegis","the-burner-design-point"]),
     ("innovation-isotope-platform","The Isotope & Helium-3 Platform","Turning the breeder's neutron flux into a strategic isotope and helium-3 business.",
      [f"Beyond fusion fuel, the breeder's neutron flux is a platform for scarce materials — medical isotopes and strategic helium-3 ({F['b_He3']} co-produced). Framing the neutron source as a materials platform, distinct from electricity, is part of what makes Kronos a business before net electricity."],
      [("He-3 output",F["b_He3"]),("Also","Medical isotopes")],
      ["isotope-platform","helium-3-for-quantum","the-neutron-economy"]),
     ("innovation-frozen-design","The Frozen-Design Discipline","One canonical operating point every artefact must reproduce — engineering rigour made visible.",
      ["Kronos freezes a single design point so that papers, figures, the 3D model, the live simulator and this library all reproduce the same numbers from the same source. It is a discipline that makes the entire public record self-consistent and auditable — unusual in a field where different documents often carry different numbers."],
      [("Discipline","One canonical point")],
      ["the-freeze-discipline","design-methodology","reproducibility-overview"]),
    ]
    for slug,title,desc,paras,facts,rel in P:
        page(slug,title,"innovations",desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
