# -*- coding: utf-8 -*-
"""Glossary batch 15 — heating waves, magnet winding, cryogenic cooling."""
def register(cat, page, F):
    T = [
     ("fast-wave-heating","Fast-Wave Heating","An ion-cyclotron-range wave used to heat the plasma core.","The fast magnetosonic wave, launched in the ion-cyclotron range, penetrates to the core and heats ions or drives current. It is a mainstay RF heating scheme alongside neutral beams.",["ion-cyclotron-heating","wave-heating","minority-heating"]),
     ("minority-heating","Minority-Ion Heating","Efficiently heating the bulk by resonantly heating a minority ion species.","Adding a small minority ion species whose cyclotron resonance the RF hits lets power be absorbed efficiently and passed to the bulk plasma. It is a widely-used, efficient ICRH scheme.",["fast-wave-heating","ion-cyclotron-heating","mode-conversion"]),
     ("lower-hybrid-wave","Lower-Hybrid Waves","Waves especially effective at driving off-axis plasma current.","Lower-hybrid waves drive current efficiently in the outer plasma, useful for shaping the current profile and sustaining steady state. They are a key current-drive tool where accessible.",["rf-current-drive","current-profile","current-drive"]),
     ("ec-current-drive","Electron-Cyclotron Current Drive","Precisely localised current driven by microwaves, used to stabilise modes.","ECCD drives current in a narrow, steerable location, ideal for suppressing neoclassical tearing modes by replacing the missing island current. It is precise, if less efficient than some methods.",["electron-cyclotron-heating","neoclassical-tearing-mode","rf-current-drive"]),
     ("react-and-wind","React-and-Wind vs Wind-and-React","Two ways to form REBCO into a coil, trading handling against performance.","REBCO magnets are made either by reacting the tape then winding it (react-and-wind) or winding then reacting (wind-and-react). REBCO's tolerance to strain favours react-and-wind, easing manufacture — a real advantage over more brittle conductors.",["winding-pack","rebco-tape","pancake-winding"]),
     ("pancake-winding","Pancake Winding","Building a coil from flat, stacked disc windings.","A pancake-wound coil is assembled from flat spiral 'pancakes' stacked together, a common REBCO construction that eases winding and joint access. Layer winding is the alternative geometry.",["react-and-wind","winding-pack","superconducting-joint"]),
     ("no-insulation-coil","No-Insulation Coils","A REBCO winding technique that improves stability by omitting turn insulation.","No-insulation (or partially-insulated) REBCO coils let current redistribute around a local defect or hot spot, improving stability and quench tolerance, at the cost of slower charging. It is an active magnet-technology choice.",["winding-pack","quench-protection","cryogenic-stability"]),
     ("bus-bar","Bus-Bars & Feeders","The heavy conductors that carry current to the magnets.","Bus-bars and feeders route the magnets' large currents from the power supplies and current leads into the coils, and must handle both the current and the forces on it. They are part of the magnet electrical system.",["hts-current-lead","power-supply-converter","superconducting-joint"]),
     ("joint-resistance","Joint Resistance","The small residual resistance at superconducting splices, a heat source.","Even good superconducting joints have a tiny resistance that dissipates heat under current, adding to the cryogenic load. Minimising joint resistance is important for efficiency and stability.",["superconducting-joint","cryogenic-stability","ac-loss"]),
     ("supercritical-helium","Supercritical Helium Cooling","Cooling magnets with helium above its critical point for stable single-phase flow.","Many superconducting magnets are cooled by supercritical helium — a single-phase fluid that avoids the instabilities of boiling — forced through the conductor. It gives predictable, stable cooling.",["forced-flow-cooling","cryogenic-system","cold-mass"]),
     ("forced-flow-cooling","Forced-Flow Cooling","Pumping coolant through the conductor for reliable heat removal.","Forced-flow cooling pumps cryogen through channels in the conductor, removing heat reliably along the whole coil. It contrasts with bath cooling and suits large, high-field magnets.",["supercritical-helium","cryogenic-stability","cold-mass"]),
     ("cryocooler","Cryocooler","A closed-cycle refrigerator cooling smaller cold components directly.","Cryocoolers provide compact, closed-cycle cooling for current leads, shields and smaller cold components without a full helium plant. They complement the main cryoplant.",["cryogenic-system","hts-current-lead","thermal-anchoring"]),
     ("thermal-anchoring","Thermal Anchoring","Heat-sinking wires and supports to intercept heat leaks.","Thermal anchoring heat-sinks instrumentation wires, supports and leads to intermediate cold stages so their heat does not reach the coldest components. It is a detail that adds up in the cryogenic heat budget.",["cryocooler","mli-insulation","cold-mass"]),
     ("turbomolecular-pump","Turbomolecular Pump","A high-speed rotor pump for high vacuum.","A turbomolecular pump uses fast-spinning blades to fling gas molecules out, reaching high vacuum. With backing pumps it helps establish the base vacuum before cryopumps handle the plasma load.",["vacuum-system","roughing-pump","base-pressure"]),
     ("roughing-pump","Roughing Pump","The backing pump that establishes rough vacuum first.","Roughing pumps bring a chamber from atmosphere down to the pressure where high-vacuum pumps can take over. They are the first stage of the vacuum-pumping train.",["turbomolecular-pump","vacuum-system","base-pressure"]),
     ("ion-pump","Ion Pump","A pump that captures gas by ionising it, for clean ultra-high vacuum.","Ion pumps ionise residual gas and bury it in electrodes, providing clean, vibration-free ultra-high vacuum with no moving parts. They suit maintaining base pressure in sensitive regions.",["vacuum-system","base-pressure","cryopump"]),
     ("recycling-coefficient","Recycling Coefficient","How much plasma returns from the wall as neutral gas.","The recycling coefficient measures the fraction of plasma reaching the wall that returns as neutrals to be re-ionised. High recycling governs edge density and complicates density control.",["neutral-recycling","density-control","wall-conditioning"]),
     ("density-control","Density Control","Holding the plasma density at its target through fuelling and pumping.","Density control balances fuelling (gas, pellets) against pumping and recycling to hold the target density. Good density control is essential to sustaining fusion power and staying below the density limit.",["fueling-pellet","recycling-coefficient","cryopump"]),
     ("fueling-efficiency","Fuelling Efficiency","How much injected fuel actually reaches and stays in the plasma.","Fuelling efficiency measures the fraction of injected fuel that ends up sustaining the plasma rather than being pumped away. Pellet fuelling is more efficient than gas because it penetrates deeper.",["fueling-pellet","density-control","gas-puffing"]),
     ("kerma","Nuclear Heating (KERMA)","The heat neutrons and gammas deposit throughout the machine.","KERMA quantifies the energy neutrons and gamma rays deposit as heat in materials, from the blanket to the magnets. Computing it is central to cooling design and to protecting the superconductors.",["neutronics","monte-carlo-neutronics","shielding"]),
     ("helium-production-metals","Helium Production in Metals","Neutron reactions generating helium that embrittles structures.","Fast neutrons produce helium inside structural metals via (n,&alpha;) reactions; the helium collects at grain boundaries and embrittles the material. Helium production is a key neutron-damage metric for structural lifetime.",["radiation-embrittlement","neutron-damage-materials","dpa"]),
     ("transmutation-rate","Transmutation Rate","How fast neutrons change a material's composition.","The transmutation rate tracks how quickly neutron reactions alter a material's elemental makeup, affecting its properties and activation over life. It feeds both materials and waste analysis.",["transmutation","activation-analysis","neutron-damage-materials"]),
     ("thermal-efficiency","Thermal-Cycle Efficiency","How efficiently the breeder turns heat into electricity.","Thermal efficiency is the fraction of the breeder's heat converted to electricity in its steam cycle, bounded by the Carnot limit. The burner sidesteps this ceiling with direct conversion.",["steam-cycle","carnot-efficiency","power-conversion"]),
     ("parasitic-load","Parasitic (House) Load","The power a plant consumes to run itself.","Parasitic or house load is the electricity a plant uses internally — pumps, cryo, controls — subtracted from gross output to give net. Keeping it low is essential to a good engineering gain.",["recirculating-power","net-electric-power","balance-of-plant"]),
     ("gross-vs-net","Gross vs Net Electric Power","The difference between what a plant generates and what it exports.","Gross electric power is what the generator makes; net is what is left after the plant's own consumption. Kronos reports net figures for the burner housings, the honest measure of what reaches the grid.",["parasitic-load","net-electric-power","fusion-gain-q"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
