# -*- coding: utf-8 -*-
"""Reference devices — public and historical machines that anchor the science.
Factual, widely-published context; positions Kronos's lineage, no competitive claims."""
def register(cat, page, F):
    cat("devices", "Reference Devices",
        "The public and historical machines whose results underpin the fusion database Kronos "
        "designs against — the tokamaks, mirrors and facilities that established the science.", 12.8)
    D = [
     ("device-iter","ITER","The international megaproject building the largest tokamak to prove burning-plasma physics at scale.",
      ["ITER is a large international tokamak under construction to demonstrate a burning D–T plasma at the scale of a power reactor. As a public project it establishes physics and engineering that the whole field, Kronos included, builds on.",
       "Kronos anchors its confinement assumptions to the multi-machine database ITER helped consolidate, taking a compact, high-field route to complementary ends."],
      [("Type","Large D–T tokamak"),("Role","Burning-plasma physics")],
      ["kronos-vs-iter","the-public-programmes","confinement-scaling"]),
     ("device-jet","JET","The Joint European Torus — long the largest operating tokamak and a D–T record-holder.",
      ["JET, the Joint European Torus, was for decades the largest operating tokamak and produced landmark D–T fusion results that helped calibrate confinement scaling. It is a cornerstone of the empirical database.",
       "The scaling laws Kronos designs to draw heavily on machines like JET."],
      [("Type","D–T tokamak"),("Legacy","Confinement database")],
      ["confinement-scaling","device-iter","tokamak-approach"]),
     ("device-nstx","NSTX / NSTX-U","A leading spherical-tokamak experiment establishing low-aspect-ratio, high-beta physics.",
      [f"NSTX and its upgrade are spherical-tokamak experiments that established much of the low-aspect-ratio, high-beta physics Kronos's breeder relies on. HYPERION's beta target (&beta;<sub>N</sub> = {F['b_bN']}) sits within limits observed on such machines.",
       "The spherical-tokamak database is the direct heritage of the Kronos breeder."],
      [("Type","Spherical tokamak"),("Relevance","Breeder heritage")],
      ["spherical-tokamak","plasma-beta","aspect-ratio"]),
     ("device-diii-d","DIII-D","A versatile tokamak that pioneered plasma shaping and negative-triangularity studies.",
      [f"DIII-D is a flexible tokamak known for advancing plasma shaping, transport and stability physics, including experiments on negative triangularity — the configuration HYPERION adopts (&delta; = {F['b_delta']}).",
       "Kronos's shaping choices rest on results from machines like this."],
      [("Type","Shaped tokamak"),("Relevance","Negative-&delta; physics")],
      ["negative-triangularity","plasma-shaping","edge-localized-modes"]),
     ("device-w7x","Wendelstein 7-X","The flagship stellarator demonstrating disruption-free, steady-state confinement.",
      ["Wendelstein 7-X is the leading optimised stellarator, demonstrating that carefully shaped external coils can confine plasma steadily without a plasma current or disruptions. It defines the state of the art for the stellarator route.",
       "Kronos does not use a stellarator, but W7-X frames why the tokamak's current — which the breeder must drive — is a design consideration."],
      [("Type","Stellarator"),("Demonstrates","Disruption-free steady state")],
      ["stellarator","stellarator-approach","disruptions"]),
     ("device-nif","National Ignition Facility","The laser facility that achieved target energy gain in 2022 by inertial confinement.",
      ["The National Ignition Facility uses powerful lasers to compress fuel pellets, and in 2022 achieved fusion energy exceeding the laser energy delivered to the target — a landmark for inertial confinement.",
       "It marks a different, pulsed route to fusion than Kronos's continuous magnetic approach."],
      [("Type","Inertial confinement"),("Milestone","Target gain, 2022")],
      ["inertial-approach","inertial-confinement","the-three-approaches"]),
     ("device-tftr","TFTR","An early US tokamak that ran D–T and helped establish fusion performance records.",
      ["The Tokamak Fusion Test Reactor was among the first to operate with D–T fuel, producing significant fusion power in the 1990s and contributing foundational D–T and confinement data.",
       "It is part of the historical record the modern database rests on."],
      [("Type","D–T tokamak"),("Era","1980s–90s")],
      ["device-jet","confinement-scaling","dt-fuel"]),
     ("device-jt60","JT-60SA","A large superconducting tokamak advancing steady-state and high-beta operation.",
      ["JT-60SA is a large superconducting tokamak supporting steady-state, high-beta research complementary to ITER. It extends the database for advanced operating scenarios.",
       "Its steady-state focus is directly relevant to the challenge Kronos's breeder faces."],
      [("Type","Superconducting tokamak"),("Focus","Steady state")],
      ["steady-state-operation","plasma-beta","device-iter"]),
     ("device-gdt","The Gas-Dynamic Trap","A mirror experiment demonstrating stable, high-beta open-ended confinement.",
      [f"The Gas-Dynamic Trap is a leading magnetic-mirror experiment that has demonstrated stable, high-beta operation and advanced sloshing-ion and plug physics — the modern basis for taking mirrors seriously again.",
       f"It is direct heritage for the Kronos burner, whose plug-density requirement (n_p/n_c &asymp; {F['u_np']}) builds on this line of work."],
      [("Type","Magnetic mirror"),("Relevance","Burner heritage")],
      ["mirror-approach","tandem-mirror","history-of-mirrors"]),
     ("device-tmx","TMX and Historical Tandem Mirrors","The 1980s experiments that established tandem-mirror plugging physics.",
      ["The Tandem Mirror Experiment and its contemporaries in the 1980s demonstrated the ambipolar-plug principle and thermal barriers that define the tandem-mirror concept. Their physics — reworked with modern high-field magnets — underpins the Kronos burner.",
       "The burner is a modern realisation of this heritage."],
      [("Type","Tandem mirror"),("Era","1980s")],
      ["ambipolar-potential","thermal-barrier","history-of-mirrors"]),
     ("device-east-kstar","EAST and KSTAR","Superconducting tokamaks demonstrating long-pulse operation.",
      ["EAST and KSTAR are superconducting tokamaks that have pushed long-pulse, steady-state operation to hundreds of seconds, extending the database for continuous operation.",
       "Long-pulse results inform the steady-state design goals of the Kronos breeder."],
      [("Type","Superconducting tokamaks"),("Focus","Long pulse")],
      ["steady-state-operation","device-jt60","flat-top"]),
     ("device-alcator","Alcator C-Mod","A compact, high-field tokamak that showed the payoff of strong magnetic fields.",
      [f"Alcator C-Mod was a compact, high-field copper-magnet tokamak that demonstrated the performance benefits of strong fields in a small machine — the very principle high-temperature superconductors now let Kronos pursue continuously at {F['b_Bpeak']}.",
       "It is intellectual heritage for the compact, high-field approach."],
      [("Type","High-field tokamak"),("Lesson","High field, compact")],
      ["high-field-magnets","compact-vs-conventional","why-now"]),
    ]
    for slug,title,desc,paras,facts,rel in D:
        page(slug,title,"devices",desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
