# -*- coding: utf-8 -*-
"""Components — the actual hardware of the two machines, component by component."""
def register(cat, page, F):
    cat("components", "Components & Hardware",
        "The machine, part by part — every major component of the breeder and burner, what it "
        "does, what it is made of, and how mature it is. Representative to the frozen design.", 4.2)
    C = [
     # magnets
     ("tf-coil","Toroidal-Field Coil","The D-shaped superconducting coils that make the breeder's main confining field.",
      [f"HYPERION's toroidal-field coils are D-shaped windings of REBCO high-temperature superconductor that produce the main confining field, reaching {F['b_Bpeak']} at the conductor. Their shape minimises bending stress, and a robust case and intercoil structure contain the enormous Lorentz forces."],
      [("Conductor","REBCO tape"),("Peak field",F["b_Bpeak"]),("Grade","DERIVED")],
      ["toroidal-field-coil","winding-pack","coil-case"]),
     ("pf-coil-set","Poloidal-Field Coil Set","Ring coils that shape the plasma and hold its position.",
      ["The poloidal-field coils are horizontal ring coils above, below and around the plasma that control its position, elongation and triangularity. They are the actuators the vertical- and shape-control systems drive in real time."],
      [("Role","Shape & position control"),("Grade","DERIVED")],
      ["poloidal-field","plasma-position-control","plasma-shaping"]),
     ("central-solenoid-component","Central Solenoid","The core magnet that induces and ramps the plasma current.",
      [f"The central solenoid runs up the machine's centre and acts as a transformer primary, inducing HYPERION's {F['b_Ip']} plasma current. Space for it is famously tight in a compact spherical tokamak, making its flux budget a key design constraint."],
      [("Role","Current induction"),("Constraint","Tight centre column")],
      ["central-solenoid","volt-seconds","centre-column-challenge"]),
     ("plug-coil","High-Field Plug Coil","The burner's end-cap magnet that plugs the mirror.",
      [f"The burner's plug coils are its highest-field magnets, reaching {F['u_Bplug']} at the ion end, creating the high-field throat and helping build the ambipolar potential that confines the central-cell plasma. Their cyclic fatigue at full field is the burner's binding magnet gate."],
      [("Peak field",F["u_Bplug"]),("Gate","Cyclic fatigue")],
      ["mirror-throat-coil","ambipolar-potential","magnet-fatigue"]),
     ("central-cell-solenoid","Central-Cell Solenoid","The long solenoid string that confines the burner's central plasma.",
      [f"The burner's central cell is a string of solenoid coils producing a uniform axial field ({F['u_Bm']} class) along the machine's length — {F['u_ref_len']}, {F['u_aeg_len']} or {F['u_mv_len']} depending on the housing. It is the simplest part of the magnet system, scaled by product."],
      [("Field","~"+F["u_Bm"]),("Length","55–1400 m by housing")],
      ["tandem-mirror","the-burner-design-point","plug-coil"]),
     ("mirror-throat-coil","Mirror-Throat Coil","The coil that forms the high-field reflection point at each end of the mirror.",
      [f"At each end of the central cell, a mirror-throat coil raises the field to {F['u_Bm']}, reflecting particles back toward the centre. Together with the plug it sets the mirror ratio and the end confinement."],
      [("Throat field",F["u_Bm"])],
      ["mirror-ratio","plug-coil","magnetic-mirror"]),
     ("hts-current-lead","HTS Current Lead","The high-current feedthrough that brings power into the cold magnets.",
      ["High-temperature-superconductor current leads carry the magnets' large currents from room-temperature power supplies into the cold mass while minimising heat leak — a specialised, long-lead component."],
      [("Role","Current feedthrough"),("Lead time","Long-lead item")],
      ["superconducting-joint","cold-mass","cryogenic-system"]),
     ("superconducting-joint","Superconducting Joint","The low-loss splice between lengths of superconducting tape.",
      ["Because superconducting tape comes in finite lengths, coils need low-resistance joints between them. Joint quality affects both efficiency and quench behaviour, and is a focus of the REBCO magnet study."],
      [("Role","Tape splice"),("Study","DOI "+F["doi_rebco"])],
      ["rebco-tape","hts-current-lead","quench-protection"]),
     ("coil-case","Coil Case & Intercoil Structure","The steel structure that contains a magnet's Lorentz forces.",
      ["Each coil sits in a high-strength steel case, and intercoil structure ties the coils together against the forces trying to splay them. This structure carries the hoop and overturning loads that the winding pack alone could not."],
      [("Role","Force containment"),("Material","High-strength steel")],
      ["hoop-stress","magnet-structure","cold-mass"]),
     ("quench-dump-resistor","Quench Dump Resistor","The resistor bank that safely absorbs a magnet's energy in a quench.",
      ["If a magnet quenches, its stored energy is switched into a dump resistor and dissipated as heat outside the coil, protecting it from a hot spot. Sizing it follows directly from the stored magnetic energy."],
      [("Role","Energy dump"),("Sized by","Stored magnetic energy")],
      ["quench-protection","stored-magnetic-energy","dump-switch"]),
     ("dump-switch","Quench Dump Switch","The fast breaker that diverts magnet current into the dump resistor.",
      ["A fast, reliable switch (breaker) opens on a quench signal to divert the coil current into the dump resistor within milliseconds. Its speed and reliability are central to magnet protection."],
      [("Role","Fast current diversion")],
      ["quench-dump-resistor","quench-detection","quench-protection"]),
     # vessel / structure
     ("vacuum-vessel-sector","Vacuum-Vessel Sector","A welded segment of the chamber that holds the plasma vacuum.",
      ["The vacuum vessel is built from sectors — forged and rolled steel segments joined by automated field welds — that together form the sealed, ported chamber holding ultra-high vacuum. Sector forgings are a long-lead procurement item."],
      [("Role","Vacuum boundary"),("Lead time","24–30 mo (forgings)")],
      ["vacuum-vessel","vessel-port","systems-integration"]),
     ("vessel-port","Vessel Port","An opening for heating, diagnostics and maintenance access.",
      ["Ports penetrate the vessel and blanket to admit heating beams, diagnostics and remote-handling tools, sealed by port plugs. Their number and size trade access against shielding and structural strength."],
      [("Role","Access penetration")],
      ["port-plug","remote-handling","vacuum-vessel"]),
     ("cryostat-component","Cryostat","The large vacuum enclosure insulating the cold magnets.",
      ["The cryostat is the outer vacuum vessel surrounding the entire cold mass, providing the insulating vacuum that keeps room-temperature heat from reaching the magnets."],
      [("Role","Insulating vacuum")],
      ["cryostat","thermal-shield-component","cold-mass"]),
     ("thermal-shield-component","Thermal Shield","Actively-cooled panels intercepting heat before it reaches the magnets.",
      ["Between cryostat and cold mass, actively-cooled thermal-shield panels intercept radiant heat, cutting the load the cryoplant must remove at the coldest temperature."],
      [("Role","Radiant-heat interception")],
      ["thermal-shield","cryogenic-system","cold-mass"]),
     ("gravity-support-component","Gravity Supports","The structure carrying the machine's weight while allowing thermal motion.",
      ["Gravity supports hold up the cold mass and vessel while flexing to accommodate the large contractions of cool-down and the loads of operation — a critical structural interface."],
      [("Role","Weight + thermal motion")],
      ["gravity-support","cold-mass","magnet-structure"]),
     # in-vessel
     ("first-wall-panel-component","First-Wall Panel","A replaceable armoured tile assembly facing the plasma.",
      [f"First-wall panels — plasma-facing armour bonded to actively-cooled heat sinks — line the vessel and take the radiation and particle load, rated for {F['b_wall']} on the breeder. They are designed for remote replacement as they wear."],
      [("Load (breeder)",F["b_wall"]),("Maintenance","Remote-replaceable")],
      ["first-wall","plasma-facing-materials","cucrzr"]),
     ("blanket-module-component","Breeding Blanket Module","A replaceable segment that breeds tritium and recovers heat.",
      [f"Each blanket module slows fusion neutrons to breed tritium from lithium (toward TBR {F['b_TBR']}) and recovers their energy as heat. Modularity enables remote maintenance and is central to plant availability."],
      [("Breeding target","TBR "+F["b_TBR"]),("Maintenance","Remote-replaceable")],
      ["blanket","breeding-material","remote-handling"]),
     ("divertor-cassette-component","Divertor Cassette","A remotely-replaceable unit carrying the divertor targets.",
      ["Divertor cassettes carry the high-heat-flux target plates that exhaust the plasma and are swapped by remote handling. Their design balances heat handling, pumping and maintainability."],
      [("Role","Exhaust target carrier")],
      ["divertor-cassette","tungsten-divertor","detachment"]),
     ("neutron-shield-block","Neutron Shield Block","Dense shielding that protects the magnets from neutron damage.",
      ["Shield blocks between the blanket and the magnets slow and absorb neutrons, protecting the superconductors' lifetime. Shielding is heaviest on the neutron-rich breeder."],
      [("Role","Magnet protection")],
      ["shielding","neutron-damage-materials","blanket"]),
     ("reflector-liner-component","Reflector Liner","The reflective central-cell liner central to the burner's power balance.",
      ["The burner's central cell is lined with a reflective material that returns radiation to the plasma, improving the power balance. Its reflectivity is a deciding parameter, traded against neutron activation."],
      [("Role","Radiation return"),("Trade","Reflectivity vs activation")],
      ["reflector-liner","synchrotron-radiation","the-burner-design-point"]),
     # fuel cycle
     ("tritium-extraction-unit","Tritium Extraction Unit","The system that recovers bred tritium from the blanket.",
      ["Tritium bred in the blanket must be extracted, purified and returned to the fuel cycle. The extraction system, with permeation control and accountancy, is a licensing-relevant part of the breeder."],
      [("Role","Tritium recovery"),("Relevance","Licensing")],
      ["fuel-cycle","tritium-permeation","tritium-safety"]),
     ("pellet-injector-component","Pellet Injector","Fires frozen fuel pellets deep into the plasma.",
      ["A pellet injector accelerates frozen deuterium (or D–T) pellets into the core, fuelling deeper than gas can reach and controlling the density profile."],
      [("Role","Core fuelling")],
      ["fueling-pellet","density-peaking","fuel-cycle"]),
     ("cryopump-component","Cryopump","Captures exhaust gas and helium ash on cold surfaces.",
      ["Cryopumps freeze exhaust gas onto cold panels, providing the high pumping speeds needed to control density and remove helium ash. They are the primary vacuum pumps for the plasma chamber."],
      [("Role","Exhaust pumping")],
      ["cryopump","helium-ash","vacuum-system"]),
     # heating
     ("nbi-injector","Neutral-Beam Injector","Fires energetic neutral atoms to heat the plasma and drive current.",
      [f"A neutral-beam injector accelerates ions, neutralises them, and fires the resulting fast atoms into the plasma to heat it and drive current, within HYPERION's {F['b_Paux']} auxiliary budget. It is a specialised, long-lead component."],
      [("Role","Heating + current drive"),("Lead time","~24 mo")],
      ["neutral-beam-injection","heating-systems","current-drive"]),
     ("gyrotron","Gyrotron","A high-power microwave source for electron-cyclotron heating.",
      ["A gyrotron generates the high-frequency, high-power microwaves used for electron-cyclotron heating and current drive, enabling precise, localised deposition for heating and mode stabilisation. It is a specialised source with a long lead time."],
      [("Role","ECRH source"),("Lead time","~24 mo")],
      ["electron-cyclotron-heating","rf-current-drive","neoclassical-tearing-mode"]),
     ("rf-antenna","RF Antenna / Launcher","Couples radio-frequency heating power into the plasma.",
      ["RF antennas and launchers, mounted at the vessel wall, couple ion- or lower-hybrid-frequency power into the plasma. Their design must survive the plasma edge while coupling efficiently."],
      [("Role","RF coupling")],
      ["ion-cyclotron-heating","rf-current-drive","first-wall"]),
     # power / DEC
     ("dec-collector-ring","DEC Collector Ring","A biased electrode ring that recovers ion energy as electricity.",
      [f"The direct-energy converter's collector rings — an angled, biased 'venetian-blind' array — decelerate the burner's escaping ions and collect their energy as electricity at about {F['u_dec']}, the heart of the burner's direct conversion."],
      [("Role","Direct conversion"),("Efficiency",F["u_dec"])],
      ["venetian-blind-collector","direct-energy-conversion","expander-tank-component"]),
     ("expander-tank-component","Expander / End Tank","Spreads the burner's exhaust plasma for the converter.",
      ["Beyond the plug, the expander tank flares the field so exhaust plasma spreads over a large area, easing heat load and feeding the direct converter. It is where the burner recovers end-loss energy."],
      [("Role","Exhaust expansion")],
      ["expander-tank","direct-energy-conversion","dec-collector-ring"]),
     ("power-supply-converter","Power Supplies & Converters","The bespoke converters that feed magnets and heating.",
      ["Large, bespoke power converters feed the magnets, heating systems and, on the burner, the direct-conversion electronics. They are conventional but high-power, and a ~18–24-month lead item."],
      [("Role","Power conditioning"),("Lead time","18–24 mo")],
      ["balance-of-plant","dec-collector-ring","quench-protection"]),
     # cryo / BoP
     ("cold-box","Cryoplant Cold Box","The bespoke helium refrigerator that keeps the magnets cold.",
      ["The cold box is the heart of the cryoplant — a large helium refrigerator that removes the cold mass's heat loads at cryogenic temperature. It is a bespoke, ~30-month-lead system drawn from big-science practice."],
      [("Role","Helium refrigeration"),("Lead time","~30 mo")],
      ["cryogenic-system","cryoline","cold-mass"]),
     ("cryoline","Cryogenic Distribution Line","Insulated lines carrying cryogen to the magnets.",
      ["Cryolines distribute cold helium from the cold box to the coils and shields through vacuum-insulated, multi-channel transfer lines — a specialised distribution system."],
      [("Role","Cryogen distribution")],
      ["cold-box","cryogenic-system","thermal-shield-component"]),
     ("primary-coolant-pump","Primary Coolant Pump","Circulates coolant to remove fusion heat.",
      ["Primary coolant pumps circulate the fluid that removes heat from the blanket and first wall and carries it to power conversion. They are conventional but critical balance-of-plant machinery."],
      [("Role","Heat removal")],
      ["primary-coolant","heat-exchanger","balance-of-plant"]),
     ("heat-exchanger-component","Heat Exchanger","Transfers fusion heat to the power cycle while isolating loops.",
      ["Heat exchangers pass fusion heat from the primary coolant to the power-conversion cycle while keeping the loops separate — important for tritium containment on the breeder. Conventional power-plant equipment."],
      [("Role","Heat transfer")],
      ["heat-exchanger","power-conversion","primary-coolant"]),
     # I&C
     ("diagnostic-port-plug","Diagnostic Port Plug","A shielded plug carrying instruments to the plasma edge.",
      ["Diagnostic port plugs mount instruments — cameras, spectrometers, probes — at vessel penetrations while maintaining shielding and vacuum. They integrate many diagnostics into a maintainable unit."],
      [("Role","Diagnostic access")],
      ["plasma-diagnostics","port-plug","diagnostic-suite"][:2]+["vessel-port"]),
     ("sis-controller","Safety-Instrumented Controller","The independent system that enforces protective interlocks.",
      ["A safety-instrumented system, independent of normal control, enforces the interlocks that protect the machine and staff — tripping on out-of-bounds conditions to a safe state. Its integrity level is set by functional-safety standards."],
      [("Role","Protective interlocks"),("Standard","IEC 61508/61511")],
      ["instrumentation-control","real-time-control","gate-reviews"]),
     ("magnetic-pickup-coil","Magnetic Pickup Coil","A simple sensor that measures the plasma's magnetic field.",
      ["Pickup coils and flux loops around the vessel sense the plasma's magnetic field, feeding the real-time reconstruction of its current, position and shape that control depends on."],
      [("Role","Magnetic sensing")],
      ["magnetic-diagnostics","plasma-position-control","real-time-control"]),
    ]
    for slug,title,desc,paras,facts,rel in C:
        page(slug,title,"components",desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
