# -*- coding: utf-8 -*-
"""Glossary depth batch C — magnets, cryogenics, materials, neutronics, vacuum."""
def register(cat, page, F, enrich):
    G = {
     "rebco-tape": f"REBCO tape is a layered composite — a micron-thin superconducting film on a strong metal substrate, stabilised with copper — and its tolerance to strain is what makes it manufacturable into large coils. It carries current densities and fields low-temperature superconductors cannot, enabling the {F['b_Bpeak']} breeder field, and Kronos's open REBCO study maps its critical-current envelope, stress and quench behaviour against demonstrated coils.",
     "magnet-structure": "A high-field magnet is really a structure problem: the Lorentz forces try to blow the coil apart, and the winding pack alone cannot hold them, so a high-strength cryogenic case and intercoil structure carry the hoop and overturning loads. Bore-resolved stress analysis shows the static case is sound; cyclic fatigue of that structure is the binding magnet gate.",
     "plasma-facing-materials": f"Plasma-facing materials live in the harshest environment in the machine, so they are chosen for heat tolerance, low erosion and low tritium retention rather than strength. Tungsten armour on copper-alloy heat sinks is the reference pairing, rated for HYPERION's {F['b_wall']} first-wall load, and every plasma-facing component is designed to be inspected and replaced.",
     "neutron-damage-materials": f"Fusion neutrons both displace atoms (measured in dpa) and transmute them into gas and radioactive isotopes, degrading materials and setting their lifetime. The neutron-rich breeder ({F['b_fn']} neutrons) carries almost all of this load; the burner ({F['u_fn']}) far less. Low-activation steels are chosen so the damage is bounded and the resulting waste is short-lived.",
     "superconducting-magnets": f"The magnet is the machine: everything about a compact fusion device follows from how much field its coils can hold. REBCO high-temperature superconductors let Kronos reach {F['b_Bpeak']} in the breeder and {F['u_Bplug']} in the burner plug continuously, and the full package — conductor, joints, current leads, quench protection, structure — is documented openly and benchmarked against real coils.",
     "cryogenic-system": "The cryoplant is large but conventional big-science engineering: a helium refrigerator removes the residual heat that leaks into the cold magnets through supports, leads, radiation and nuclear heating. Because that heat is removed at cryogenic temperature it is expensive, which is why insulation, thermal shields and minimising nuclear heating of the magnets all matter to the plant's efficiency.",
     "vacuum-system": f"The plasma must sit in ultra-high vacuum so that stray gas cannot cool or contaminate it, and reaching a very low base pressure is a cold-commissioning milestone. Cryopumps provide the high pumping speeds needed to hold density and exhaust helium ash, and the same system handles the tritium-bearing exhaust on the breeder.",
     "fuel-cycle": f"The tritium fuel cycle is a closed loop unique to the D–T breeder: breed in the blanket, extract and purify, account for every gram, and re-inject. HYPERION runs it at breeding ratio {F['b_TBR']} to make {F['b_T']} while co-producing helium-3, and because tritium is mobile and radioactive the loop is one of the breeder's licensing-relevant systems.",
     "tandem-mirror": f"A tandem mirror confines plasma in a straight central cell capped by high-field plugs whose electrostatic potential holds the ions in. The Kronos burner runs D–&sup3;He this way, gaining a disruption-free machine that converts energy directly and scales by length ({F['u_ref_len']}/{F['u_aeg_len']}/{F['u_mv_len']}) — with the plug-density requirement (~{F['u_np']}) as its honest open item.",
     "spherical-tokamak": f"A spherical tokamak squeezes the doughnut's hole almost shut, running at low aspect ratio (A = {F['b_A']}), which naturally supports strong elongation and high beta. HYPERION uses that geometry to be a compact, high-performance neutron and tritium source at Q = {F['b_Q']}, accepting the tight, highly-loaded central column as the defining engineering trade.",
     "hyperion-breeder": f"HYPERION's job is to make fuel and neutrons, not electricity, and that reframing is what makes it a business before net-electric fusion is solved. It breeds {F['b_T']} of tritium at ratio {F['b_TBR']}, co-produces helium-3, and offers a high neutron flux for isotopes — value grounded in a compact spherical tokamak at Q = {F['b_Q']} / {F['b_Pfus']}.",
     "metrovolt": f"MetroVolt is the largest burner housing at {F['u_mv_len']}, delivering {F['u_mv_net']} net ({F['u_mv_gw']} class) from the same D–&sup3;He physics as the smaller units. It targets the scarce commodity in a renewable-heavy grid — firm, dispatchable, clean power — and its low neutron fraction lets it, in principle, site nearer to hyperscale load than a neutron-heavy plant.",
     "aegis": f"AEGIS is the {F['u_aeg_len']} burner housing at {F['u_aeg_net']} net, aimed at fixed defence installations that value resilient, independent, low-signature power above almost all else. It is explicitly a fixed-installation product, not a mobile or naval one, and its disruption-free, direct-conversion character suits a resilience-focused deployment.",
     "the-neutron-economy": f"Reframing the breeder's {F['b_Pn']} of neutron power from a shielding burden into a product line is the commercial heart of Kronos. Those neutrons breed tritium, co-produce helium-3, and can make medical and industrial isotopes — value that exists independent of grid-scale net-electric fusion, which is exactly why the breeder is built first.",
     "helium-3-supply": f"Helium-3 is genuinely scarce, which is why the breeder co-producing about {F['b_He3']}/yr turns a potential dependency into an internal supply and a strategic position. Kronos is careful to frame that strategic value as distinct from near-term revenue, which rests on the more clearly bankable tritium.",
     "carnot-efficiency-x": "",
     "quench-protection-detail": "Quench protection has two halves: detect the resistive voltage as a coil goes normal, then switch its stored energy into a dump resistor before a hot spot forms. REBCO's slow quench propagation makes fast, reliable detection the harder problem, and Kronos's adiabatic hot-spot analysis reports the magnet self-protecting within its design basis.",
     "reflector-liner": "The burner's reflective liner is a deciding component, not a detail: by returning radiation to the plasma it improves the power balance that closes the machine. Its reflectivity trades directly against neutron activation of the liner material, a tension Kronos flags explicitly rather than assuming an ideal reflector.",
     "low-activation-steel": "Low-activation ferritic-martensitic steels are engineered to omit the elements that would form long-lived radioactive isotopes, so that after irradiation they decay to hands-on levels in decades rather than millennia. They are the structural backbone of the neutron-heavy breeder and the reason fusion's waste can be bounded and short-lived.",
     "plug-density-requirement": f"The plug-density requirement is the burner's single most important honest caveat: net power depends on the end plugs reaching a density about {F['u_np']} times the central cell to build a deep enough confining potential. Kronos labels the result requirement-class and closes it with a dedicated plug demonstration, while the breeder's value stands independently of it.",
     "fusion-gain-q": f"Q measures the plasma; the plant-level engineering gain measures the business. HYPERION's plasma Q of {F['b_Q']} is comfortably net-positive, while the burner quotes a plant-level Q<sub>E</sub> of {F['u_QE']} thanks to direct conversion. Kronos reports both separately and per product housing, refusing to let a headline plasma Q stand in for grid electricity.",
     "lawson-criterion": f"Lawson's inequality is the one number that decides whether a fusion plasma can pay for itself, combining density, temperature and confinement time into the triple product. Kronos designs to it explicitly and reports where each machine sits — the breeder at {F['b_Ti']} and {F['b_tauE']}, the burner far hotter at {F['u_Ti']} because its fuel demands it.",
     "ignition-vs-driven": f"An igniting plasma sustains itself; a driven one is continuously heated and produces a steady multiple of that input. Kronos chooses driven operation on purpose — HYPERION at Q = {F['b_Q']}, the burner at Q<sub>E</sub> = {F['u_QE']} — because a driven machine is steerable by its heating and its finite gain is a complete, checkable claim rather than an over-readable 'ignition'.",
     "dt-fuel": f"D–T is the easiest fusion fuel — highest reactivity at the lowest temperature — and Kronos embraces its {F['b_fn']} neutron fraction rather than apologising for it, because those neutrons are the breeder's product. The catch is that tritium must be bred, which is the blanket's job, targeting {F['b_T']} per year.",
     "d-he3-fuel": f"D–&sup3;He is the reason the burner can convert energy directly: with 18.3 MeV released almost entirely as charged particles and a neutron fraction of only {F['u_fn']}, its energy can be recovered electrostatically instead of through a steam cycle. The price is a far hotter, harder-to-confine plasma at {F['u_Ti']}.",
     "central-solenoid": f"The central solenoid induces and ramps the plasma current like a transformer primary, and in a compact spherical tokamak there is barely room for it — part of the centre-column squeeze. Its limited flux swing (volt-seconds) is one reason HYPERION leans on non-inductive current drive and a {F['b_fbs']} bootstrap fraction to sustain steady state.",
    }
    G.pop("carnot-efficiency-x", None)
    for slug, para in G.items():
        if para: enrich(slug, add_body=[('p', para)])
