# -*- coding: utf-8 -*-
"""Glossary batch 4 — operations, profiles, divertor physics, current drive detail."""

def register(cat, page, F):
    T = [
     ("plasma-breakdown","Plasma Breakdown","The initial ionisation that turns fill gas into a conducting plasma at start-up.",
      ["Breakdown is the first step of every discharge: a loop voltage ionises the fill gas into a conducting plasma, after which the current can be ramped up. Reliable, low-voltage breakdown is a start-up design requirement."],
      ["plasma-current","tokamak-startup","first-plasma"]),
     ("tokamak-startup","Tokamak Start-Up","Ramping a tokamak from breakdown to its flat-top operating current.",
      ["Start-up takes the plasma from breakdown through current ramp-up to the steady 'flat-top' where fusion conditions are held. Managing the current and density profiles through this sequence avoids instabilities."],
      ["plasma-breakdown","flat-top","plasma-current"]),
     ("flat-top","Flat-Top Operation","The steady phase of a discharge where fusion conditions are maintained.",
      ["The flat-top is the sustained portion of a discharge at constant current where fusion power is produced. For a power plant this phase must extend indefinitely — true steady-state operation."],
      ["steady-state-operation","tokamak-startup","current-drive"]),
     ("first-plasma","First Plasma","The milestone of a new machine's first successful discharge.",
      ["First plasma is a machine's inaugural discharge — the point at which integrated commissioning has succeeded and physics operation can begin. It is a headline commissioning milestone on any build path."],
      ["the-path-to-build","plasma-breakdown","tokamak-startup"]),
     ("current-profile","Current Profile","How the plasma current is distributed across the radius; it shapes stability.",
      ["The radial distribution of plasma current sets the safety-factor profile and hence stability. Tailoring it — with current drive and heating — is a key tool for avoiding tearing modes and optimising bootstrap current."],
      ["safety-factor","current-drive","q-profile"]),
     ("q-profile","The q-Profile","The radial profile of the safety factor, central to advanced operating scenarios.",
      ["The q-profile is the safety factor plotted across the plasma radius. Its shape — monotonic, reversed, or flat — defines operating scenarios and where instabilities can appear. Reversed-shear profiles can form internal transport barriers."],
      ["safety-factor","reversed-shear","internal-transport-barrier"]),
     ("reversed-shear","Reversed Magnetic Shear","A q-profile that dips in the core, capable of forming an internal transport barrier.",
      ["When the q-profile has an off-axis minimum ('reversed shear'), turbulence can be suppressed there, forming an internal transport barrier that boosts core confinement. It is a route to advanced, high-performance scenarios."],
      ["q-profile","internal-transport-barrier","magnetic-shear"]),
     ("internal-transport-barrier","Internal Transport Barrier","A core region of quenched turbulence and steep gradients that raises performance.",
      ["An internal transport barrier is a core layer where turbulence is suppressed, allowing steep temperature and density gradients and improved confinement. Combined with a strong edge pedestal it defines advanced operating regimes."],
      ["reversed-shear","transport-barrier","pedestal"]),
     ("detachment","Divertor Detachment","Cooling the divertor plasma until it 'detaches' from the target, spreading the heat load.",
      ["In detachment, the plasma near the divertor target is cooled by radiation and neutrals until it lifts off the surface, dramatically reducing peak heat flux. It is a key technique for protecting the divertor, tied to the radiated-fraction strategy."],
      ["radiated-power-fraction","divertor","heat-flux"]),
     ("neutral-recycling","Neutral Recycling","The cycle of plasma neutralising at the wall and re-entering as gas.",
      ["Ions reaching the wall neutralise and return to the plasma as gas, 'recycling'. This flux governs edge density and fuelling and strongly affects divertor conditions."],
      ["detachment","gas-puffing","scrape-off-layer"]),
     ("wall-conditioning","Wall Conditioning","Preparing vessel surfaces to control impurities and recycling.",
      ["Techniques like baking and glow-discharge cleaning condition the vessel walls to remove adsorbed gas and control impurity influx and recycling, improving plasma purity and reproducibility."],
      ["neutral-recycling","zeff","vacuum-vessel"]),
     ("locked-mode","Locked Mode","A magnetic island that stops rotating and can trigger a disruption.",
      ["A tearing-mode island that slows and locks to the wall often precedes a disruption. Avoiding locked modes — with error-field correction and rotation — is part of disruption avoidance."],
      ["tearing-mode","error-field","disruptions"]),
     ("error-field","Error Fields","Tiny magnetic imperfections that can seed islands and locked modes.",
      ["Small deviations from perfect field symmetry — error fields from coil misalignments — can seed magnetic islands and locked modes. Correction coils cancel them, a standard part of tokamak operation."],
      ["locked-mode","resonant-magnetic-perturbation","tearing-mode"]),
     ("resonant-magnetic-perturbation","Resonant Magnetic Perturbations","Deliberately applied 3D fields used to control ELMs.",
      ["Applying small, resonant 3D magnetic perturbations can suppress or pace edge-localised modes, protecting the divertor. It is one of several ELM-control tools, complementary to shaping choices like negative triangularity."],
      ["edge-localized-modes","error-field","negative-triangularity"]),
     ("fishbone-instability","Fishbone Instability","A fast-ion-driven mode that can expel energetic particles.",
      ["Fishbones are bursts driven by resonance between energetic ions and an internal mode, capable of ejecting fast ions. Like Alfvén eigenmodes, they are part of fast-ion management."],
      ["fast-ions","alfven-eigenmodes","sawtooth-oscillation"]),
     ("plasma-rotation","Plasma Rotation","Bulk flow of the plasma that stabilises certain instabilities.",
      ["Plasmas can rotate toroidally, driven by injected beams or intrinsic effects. Rotation and its shear stabilise resistive-wall modes and suppress turbulence, making it a useful performance lever."],
      ["resistive-wall-mode","turbulent-transport","neutral-beam-injection"]),
     ("density-peaking","Density Peaking","A centrally-peaked density profile that raises fusion power.",
      ["A density profile peaked in the core concentrates fuel where it is hottest, boosting fusion power for the same average density. Controlling peaking through fuelling and transport is a performance tool."],
      ["plasma-density","fueling-pellet","current-profile"]),
     ("beam-driven-current","Beam-Driven Current","Current driven by injecting energetic neutral beams.",
      [f"Neutral beams deposit not only heat but momentum, driving a component of the plasma current. Along with RF methods and the bootstrap current, it helps sustain HYPERION's {F['b_Ip']} in steady state."],
      ["neutral-beam-injection","current-drive","bootstrap-current"]),
     ("rf-current-drive","RF Current Drive","Driving plasma current with radio-frequency and microwave waves.",
      ["Waves — lower-hybrid, electron-cyclotron — can push current in the plasma efficiently and with spatial precision, useful both for sustaining current and for stabilising tearing modes by driving local current."],
      ["current-drive","electron-cyclotron-heating","neoclassical-tearing-mode"]),
     ("pumping-speed","Vacuum Pumping Speed","How fast the vacuum system removes gas and helium ash.",
      ["Pumping speed sets how quickly exhaust gas and helium ash are removed, controlling density and purity. Cryopumps provide the high speeds fusion vessels need."],
      ["vacuum-system","helium-ash","cryopump"]),
     ("cryopump","Cryopump","A pump that captures gas by freezing it on cold surfaces.",
      ["A cryopump condenses or adsorbs gas on very cold surfaces, achieving the high pumping speeds and ultra-high vacuum a plasma needs. It is the workhorse of fusion vacuum systems."],
      ["pumping-speed","vacuum-system","cryogenic-system"]),
     ("burning-plasma","Burning Plasma","A plasma where fusion self-heating is significant — a scientific milestone.",
      ["A burning plasma is one where fusion self-heating (alpha heating in D–T) contributes significantly to sustaining the temperature. It is a scientific milestone distinct from ignition; Kronos's driven designs quote finite gain rather than relying on dominant self-heating."],
      ["alpha-heating","ignition-vs-driven","fusion-gain-q"]),
     ("isotope-effect","The Isotope Effect","The empirical improvement in confinement with heavier hydrogen isotopes.",
      ["Confinement tends to improve with heavier hydrogen isotopes — deuterium over hydrogen, and D–T over pure deuterium. This favourable 'isotope effect' is part of why D–T operation performs well."],
      ["confinement-scaling","dt-fuel","energy-confinement-time"]),
     ("plasma-facing-component","Plasma-Facing Components","The armoured surfaces that directly face the plasma.",
      [f"Plasma-facing components — first-wall panels and divertor targets — armour the vessel against heat, particles and radiation. Their heat-flux and neutron tolerance set maintenance intervals. HYPERION's first wall is rated for {F['b_wall']}."],
      ["first-wall","divertor","plasma-facing-materials"]),
     ("radiative-divertor","Radiative Divertor","A divertor operated to radiate most of its heat before it reaches the targets.",
      ["A radiative divertor seeds impurities to radiate the exhaust power volumetrically, spreading it over the whole surface. It is the operating strategy behind Kronos's high-radiated-fraction divertor design."],
      ["radiated-power-fraction","detachment","impurity-seeding"]),
    ]
    def make(slug, term, oneliner, paras, rel):
        page(slug, term, "glossary", oneliner, oneliner, [('p', p) for p in paras],
             related=rel, jtype="DefinedTerm", kicker="Glossary")
    for row in T:
        make(row[0], row[1], row[2], row[3], row[4])
