# -*- coding: utf-8 -*-
"""Supplement — real pages that fill out the cross-link graph."""

def register(cat, page, F):
    # reuse existing categories; no new cat() needed
    S = [
     ("plasma-current","Plasma Current","glossary","The toroidal current a tokamak drives through its plasma; it confines and shapes the plasma.",
      [f"The plasma current is the electric current driven around the torus; its poloidal magnetic field is essential to confinement and shaping. HYPERION runs {F['b_Ip']} of plasma current, split between a self-generated bootstrap fraction ({F['b_fbs']}) and externally driven current.",
       "The current is limited from above by stability (via the safety factor and Greenwald density) and costs auxiliary power to sustain — both captured in the design point."],
      [("Breeder current",F["b_Ip"]),("Bootstrap fraction",F["b_fbs"])],
      ["bootstrap-current","current-drive","safety-factor"]),
     ("plasma-density","Plasma Density","glossary","How many fuel nuclei occupy each cubic metre; fusion power scales with its square.",
      [f"Density sets the reaction rate — fusion power scales roughly with density squared. Tokamaks face the Greenwald density limit; mirrors do not. The burner operates at a design density of {F['u_ne']}.",
       "Density is one leg of the Lawson triple product and is traded against temperature and confinement time in the design."],
      [("Burner density",F["u_ne"])],
      ["greenwald-density","lawson-criterion","plasma-current"]),
     ("plasma-shaping","Plasma Shaping","glossary","Elongation and triangularity together define the plasma's cross-section and its stability.",
      [f"Shaping — the combination of elongation (&kappa; = {F['b_kappa']}) and triangularity (&delta; = {F['b_delta']}) — controls how much current and pressure a plasma holds and how stable it is. HYPERION's tall, negative-triangularity cross-section is a deliberate stability-and-performance choice.",
       "Good shaping is one of the spherical tokamak's natural advantages."],
      [("Elongation",F["b_kappa"]),("Triangularity",F["b_delta"])],
      ["elongation","triangularity","spherical-tokamak"]),
     ("beta-limit","The Beta Limit","glossary","The maximum plasma pressure a magnetic configuration can stably hold.",
      [f"Beta limits cap how much plasma pressure a given field can confine before instabilities grow. Operating below them bounds the achievable power density. HYPERION runs at &beta;<sub>N</sub> = {F['b_bN']}, within the no-wall limits observed on spherical tokamaks.",
       "Its low aspect ratio is what lets it hold high beta while staying within these limits."],
      [("Breeder beta-N",F["b_bN"])],
      ["plasma-beta","mhd-stability","aspect-ratio"]),
     ("confinement-scaling","Confinement Scaling Laws","glossary","Empirical formulas (like IPB98) that predict energy confinement time from machine parameters.",
      [f"Because turbulent transport resists first-principles prediction, the field uses empirical scaling laws — most famously the ITER IPB98 scaling — fit to a large multi-machine database, to predict energy confinement time. The multiplier H<sub>98</sub> expresses performance relative to that baseline.",
       f"HYPERION assumes H<sub>98</sub> = {F['b_H98']} — standard scaling, not an optimistic multiple — giving &tau;<sub>E</sub> = {F['b_tauE']}."],
      [("Assumption","H98 = "+F["b_H98"]),("Confinement time",F["b_tauE"])],
      ["energy-confinement-time","h-mode","turbulent-transport"]),
     ("bootstrap-fraction","Bootstrap Fraction","glossary","The share of plasma current the plasma generates itself, reducing external drive.",
      [f"The bootstrap fraction is the portion of the plasma current driven by the plasma's own pressure gradient rather than external systems. A higher fraction cuts the auxiliary power the machine needs. HYPERION's bootstrap fraction is {F['b_fbs']} of its {F['b_Ip']}.",
       "Raising it is a standard efficiency lever, bounded by stability."],
      [("Bootstrap fraction",F["b_fbs"])],
      ["bootstrap-current","current-drive","plasma-current"]),
     ("magnetic-mirror","The Magnetic Mirror","glossary","A linear trap that reflects charged particles between regions of strong field.",
      [f"A magnetic mirror confines plasma in a straight field that is stronger at its ends than its middle; particles are reflected back toward the centre. Simple mirrors leak from the ends, which the <a href='./tandem-mirror.html'>tandem mirror</a> fixes with electrostatic plugs.",
       f"The Kronos burner is a tandem mirror with high-field plugs reaching {F['u_Bplug']}."],
      [("Type","Linear confinement"),("Burner plug field",F["u_Bplug"])],
      ["tandem-mirror","mirror-ratio","ambipolar-potential"]),
     ("high-field-magnets","High-Field Magnets","materials","Why higher magnetic field is the single biggest lever for a compact fusion machine.",
      [f"For a given performance, machine size and cost fall steeply as magnetic field rises — field is the master lever of compact fusion. High-temperature superconductors let Kronos reach {F['b_Bpeak']} in the breeder and {F['u_Bplug']} in the burner plug, fields that enable a small, economical core.",
       "The trade is mechanical: higher field means larger forces and tighter fatigue margins — the magnet's binding gate."],
      [("Breeder peak field",F["b_Bpeak"]),("Burner plug field",F["u_Bplug"])],
      ["superconducting-magnets","rebco-tape","magnet-structure"]),
     ("compact-vs-conventional","Compact vs Conventional Fusion","engineering","Why Kronos pursues small, high-field machines rather than very large ones.",
      [f"Conventional tokamak designs reach performance through sheer size. The compact, high-field approach reaches it through field strength instead — a smaller, faster-to-build, potentially cheaper machine. HYPERION is a compact spherical tokamak (R&#8320; = {F['b_R0']}, A = {F['b_A']}).",
       "The compact path trades a tighter, more highly-loaded core for size and cost — a trade Kronos takes deliberately."],
      [("Breeder major radius",F["b_R0"]),("Aspect ratio",F["b_A"])],
      ["spherical-tokamak","high-field-magnets","the-breeder-design-point"]),
     ("heat-flux","Heat-Flux Handling","engineering","Managing the intense heat loads on plasma-facing components.",
      [f"The divertor and first wall must survive concentrated heat loads without failing. HYPERION's first wall is rated for {F['b_wall']}, and its divertor relies on a high radiated fraction to spread the load — a named performance gate.",
       "The burner's linear geometry and low neutron fraction give it far gentler heat-handling requirements."],
      [("First-wall load",F["b_wall"])],
      ["divertor","first-wall","plasma-facing-materials"]),
     ("the-operating-window","The Operating Window","methodology","The range of conditions over which a machine actually closes — reported, not just the peak.",
      [f"Rather than a single hero point, Kronos reports the operating window: the region of parameter space where the machine genuinely closes on power balance and stability. The breeder scan spans 25,000+ configurations; the burner scans show closure crossing a specific fuel-fraction boundary.",
       "Publishing the window — including where the machine does not close — is a deliberate honesty choice."],
      [("Breeder scan","25,000+ configs")],
      ["design-space-exploration","uncertainty-quantification","design-methodology"]),
     ("the-path-to-build","The Path to Build","methodology","What must be closed — gates, analysis, qualification, prototype — before Kronos cuts metal.",
      [f"The ordered path from today's frozen design to hardware: close the binding gates (plug density, magnet fatigue, breeder confinement and divertor), run high-fidelity analysis, promote representative drawings to fabrication-grade with material qualification, demonstrate components, then license and build. Kronos maps this distance rather than claiming it is already covered.",
       "Kronos's schedule begins construction of the HYPERION breeder in Q2 2027, with detailed design and qualification proceeding in parallel; the burner follows once its gates close. The path is stated plainly rather than glossed."],
      [("Breeder construction","Scheduled to begin Q2 2027"),("Status","Design-to-build transition")],
      ["gate-reviews","plug-density-requirement","intellectual-property"]),
     ("the-3d-model","The Interactive 3D Model","methodology","The public, physics-grounded interactive model of both machines — a design instrument, honestly labelled.",
      [f"Kronos publishes an interactive 3D model of both machines: a rotatable reactor, an in-browser physics solver, and the full frozen design point (breeder Q = {F['b_Q']}, burner Q<sub>E</sub> = {F['u_QE']}). It is a schematic design instrument grounded in the frozen canon — not a mirror of operating hardware.",
       "It sits at stage one of the model &rarr; shadow &rarr; digital-twin progression, and says so."],
      [("Breeder Q",F["b_Q"]),("Burner Q_E",F["u_QE"])],
      ["model-shadow-twin","reproducibility-overview","the-breeder-design-point"]),
     ("can-fusion-power-a-data-center","Can Fusion Power a Data Centre?","products","Why the low-neutron burner is a natural fit for hyperscale, point-of-use power.",
      [f"Data centres need large, firm, clean power close to load. The MetroVolt burner housing ({F['u_mv_len']}, {F['u_mv_net']} net, {F['u_mv_gw']} class) targets exactly this: low-neutron D–&sup3;He fusion with direct conversion that can, in principle, site nearer to demand than a neutron-heavy plant.",
       "As with all Kronos figures, this is a computed design target with its gates stated openly."],
      [("Housing",F["u_mv_len"]),("Net power",F["u_mv_net"])],
      ["metrovolt","tandem-mirror","the-burner-design-point"]),
    ]
    for slug,title,catkey,desc,paras,facts,rel in S:
        page(slug,title,catkey,desc,desc,[('p',p) for p in paras],facts=facts,related=rel,
             jtype="DefinedTerm" if catkey=="glossary" else "TechArticle")
