# -*- coding: utf-8 -*-
"""Honest comparisons — fusion vs other sources, and Kronos vs other fusion approaches."""

def register(cat, page, F):
    cat("comparisons", "Comparisons & Context",
        "How fusion compares with other energy sources, and how the Kronos approach compares "
        "with other fusion paths — argued honestly, on the merits.", 12)

    P = [
     ("fusion-vs-fission","Fusion vs Fission","Both split the atom's binding energy, but fusion has no chain reaction, no meltdown, no long-lived waste and no bomb material.",
      "Fusion and fission are often lumped together as 'nuclear'. On the things that matter, they could hardly be more different.",
      [('facts',[("Reaction","Fusion: merge light nuclei · Fission: split heavy nuclei"),
                 ("Chain reaction","Fusion: none · Fission: yes"),
                 ("Meltdown","Fusion: impossible · Fission: possible"),
                 ("Long-lived waste","Fusion: none · Fission: actinides"),
                 ("Bomb material","Fusion: none · Fission: plutonium pathway")]),
       ('p',"Fusion merges light nuclei and stops the instant conditions falter; fission sustains a chain reaction in heavy nuclei and must be actively held back. That single difference cascades into fusion's safety, waste and proliferation advantages."),
       ('gap',("What fission still wins on today","Fission is a mature, deployed technology producing power now; fusion is not yet built. Kronos states this plainly."))],
      None,
      ["inherent-safety","fusion-waste","no-proliferation"]),
     ("fusion-vs-solar-wind","Fusion vs Solar and Wind","Complementary, not rival: fusion offers firm, compact, always-available power where renewables are intermittent and land-intensive.",
      "The honest framing is complementarity. Fusion does what intermittent renewables structurally cannot.",
      [('p',"Solar and wind are cheap and clean but intermittent and land-intensive, needing storage or firm backup. Fusion offers firm, compact, weather-independent baseload from a small footprint. The two are complements in a decarbonised grid, not enemies."),
       ('gap',("The honest caveat","Renewables are deployed and inexpensive today; fusion must still be built and must prove its cost. Kronos does not claim otherwise."))],
      [("Renewables","Cheap, clean, intermittent"),("Fusion","Firm, compact, not yet built")],
      ["baseload-power","dispatchable-power","land-use"]),
     ("fusion-vs-gas","Fusion vs Natural Gas","Fusion targets the firm, dispatchable role gas plays today — without the fuel-price exposure or the carbon.",
      "Gas provides firm, flexible power — and carbon and fuel-price risk. Fusion aims at the same role without either.",
      [('p',"Gas plants are firm and flexible but emit CO&sub2; and ride fuel-price volatility. A driven fusion machine is steerable like gas, emits no operational carbon, and runs on effectively inexhaustible fuel — the value proposition Kronos aims at for firm generation."),
       ('gap',("Cost is the open question","Gas is cheap and proven; fusion's competitiveness rests on capital cost and availability, which Kronos flags as its central commercial studies."))],
      [("Gas","Firm, flexible, emitting"),("Fusion","Firm, clean, fuel-secure")],
      ["dispatchable-power","fusion-carbon-footprint","capacity-factor"]),
     ("kronos-vs-dt-tokamak","Kronos vs the Mainstream D–T Tokamak","Most fusion pursues a single large D–T tokamak for electricity; Kronos splits the job into a breeder and a low-neutron burner.",
      "The mainstream bet is one big D–T tokamak that makes electricity. Kronos makes a different bet.",
      [('p',f"A conventional D–T tokamak puts ~80% of its energy into 14 MeV neutrons and must convert heat through a steam cycle. Kronos instead uses a compact D–T breeder to <i>make fuel and neutrons</i>, and a low-neutron D–&sup3;He burner ({F['u_fn']} neutrons) to make electricity by direct conversion."),
       ('p',"The payoff is a saleable product (isotopes, tritium) before net electricity is proven, and a cleaner, disruption-free electricity machine. The cost is running two machines and a harder burner fuel."),
       ('gap',("Both share hard physics","The breeder still faces tokamak confinement questions; the burner faces its plug-density requirement. Kronos does not claim to have escaped hard physics — only to have arranged it more favourably."))],
      [("Mainstream","One D–T tokamak &rarr; electricity"),("Kronos","Breeder + low-neutron burner")],
      ["the-breeder-first-strategy","kronos-vs-iter","tandem-mirror-vs-tokamak"]),
     ("tandem-mirror-vs-tokamak","Tandem Mirror vs Tokamak","The burner's linear geometry avoids disruptions and enables direct conversion, at the cost of end-plugging.",
      "Why burn D–&sup3;He in a straight machine instead of a doughnut? Because linearity buys real advantages.",
      [('facts',[("Geometry","Mirror: linear · Tokamak: toroidal"),
                 ("Disruptions","Mirror: none · Tokamak: a design driver"),
                 ("Energy conversion","Mirror: direct · Tokamak: thermal"),
                 ("Key challenge","Mirror: end plugging · Tokamak: confinement & disruptions")]),
       ('p',"A tandem mirror is open-ended, so it cannot disrupt and its exhaust flows naturally into a direct converter. The price is that the ends must be plugged — the burner's plug-density requirement. Kronos judges that trade worthwhile for a low-neutron electricity machine."),
       ('gap',("The plug is the catch",f"The mirror's advantages hinge on reaching the plug-density requirement (n_p/n_c &asymp; {F['u_np']}) — stated openly as the burner's binding gate."))],
      None,
      ["tandem-mirror","plug-density-requirement","kronos-vs-dt-tokamak"]),
     ("kronos-vs-iter","Kronos in Context: ITER and the Big-Science Path","ITER proves the physics at scale; Kronos pursues a compact, high-field, commercially-staged alternative.",
      "ITER and Kronos are not competitors so much as different theories of how fusion arrives.",
      [('p',"ITER is a large international experiment establishing burning-plasma physics at scale — invaluable, but big and slow. The compact, high-field approach Kronos takes bets that strong superconductors let a much smaller machine reach useful performance sooner, with a commercial product staged in front of net electricity."),
       ('gap',("Standing on the database","Kronos's confinement assumptions are anchored to the same multi-machine database ITER helped build; it benefits from that science rather than dismissing it."))],
      [("ITER","Large, proves physics at scale"),("Kronos","Compact, high-field, commercially staged")],
      ["compact-vs-conventional","confinement-scaling","kronos-vs-dt-tokamak"]),
     ("why-now","Why Fusion, Why Now","High-temperature superconductors, modern computation and open validation have changed what a small team can credibly design.",
      "Fusion has been 'thirty years away' for decades. Several things genuinely changed at once.",
      [('p',"Three shifts make the compact approach credible now: high-temperature superconductors that reach fields impossible a decade ago; cheap, powerful computation for design-space exploration and uncertainty quantification; and an open-science culture that lets a design be validated by anyone. Kronos is built on all three."),
       ('gap',("Still unbuilt","'Why now' explains why the design is credible, not that the machine exists. Kronos keeps that distinction."))],
      [("Enablers","HTS magnets · computation · open validation")],
      ["high-field-magnets","design-space-exploration","reproducibility-overview"]),
    ]
    for slug,title,desc,lede,body,facts,rel in P:
        page(slug,title,"comparisons",desc,lede,body,facts=facts,related=rel,jtype="TechArticle")
