# -*- coding: utf-8 -*-
"""Final depth batch — engineering, physics, methodology, products, safety, history."""
def register(cat, page, F):
    def art(slug,title,catk,desc,paras,facts=None,rel=None):
        page(slug,title,catk,desc,desc,[('p',p) for p in paras],facts=facts,related=rel or [],jtype="TechArticle")
    A = [
     ("the-central-cell","The Burner's Central Cell","engineering","The long, uniform-field section where most of the burner's fusion happens.",
      [f"The central cell is the burner's long, uniform-field core where the bulk of D–&sup3;He fusion occurs, running {F['u_ref_len']} to {F['u_mv_len']} depending on the product. It is the simplest, most repeatable part of the machine — the reason the burner scales by length.",
       "Plugs and expanders cap it at each end."],
      [("Field","~"+F["u_Bm"]),("Length","55–1400 m")],
      ["central-cell-solenoid","tandem-mirror","innovation-modular-housings"]),
     ("the-end-cell","The Burner's End Cell","engineering","The plug-and-expander assembly that confines the plasma and recovers its energy.",
      [f"Each end of the burner holds a high-field plug ({F['u_Bplug']}), the ambipolar potential it builds, and an expander feeding the direct converter. The end cell is where the burner's hardest physics — plugging — and its cleverest engineering — direct conversion — live.",
       "It is the technical heart of the tandem mirror."],
      [("Plug field",F["u_Bplug"]),("Recovers","End-loss energy")],
      ["plug-coil","ambipolar-potential","expander-tank-component"]),
     ("charged-particle-heating","Charged-Particle Self-Heating","physics","How fusion's charged products help keep the plasma hot.",
      ["The charged products of fusion — helium in D–T, protons and helium in D–&sup3;He — stay confined and deposit their energy back into the plasma, providing self-heating. In a driven machine this supplements, rather than replaces, external heating.",
       "It is why keeping fast ions confined matters for the energy balance."],
      [("Effect","Internal heating")],
      ["alpha-heating","fast-ions","power-balance"]),
     ("plasma-wall-interaction","Plasma–Wall Interaction","physics","The complex physics where the plasma edge meets solid surfaces.",
      ["Plasma–wall interaction covers everything that happens where plasma meets material: heat and particle deposition, sputtering, recycling, redeposition and fuel retention. It links plasma physics to material lifetime and is one of fusion's toughest coupled problems.",
       "The burner's linear, low-neutron design gives it a gentler version of this problem."],
      [("Scope","Edge meets material")],
      ["sputtering","neutral-recycling","plasma-facing-materials"]),
     ("the-loss-cone","The Loss Cone","physics","The range of velocities through which a mirror leaks — and why plugs are needed.",
      ["In a magnetic mirror, particles whose velocity is too aligned with the field are not reflected and escape through the 'loss cone'. Refilling and plugging the loss cone is the central mirror challenge, which the tandem-mirror ambipolar plug addresses.",
       "It is the physics behind the burner's plug-density requirement."],
      [("Meaning","Escaping velocity range")],
      ["mirror-confinement-physics","ambipolar-potential","plug-density-requirement"]),
     ("verification-and-validation","Verification & Validation","methodology","Checking the code is right, and checking it matches reality.",
      ["Verification asks whether the models are solved correctly; validation asks whether they match experiment. Kronos does both — reproducible engines for verification, benchmarking against the multi-machine database for validation — and reports each honestly.",
       "The distinction matters: a reproducible number is not automatically a validated one."],
      [("V&V","Solved right + matches reality")],
      ["reproducibility-overview","benchmarking","what-reproducibility-proves"]),
     ("the-provenance-record","The Provenance Record","methodology","Tracing every number back to its source, openly.",
      ["Kronos keeps a provenance record so every published figure traces to the engine, input and deposit that produced it. Combined with the frozen design point, it makes the whole public record auditable rather than assertion.",
       "Provenance is what lets a reviewer follow any claim to its root."],
      [("Goal","Every number traceable")],
      ["reproducibility-overview","the-freeze-discipline","digital-thread"]),
     ("the-product-family","The Kronos Product Family","products","One physics platform, several products — from neutrons to grid power.",
      [f"Kronos's products span the breeder's neutron economy (tritium, isotopes, helium-3) and the burner's electricity in two housings (AEGIS, MetroVolt). It is a family built on one physics platform, staged so materials revenue precedes grid power.",
       "The platform, not a single product, is the asset."],
      [("Platform","Breeder + burner")],
      ["hyperion-breeder","metrovolt","aegis"]),
     ("staged-commercialization","Staged Commercialisation","products","Bringing value to market in stages rather than waiting for the hardest milestone.",
      ["Kronos stages its commercialisation: first the breeder's neutron and isotope products, then demonstration of the burner, then AEGIS and MetroVolt electricity. Each stage delivers value and de-risks the next, rather than betting everything on net electricity.",
       "It is the commercial expression of the breeder-first strategy."],
      [("Approach","Value in stages")],
      ["the-breeder-first-strategy","deployment-roadmap","neutron-source-product"]),
     ("fusion-for-industry","Fusion for Industry","applications","Firm, clean heat and power to decarbonise heavy industry.",
      ["Heavy industry needs firm, high-grade heat and reliable power that renewables struggle to supply. A fusion plant's steady output can serve industrial heat, hydrogen and electricity together, extending its value beyond the power market.",
       "It targets exactly the hard-to-decarbonise demand."],
      [("Serves","Industrial heat + power")],
      ["industrial-heat-hydrogen","deep-decarbonization","firm-clean-power-product"]),
     ("the-safety-case","The Fusion Safety Case","safety","Why the evidence says a fusion plant is safe by nature.",
      ["The safety case rests on physics: no chain reaction, seconds of fuel, small mobilisable inventory, and small decay heat — so worst-case events stay local and mild, ideally needing no evacuation. Tritium and activation are handled by conventional, layered engineering.",
       "Kronos builds this case on established analyses, not assertion."],
      [("Basis","Inherent physics")],
      ["inherent-safety","accident-analysis","no-evacuation"]),
     ("the-environmental-case","The Fusion Environmental Case","safety","Zero-carbon operation, no long-lived waste — assessed on the full lifecycle.",
      ["Fusion emits no operational carbon, needs no mined fuel at scale, and leaves no long-lived waste. The honest lifecycle view adds embodied carbon in construction and short-lived activated material at end of life — items Kronos includes in its environmental screening rather than skipping.",
       "It is a strong case, argued on the whole lifecycle."],
      [("Operation","Zero-carbon, low waste")],
      ["lifecycle-assessment","fusion-carbon-footprint","decommissioning"]),
     ("spherical-tokamak-history","The Spherical-Tokamak Story","history","How the low-aspect-ratio idea grew into a serious reactor line.",
      ["The spherical tokamak emerged from the insight that squeezing the torus to low aspect ratio yields high beta and strong shaping. Experiments established its physics, and high-temperature superconductors now make a compact ST reactor credible — the lineage of the Kronos breeder.",
       "It is a maturing line with a clear reactor rationale."],
      [("Line","Low-A, high-beta")],
      ["spherical-tokamak","device-nstx","history-of-fusion"]),
     ("direct-conversion-history","The Direct-Conversion Story","history","How turning ions straight into electricity moved from concept to the burner.",
      ["Direct energy conversion was explored decades ago for mirror machines, demonstrating that charged-particle energy can be recovered as electricity efficiently. Paired with low-neutron D–&sup3;He and modern engineering, it becomes the burner's defining feature.",
       "The Kronos burner realises this long-standing idea."],
      [("Idea","Ions &rarr; electricity directly")],
      ["direct-energy-conversion","history-of-mirrors","the-dec-record"]),
     ("the-magnet-materials-suite","The Magnet Materials Suite","materials","Every material that goes into a Kronos magnet, and why.",
      [f"A Kronos magnet combines REBCO superconductor, copper stabiliser, a Hastelloy-class substrate, high-strength structural alloys, and radiation-tolerant insulation — each chosen for its role in reaching {F['b_Bpeak']} safely. The suite is documented in the open REBCO study.",
       "Cyclic fatigue of the structure is the binding gate."],
      [("Core","REBCO + structure + insulation")],
      ["rebco-tape","magnet-structure","radiation-hard-insulation"]),
     ("the-structural-materials-suite","The Structural Materials Suite","materials","The alloys that hold the machine together under load and neutrons.",
      ["Structural materials span cryogenic-tough magnet-case alloys and low-activation steels (RAFM, ODS) for the neutron-heavy breeder. Each is chosen for strength, toughness and — for the breeder — short-lived activation, and qualified against its service environment.",
       "Material selection is inseparable from the neutron and safety cases."],
      [("Span","Magnet + blanket structure")],
      ["low-activation-steel","eurofer-steel","materials-qualification"]),
     ("the-plasma-facing-suite","The Plasma-Facing Materials Suite","materials","The armour and heat sinks that survive facing the plasma.",
      [f"Plasma-facing components pair refractory armour (tungsten) with copper-alloy heat sinks (CuCrZr), bonded by processes like HIP, rated for {F['b_wall']} on the breeder. On the burner, a reflective liner is the deciding plasma-facing choice.",
       "These surfaces are designed for inspection and replacement."],
      [("Pair","Tungsten + CuCrZr")],
      ["plasma-facing-materials","tungsten-armor","reflector-liner"]),
    ]
    for slug,title,catk,desc,paras,facts,rel in A:
        art(slug,title,catk,desc,paras,facts,rel)
