# -*- coding: utf-8 -*-
"""Glossary batch 22 — instabilities, tritium accountancy, control systems, scalings."""
def register(cat, page, F):
    T = [
     ("micro-instability","Micro-Instabilities","Small-scale instabilities that drive turbulent transport.","Micro-instabilities are short-wavelength modes (ITG, TEM, ETG) that grow into the turbulence limiting confinement. They are the target of turbulence-suppression physics like sheared flow.",["itg-mode","drift-wave","turbulent-transport"]),
     ("tem-mode","Trapped-Electron Mode","A micro-instability driven by trapped electrons.","The trapped-electron mode is a drift-wave instability driven by trapped electrons and density gradients, contributing to electron heat and particle transport. It is one of the main turbulence channels.",["micro-instability","trapped-particles","turbulent-transport"]),
     ("etg-mode","Electron-Temperature-Gradient Mode","A fine-scale instability driving electron heat loss.","The electron-temperature-gradient mode operates at very small scales and drives electron heat transport. It is part of the multi-scale turbulence picture that sets confinement.",["micro-instability","itg-mode","turbulent-transport"]),
     ("gyro-bohm-scaling","Gyro-Bohm Scaling","A turbulence scaling in which bigger machines confine relatively better.","Gyro-Bohm scaling predicts transport falling as the ratio of gyroradius to machine size shrinks, so larger (or higher-field) machines confine relatively better. It informs how confinement scales with size and field.",["turbulent-transport","confinement-scaling","larmor-radius"]),
     ("bohm-diffusion","Bohm Diffusion","A pessimistic transport estimate that good confinement beats.","Bohm diffusion is an old, pessimistic transport estimate; modern confined plasmas do much better, which is why empirical scaling — not Bohm — is used for design. It is a historical benchmark.",["turbulent-transport","gyro-bohm-scaling","confinement-scaling"]),
     ("tritium-accountancy","Tritium Accountancy","Tracking every gram of tritium for safety and regulation.","Tritium accountancy tracks the location and amount of all tritium — in fuel, blanket, storage and processing — for safety, efficiency and regulatory compliance. It is a continuous operational and licensing requirement.",["tritium-plant","material-balance","tritium-safety"]),
     ("material-balance","Tritium Material Balance","Closing the books on tritium produced, burned and stored.","A material balance reconciles tritium bred, burned, stored and lost, ensuring none is unaccounted for. Closing it continuously is central to both safety and demonstrating self-sufficiency.",["tritium-accountancy","tritium-breeding","tritium-self-sufficiency"]),
     ("tritium-monitoring","Tritium Monitoring","Continuously measuring tritium in air, water and effluent.","Tritium monitors — ionisation chambers and samplers — continuously measure tritium in work areas, effluent and the stack, protecting workers and the public and feeding accountancy. It is a pervasive safety system.",["stack-monitoring","tritium-safety","secondary-containment"]),
     ("data-acquisition","Data Acquisition Systems","Capturing the flood of diagnostic data a machine produces.","Data-acquisition systems capture, timestamp and store the high-rate signals from dozens of diagnostics, feeding both real-time control and offline analysis. They are the nervous system's recording layer.",["plasma-diagnostics-suite","real-time-network","plasma-state-estimation"]),
     ("real-time-network","Real-Time Control Network","The low-latency network that carries control signals.","A deterministic, low-latency network links diagnostics to controllers to actuators fast enough to steer the plasma and trip on faults. Its speed bounds what real-time control can achieve.",["real-time-control","data-acquisition","actuator"]),
     ("plasma-control-modeling","Control-Oriented Modelling","Fast plasma models built specifically for control.","Control needs models fast enough to run in real time — reduced representations of the plasma's response used for prediction and feedback. Kronos's reduced-order engines inform this control-oriented modelling.",["model-predictive-control","reduced-order-modeling","real-time-control"]),
     ("sub-divertor","Sub-Divertor Plenum","The pumped volume beneath the divertor that controls neutrals.","The sub-divertor plenum is the enclosed, pumped space beneath the divertor targets where neutrals are collected and removed, governing recycling and detachment. Its design links exhaust physics to pumping.",["divertor-pumping","neutral-recycling","cryopump"]),
     ("plasma-shape-reconstruction","Equilibrium Reconstruction","Computing the plasma's shape and current from magnetic data in real time.","Equilibrium reconstruction solves for the plasma's flux surfaces, position and current from magnetic measurements, continuously, so control can act on an accurate picture. It is fundamental to shape and position control.",["magnetic-diagnostics","plasma-equilibrium","plasma-position-control"]),
     ("resistive-ballooning","Resistive Ballooning Modes","Pressure-driven edge modes including resistivity.","Resistive ballooning modes are pressure-driven instabilities in the resistive plasma edge, contributing to edge transport and the pedestal limit. They are part of the edge-stability picture.",["ballooning-modes","peeling-ballooning","resistive-mhd"]),
     ("quasi-coherent-mode","Edge Coherent Modes","Benign edge fluctuations that exhaust energy without large ELMs.","Certain quasi- or weakly-coherent edge modes continuously exhaust pedestal energy in small amounts, avoiding large ELMs. They appear in ELM-free regimes attractive for divertor protection.",["qh-mode","i-mode","edge-localized-modes"]),
     ("kapton-alternatives","Magnet Insulation Materials","The organic and inorganic insulators that electrically isolate windings.","Magnet windings are electrically insulated with radiation-tolerant organics (cyanate esters) or inorganic systems, chosen to survive dose and cryogenic cycling. Insulation choice ties to the magnet's radiation limit.",["radiation-hard-insulation","insulation-dose","winding-pack"]),
     ("first-wall-fluence","First-Wall Fluence","Accumulated neutron exposure at the first wall, setting its life.","The first wall sees the highest neutron fluence, accumulated over full-power years, which sets how often it is replaced. Kronos reports the wall loading that drives it rather than assuming long life.",["fluence","full-power-year","first-wall"]),
     ("plant-simulator","The Plant Simulator","A full-plant model used for design, control and training.","A plant simulator models the whole facility's behaviour for scenario design, control development and operator training. Kronos's open reduced-order engines are the physics core such a simulator is built on.",["operator-training-simulator","the-simulation-stack","integrated-modeling"]),
     ("commissioning-milestones","Commissioning Milestones","The gated checkpoints from cold systems to demonstrated power.","Commissioning is marked by milestones — base vacuum, full magnetic field, integrated interlocks, first plasma, design-point operation — each a gate before the next. They structure the turn-on of a new machine.",["commissioning-overview","first-plasma","performance-demonstration"]),
     ("neutronics-optimization","Neutronics Optimisation","Arranging the blanket and shield to breed and protect at once.","Neutronics optimisation arranges breeding zones, multipliers and shields to hit the breeding-ratio target while protecting the magnets, all in limited space. It is a defining trade for the compact breeder.",["neutronics","tbr-margin","shielding-effectiveness"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
