# -*- coding: utf-8 -*-
"""Glossary batch 18 — reactor engineering, fuel cycle, neutronics coverage, deployment."""
def register(cat, page, F):
    T = [
     ("divertor-pumping","Divertor Pumping","Removing exhaust and helium ash from beneath the divertor.","Pumping ducts beneath the divertor remove neutralised exhaust gas and helium ash, controlling density and enabling detachment. Divertor pumping ties the exhaust physics to the vacuum system.",["cryopump","helium-ash","detachment"]),
     ("tbr-margin","Breeding-Ratio Margin","The safety margin above breeding self-sufficiency.","Blankets are designed for a breeding ratio comfortably above one so that real-world losses still leave the plant self-sufficient. HYPERION's target of "+F['b_TBR']+" builds in margin and surplus for export.",["tritium-breeding","tritium-self-sufficiency","breeding-zone"]),
     ("blanket-coverage","Blanket Coverage","How much of the plasma surface the breeding blanket surrounds.","Breeding needs the blanket to cover as much of the plasma-facing surface as possible; ports and gaps reduce coverage and breeding. Maximising coverage in a ported machine is a neutronics-and-layout trade.",["breeding-zone","neutron-streaming","tbr-margin"]),
     ("fuel-throughput","Fuel Throughput","The rate fuel must be injected and recycled to sustain the burn.","Because only a fraction of fuel burns per pass, throughput — the injection and recycling rate — is much larger than the consumption rate. It sizes the fuelling and processing systems.",["burn-fraction","fuel-cycle","fueling-efficiency"]),
     ("cooldown-time","Magnet Cool-Down Time","The weeks it takes to chill the magnets before operation.","Cooling the large cold mass to operating temperature takes weeks and is staged to limit thermal stress. It is a fixed part of the commissioning and any maintenance-restart timeline.",["cooldown-sequence","cold-mass","commissioning"]),
     ("magnet-charging-time","Magnet Charging Time","How long it takes to energise the magnets to full field.","Ramping magnets to full field is limited by stability and AC losses, taking from minutes to hours depending on design. For steady-state machines this is a one-time operation per campaign.",["ramp-rate","superconducting-magnets","ac-loss"]),
     ("factory-fabrication","Factory Fabrication & Modularity","Building modules in factories to speed and de-risk construction.","Fabricating standardised modules in factories, then assembling on site, can speed construction and improve quality. The burner's modular, repeated central-cell units especially suit this approach.",["central-cell-solenoid","assembly-sequence","the-path-to-build"]),
     ("first-of-a-kind","First-of-a-Kind vs Nth-of-a-Kind","How a technology matures from its first build to routine production.","The first build of any technology is hardest and least optimised; later units benefit from experience and standardisation. Kronos's modular burner is designed to move toward routine, repeated production.",["factory-fabrication","innovation-modular-housings","availability-growth"]),
     ("site-selection","Site Selection","Choosing where to build, balancing grid, cooling, and access.","Site selection weighs grid connection, cooling water, seismic conditions, and regulatory factors. The low-neutron burner's point-of-use character widens siting options compared with a neutron-heavy plant.",["grid-interconnection","water-use","land-use"]),
     ("plasma-facing-first-wall-coverage","First-Wall Coverage","Ensuring the plasma-facing surface is fully protected.","The first wall must cover the plasma-facing surface with armoured, cooled panels, coordinated with ports and blanket modules. Coverage and cooling together determine wall survivability.",["first-wall","blanket-coverage","first-wall-panel-component"]),
     ("penetration-shielding","Penetration Shielding","Protecting the gaps where ports pierce the shield.","Ports and ducts are weak points where neutrons can stream through; local shielding and offset geometry protect against it. It is a detailed neutronics-and-layout task on the breeder.",["neutron-streaming","port-plug","shielding-effectiveness"]),
     ("tritium-release-pathways","Tritium Release Pathways","The routes tritium could take, all engineered against.","Tritium could in principle escape via permeation, leaks or effluent water; each pathway is engineered against with barriers, detritiation and monitoring. Mapping and closing them is core to tritium safety.",["tritium-safety","water-detritiation","secondary-containment"]),
     ("neutron-heating-rate","Nuclear Heating Rate","How fast neutrons and gammas deposit heat in each component.","The nuclear heating rate sets how much cooling each component — especially the magnets — needs to handle the energy neutrons and gammas deposit. Computing it is essential to thermal design.",["kerma","monte-carlo-neutronics","thermal-hydraulics"]),
     ("component-testing","Component Prototype Testing","Proving key components in test facilities before the full machine.","Before construction, key components — a magnet test coil, a divertor mock-up, a plug demonstration — are proven in dedicated test facilities. This demonstration work is a named stage on the path to build.",["acceptance-testing","the-path-to-build","gate-reviews"]),
     ("magnet-test-coil","The Magnet Test Coil","A representative coil built and powered to prove the magnet technology.","A magnet test coil validates the winding, joints, quench protection and — critically — the cyclic fatigue behaviour that is the burner's binding magnet gate. It is a key demonstration before committing to the full magnet system.",["magnet-fatigue","component-testing","superconducting-magnets"]),
     ("plug-demonstration","The Plug Demonstration","The experiment that must prove the burner's plug-density requirement.","The gating experiment for the burner is a plug demonstration reaching the required plug-to-central density ratio (~"+F['u_np']+"). Until it succeeds, the burner's net power stays requirement-class — which Kronos states openly.",["plug-density-requirement","component-testing","the-burner-design-point"]),
     ("prototype-plant","The Prototype Plant","The first integrated machine that demonstrates the whole system.","After component demonstrations, an integrated prototype proves the complete system and its performance — the gate between demonstration and commercial products. It is a defined future milestone, not a present claim.",["gate-reviews","the-path-to-build","performance-demonstration"]),
     ("scale-up","Scaling to Commercial Products","Moving from prototype to the AEGIS and MetroVolt products.","With the physics core proven, Kronos scales the burner by length into its AEGIS and MetroVolt products — the same physics, packaged for different markets. Modular scaling is a distinctive commercial advantage.",["innovation-modular-housings","metrovolt","aegis"]),
     ("deployment-roadmap","The Deployment Roadmap","The staged path from design study to fielded products.","The roadmap runs design study &rarr; component demonstration &rarr; integrated prototype &rarr; commercial products, gated at each step. Kronos presents it as targets with named gates, not dates or guarantees.",["gate-reviews","the-path-to-build","prototype-plant"]),
     ("technology-readiness","Technology Readiness","Judging how mature each subsystem is, honestly.","Technology-readiness assessment grades each subsystem's maturity from concept to demonstrated hardware. Kronos maps its subsystems this way — most conventional plant ready for detailed design, the binding gates named — rather than claiming uniform readiness.",["the-path-to-build","gate-reviews","component-testing"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
