# -*- coding: utf-8 -*-
"""FAQ batch 3 — technical, commercial and safety questions."""
def register(cat, page, F):
    Q = [
     ("how-much-fuel-does-fusion-need","How much fuel does a fusion plant actually use?","Grams per day — fusion is millions of times more fuel-efficient than combustion.",
      ["Very little. Because each fusion reaction releases millions of times more energy than a chemical bond, a plant consumes only grams of fuel per day. The breeder even makes its own tritium; deuterium comes from water. Fuel supply is not the constraint fusion faces.",
       "This energy density is why fusion's footprint and fuel logistics are so favourable."],
      ["deuterium","tritium-supply","specific-power"]),
     ("what-is-the-neutron-wall-loading","Why does neutron wall loading matter so much?","It sets how fast materials wear and how often components are replaced.",
      [f"Neutron wall loading — {F['b_wall']} on HYPERION's first wall — drives the damage rate in materials and therefore component lifetime and maintenance frequency. The neutron-rich breeder carries this load deliberately; the low-neutron burner far less. It is a first-order design and materials driver.",
       "Kronos states the loadings rather than assuming materials cope."],
      ["neutron-wall-loading","dpa","first-wall"]),
     ("can-fusion-be-cheap","Can fusion ever be cheap?","Cost is the open question — Kronos's answer is a saleable product first and honest cost studies, not a claim.",
      ["Fusion's cost competitiveness is genuinely open, and Kronos treats it that way — as its central commercial studies (capital and availability), not a settled result. Its distinctive answer is to sell materials and isotopes before net electricity, so early value does not wait on solving cost.",
       "Kronos keeps economics off its public technical pages and does not make cost claims here."],
      ["capacity-factor","the-breeder-first-strategy","how-to-compare-fusion"]),
     ("what-is-a-driven-system","What does it mean that Kronos is a 'driven' system?","It is continuously heated rather than self-igniting — which makes it controllable.",
      [f"A driven system produces a steady multiple of continuous external heating rather than sustaining itself by fusion self-heating (ignition). HYPERION's Q = {F['b_Q']} and the burner's Q<sub>E</sub> = {F['u_QE']} are driven figures. The advantage is control: turn the heating down and the power responds.",
       "Kronos chooses driven operation deliberately and quotes finite gain honestly."],
      ["ignition-vs-driven","burn-control","fusion-gain-q"]),
     ("why-spherical-tokamak","Why a spherical tokamak for the breeder?","It holds more plasma pressure per tesla — the route to a compact neutron source.",
      [f"A spherical tokamak's low aspect ratio (A = {F['b_A']}) lets it hold high plasma pressure (&beta;<sub>N</sub> = {F['b_bN']}) for a given field, making a compact, economical machine. Since the breeder's job is to be a dense neutron and tritium source, that compactness is exactly what it needs.",
       "The trade is a tight central column, which Kronos treats as a named design focus."],
      ["spherical-tokamak","aspect-ratio","centre-column-challenge"]),
     ("why-not-just-dt","Why not just build one D–T machine like everyone else?","Because a breeder-plus-low-neutron-burner sells a product sooner and makes cleaner electricity.",
      ["A single D–T machine must solve net electricity before it has anything to sell, and puts most of its energy into neutrons it then has to convert thermally. Kronos's split lets the breeder sell fuel and isotopes early, and the burner make electricity cleanly by direct conversion. Different bet, different risk profile.",
       "Both still face hard physics; Kronos claims a better arrangement of it, not an escape from it."],
      ["kronos-vs-dt-tokamak","the-breeder-first-strategy","innovation-two-machine-architecture"]),
     ("how-does-direct-conversion-work","How does direct energy conversion work?","It decelerates escaping ions against an electric field, capturing their energy as electricity.",
      [f"Direct conversion sends the burner's escaping charged particles into a biased electrode array that decelerates them, turning their kinetic energy straight into electric current at about {F['u_dec']} — no boiler, no turbine. It only works because D–&sup3;He keeps most energy in charged particles.",
       "It is what gives the burner its engineering-gain advantage."],
      ["direct-energy-conversion","dec-collector-ring","d-he3-fuel"]),
     ("is-tritium-a-problem","Is tritium a showstopper?","No — it is a handled hazard, and the breeder makes its own so supply is not a constraint.",
      [f"Tritium is radioactive and must be handled carefully, but it is a well-understood, low-energy emitter managed with low inventories ({F['b_startup']} startup), permeation barriers and monitoring. Crucially, the breeder breeds its own ({F['b_T']}/yr at TBR {F['b_TBR']}), so supply is a feature, not a bottleneck.",
       "Kronos names tritium handling as a licensing-relevant gate rather than waving it away."],
      ["tritium-safety","tritium-breeding","tritium-plant"]),
     ("what-if-the-plug-fails","What if the burner's plug requirement can't be met?","Then the burner does not close as a net-power machine — which is exactly why Kronos labels it requirement-class.",
      [f"If a plug demonstration cannot reach the required density ratio (~{F['u_np']}), the burner does not close as a net-electric machine at the design point. Kronos is explicit about this: the burner's net power is requirement-class, a target to be demonstrated. The breeder's value — fuel, neutrons, isotopes — does not depend on it.",
       "Stating the failure mode openly is part of the honesty framework."],
      ["plug-density-requirement","validation-suite-burner","the-breeder-first-strategy"]),
     ("how-big-is-a-kronos-plant","How big is a Kronos machine?","The breeder is compact (~1.2 m major radius); the burner scales in length from 55 to 1400 m by product.",
      [f"The breeder is genuinely compact — a {F['b_R0']} major-radius spherical tokamak. The burner is linear and scales by product: {F['u_ref_len']} (reference), {F['u_aeg_len']} (AEGIS), {F['u_mv_len']} (MetroVolt). One physics core, three lengths.",
       "Compactness comes from high field; the burner's length sets its power class."],
      ["compact-vs-conventional","innovation-modular-housings","the-burner-design-point"]),
     ("does-fusion-use-rare-materials","Does fusion depend on rare materials?","The fuels are abundant; the notable scarce input is helium-3, which the breeder makes itself.",
      [f"Deuterium is from seawater and lithium (for breeding) is common. The genuinely scarce input is helium-3 for the burner — which is exactly why the breeder co-produces it ({F['b_He3']}/yr), giving Kronos an internal supply rather than a dependency.",
       "REBCO superconductor uses rare-earth elements, but in small tape quantities."],
      ["helium-3-supply","deuterium","rebco-tape"]),
     ("what-makes-this-credible","Kronos is a small company — why believe any of this?","Because you can download and re-run the engines, and every caveat is stated up front.",
      ["Credibility here does not rest on trust. The reduced-order engines, inputs and expected outputs are open on Zenodo and reproduce; the physics runs live in your browser; the design is frozen so nothing drifts; and the binding gates are named. A small team can be checked as rigorously as a large one when it publishes this way.",
       "The team also brings decades of fusion-programme experience, anchoring conservative assumptions to real databases."],
      ["reproducibility-overview","honesty-framework","the-experience-behind-kronos"]),
    ]
    for slug,q,one,ans,rel in Q:
        page(slug,q,"faq",one,one,[('qa',[(q," ".join(f"<p>{a}</p>" for a in ans))])],related=rel,jtype="FAQPage",kicker="Question")
