# -*- coding: utf-8 -*-
"""Glossary batch 11 — fuel-cycle processing, cryogenics, balance-of-plant."""
def register(cat, page, F):
    T = [
     ("cryogenic-distillation","Cryogenic Distillation","The low-temperature process that separates hydrogen isotopes.","Cryogenic distillation separates deuterium, tritium and protium by their tiny boiling-point differences at very low temperature. It is a core tritium-plant process for purifying and recycling fuel.",["isotope-separation","tritium-plant","fuel-cycle"]),
     ("palladium-membrane","Palladium Membrane","A membrane that purifies hydrogen isotopes by selective permeation.","Hydrogen isotopes permeate palladium while impurities do not, so palladium membranes purify the fuel stream. They are a standard tritium-plant purification technology.",["fuel-cycle","cryogenic-distillation","tritium-plant"]),
     ("getter-bed","Getter Bed","A material bed that absorbs and stores tritium safely.","Getter beds use metals that absorb hydrogen isotopes to store and control tritium at low pressure and hazard. They are safer than storing tritium as a gas and are used throughout the fuel cycle.",["storage-bed","tritium-plant","tritium-safety"]),
     ("storage-bed","Tritium Storage Bed","The controlled bed where tritium inventory is held.","Tritium is stored absorbed in metal-hydride beds that release it on heating, keeping inventory low-pressure and accountable. Storage-bed management is central to tritium accountancy.",["getter-bed","tritium-inventory","tritium-plant"]),
     ("detritiation","Detritiation","Removing tritium from gases, water and materials for safety and recovery.","Detritiation systems strip tritium from process streams, room air and waste water, both to recover valuable fuel and to limit releases. They are a key safety and accountancy system on the breeder.",["water-detritiation","tritium-safety","stack-monitoring"]),
     ("water-detritiation","Water Detritiation","Recovering tritium that ends up in water.","Because tritium readily forms tritiated water, a water-detritiation system recovers it from coolant and effluent, protecting the environment and recovering fuel. It is a specialised tritium-plant subsystem.",["detritiation","tritium-safety","primary-coolant"]),
     ("secondary-containment","Secondary Containment","Nested barriers that keep tritium from escaping.","Tritium systems use multiple nested containment barriers — gloveboxes, room confinement, ventilation — so that any leak is captured rather than released. Layered containment is fundamental to tritium safety.",["tritium-safety","detritiation","stack-monitoring"]),
     ("stack-monitoring","Stack Monitoring","Continuous measurement of any tritium released to the environment.","Continuous stack monitoring measures and records any tritium leaving the facility, ensuring releases stay within limits and providing accountancy. It is a regulatory-relevant safety system.",["secondary-containment","tritium-safety","tritium-standards"]),
     ("helium-liquefaction","Helium Liquefaction","The refrigeration that produces the liquid helium magnets need.","Cryoplants liquefy helium through compression and expansion to reach the temperatures superconducting magnets require. It is mature, if bespoke and large, big-science technology.",["cold-box","joule-thomson-effect","cryogenic-system"]),
     ("joule-thomson-effect","Joule–Thomson Cooling","Cooling a gas by expanding it — a stage of helium refrigeration.","Expanding high-pressure helium through a valve cools it (the Joule–Thomson effect), a final stage in reaching liquid-helium temperatures. It is part of the cold box's refrigeration cycle.",["helium-liquefaction","turboexpander","cold-box"]),
     ("turboexpander","Turboexpander","A turbine stage that cools helium in the cryoplant.","A turboexpander extracts work from expanding helium, cooling it efficiently as part of the refrigeration cycle. It is a key rotating component of the cold box.",["helium-liquefaction","joule-thomson-effect","cold-box"]),
     ("mli-insulation","Multi-Layer Insulation","Reflective layers that block radiant heat in the cryostat.","Multi-layer insulation — many thin reflective sheets in vacuum — drastically cuts radiant heat reaching the cold mass, reducing the cryoplant's load. It works alongside the actively-cooled thermal shield.",["thermal-shield-component","cryostat","cold-mass"]),
     ("cooldown-sequence","Cool-Down Sequence","The careful staged chilling of the magnets before operation.","Cooling the large cold mass from room temperature to cryogenic operation takes weeks and must be staged to limit thermal stress. The cool-down and its reverse (warm-up for maintenance) are planned operational procedures.",["cold-mass","cryogenic-system","commissioning"]),
     ("heat-rejection-system","Heat Rejection","Getting the plant's waste heat to the environment.","Every thermal plant must reject waste heat, through cooling towers or water bodies. For the breeder this is conventional; the burner's direct conversion reduces the waste heat to reject.",["cooling-tower","power-conversion","water-use"]),
     ("cooling-tower","Cooling Tower","The structure that sheds a thermal plant's waste heat to air.","Cooling towers evaporate water to reject waste heat to the atmosphere, standard equipment for thermal plants. The burner's direct conversion can reduce reliance on them.",["heat-rejection-system","water-use","steam-cycle"]),
     ("turbine-generator","Turbine-Generator","The rotating machine that turns the breeder's heat into electricity.","On the breeder's thermal side, a turbine-generator converts steam energy to electricity — conventional power-plant machinery. The burner replaces it with direct conversion.",["steam-cycle","power-conversion","direct-energy-conversion"]),
     ("scada-system","SCADA & Plant Control","The supervisory system that monitors and controls plant systems.","A supervisory control-and-data-acquisition system oversees the balance of plant — cooling, power, cryo, vacuum — coordinating with the fast plasma control and the safety system. It is standard industrial control at plant scale.",["plasma-control-system","instrumentation-control","balance-of-plant"]),
     ("operator-training-simulator","Operator Training & Simulators","Training operators on a simulator before running the real machine.","Operators train on plant and plasma simulators — like the reduced-order engines Kronos deposits — before running hardware, building the procedures and judgement safe operation needs. It links the simulation stack to operations.",["the-simulation-stack","scada-system","commissioning"]),
     ("plant-startup-shutdown","Plant Start-Up & Shutdown","The orchestrated sequences that bring the whole plant on and offline.","Beyond the plasma, the whole plant has start-up and shutdown sequences — energising, pumping, cooling, and their reverse — that must be safe and repeatable. They are core operating procedures developed before first operation.",["cooldown-sequence","commissioning","operating-modes"]),
     ("operating-modes","Operating Modes","The distinct states a plant runs in, from standby to full power.","A plant runs in defined modes — standby, conditioning, full power, maintenance — each with its own procedures and interlocks. Clear mode definitions are part of safe, reproducible operation.",["plant-startup-shutdown","real-time-control","maintainability"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
