# -*- coding: utf-8 -*-
"""Glossary batch 8 — gain metrics, magnet engineering, blanket materials, divertor concepts."""
def register(cat, page, F):
    T = [
     ("scientific-breakeven","Scientific Breakeven","Fusion power equalling heating power — Q = 1, the plasma-physics milestone.","Scientific breakeven (Q = 1) is where a plasma produces as much fusion power as the heating put into it. It is a physics milestone, distinct from a plant that delivers net electricity. HYPERION's Q = "+F['b_Q']+" is comfortably past it.",["fusion-gain-q","engineering-breakeven","ignition-vs-driven"]),
     ("engineering-breakeven","Engineering Breakeven","A plant producing as much electricity as the whole facility consumes.","Engineering breakeven counts net electricity against total plant consumption — the commercially meaningful bar, well beyond scientific breakeven. Kronos reports plant-level gain (burner Q<sub>E</sub> = "+F['u_QE']+") separately from plasma Q for exactly this reason.",["net-electric-power","fusion-gain-q","scientific-breakeven"]),
     ("wall-plug-efficiency","Wall-Plug Efficiency","How efficiently a heating or conversion system turns grid power into useful output.","Wall-plug efficiency is the ratio of useful output to electrical input for a system — a heating injector or a converter. Low efficiencies inflate recirculating power, so they feed directly into the engineering-gain ledger.",["recirculating-power","heating-systems","direct-energy-conversion"]),
     ("magnetic-pressure","Magnetic Pressure","The outward push of a magnetic field — what confines plasma and stresses magnets.","A magnetic field exerts a pressure proportional to field squared; it both confines the plasma (balancing plasma pressure via beta) and stresses the magnet that makes it. At "+F['b_Bpeak']+" the magnetic pressure is immense, driving structural design.",["plasma-beta","hoop-stress","high-field-magnets"]),
     ("current-quench","Current Quench","The rapid collapse of plasma current during a disruption.","The current quench is the phase of a disruption where the plasma current collapses in milliseconds, inducing large forces and driving runaway electrons. Its speed and forces set structural loads on the breeder.",["disruptions","halo-current","thermal-quench"]),
     ("thermal-quench","Thermal Quench","The sudden loss of plasma thermal energy that starts a disruption.","The thermal quench is the first, fastest phase of a disruption: the plasma's stored heat dumps onto the wall in under a millisecond, before the current collapses. It drives the peak heat loads a disruption imposes.",["disruptions","current-quench","stored-plasma-energy"]),
     ("current-sharing-temperature","Current-Sharing Temperature","The temperature at which current starts leaving the superconductor for the copper.","As a superconductor warms toward its critical temperature, current begins sharing into the copper stabiliser. The margin to this temperature — the temperature margin — is a key magnet-stability metric mapped in the REBCO study.",["temperature-margin","rebco-tape","quench-protection"]),
     ("temperature-margin","Temperature Margin","How much a magnet can warm before it starts to quench.","The temperature margin is the gap between the operating temperature and where current-sharing begins. Adequate margin keeps a magnet stable against transient heat loads; it is a core magnet-design parameter.",["current-sharing-temperature","cryogenic-stability","rebco-tape"]),
     ("cryogenic-stability","Cryogenic Stability","A magnet's ability to recover from a local heat pulse without quenching.","A cryogenically stable magnet can absorb a small heat disturbance and cool back down rather than quenching. Stability margins, conductor design and cooling all contribute, and they underpin reliable magnet operation.",["temperature-margin","quench-protection","cold-mass"]),
     ("ac-loss","AC Loss","Heat generated in superconductors by changing fields or currents.","Superconductors dissipate some heat when their field or current changes — AC loss. It adds to the cryogenic load during ramps and pulsed operation, favouring steady-state designs and careful conductor engineering.",["cryogenic-stability","eddy-current","steady-state-operation"]),
     ("eddy-current","Eddy Currents","Currents induced in structures by changing magnetic fields.","Changing magnetic fields induce eddy currents in conductive structures, causing heating and forces. They matter during ramps and disruptions and are managed through structural design and segmentation.",["ac-loss","halo-current","vacuum-vessel"]),
     ("snowflake-divertor","Snowflake Divertor","An advanced divertor geometry that spreads heat over more surface.","The snowflake divertor uses a second-order magnetic null to flare the field lines, spreading exhaust heat over a larger target area. It is one of several advanced divertor concepts for handling extreme heat flux.",["divertor","super-x-divertor","x-point"]),
     ("super-x-divertor","Super-X Divertor","A long-legged divertor that increases connection length to ease heat load.","The Super-X divertor routes the exhaust to a target at larger major radius with a longer connection length, giving more volume to radiate and detach. It is an advanced option for high-power divertor operation.",["snowflake-divertor","connection-length","detachment"]),
     ("liquid-metal-divertor","Liquid-Metal Divertor","A self-healing divertor surface of flowing liquid metal.","Flowing liquid metal (such as lithium) as a divertor surface can tolerate high heat flux and self-heal erosion, an alternative to solid tungsten. It is an active research direction for the exhaust problem.",["divertor","liquid-lithium-wall","tungsten-divertor"]),
     ("liquid-lithium-wall","Liquid-Lithium Wall","A lithium plasma-facing surface that can improve confinement and handle heat.","Coating or flowing lithium on plasma-facing surfaces can lower recycling, improve confinement and tolerate heat, while also relating to tritium breeding. It is a research concept for both wall protection and performance.",["liquid-metal-divertor","plasma-facing-materials","lithium-blanket"]),
     ("eurofer-steel","EUROFER Steel","A reduced-activation ferritic-martensitic steel developed for fusion structures.","EUROFER is a leading low-activation structural steel developed specifically for fusion blankets, engineered so that after irradiation it decays to hands-on levels in decades. It exemplifies the low-activation materials strategy.",["low-activation-steel","neutron-damage-materials","blanket"]),
     ("ods-steel","Oxide-Dispersion-Strengthened Steel","A steel reinforced with fine oxides for high-temperature, high-dose service.","ODS steels disperse nanoscale oxide particles through the metal, raising high-temperature strength and radiation tolerance. They are candidates for the most demanding structural roles in a fusion blanket.",["low-activation-steel","radiation-swelling","eurofer-steel"]),
     ("ceramic-breeder","Ceramic Breeder","Solid lithium-ceramic pebbles that breed tritium in the blanket.","Lithium ceramics — orthosilicate or titanate pebbles — breed tritium as neutrons strike their lithium, in a helium-cooled pebble-bed blanket. They are one of the main solid-breeder blanket routes.",["breeding-material","blanket","helium-cooled-blanket"]),
     ("lead-lithium","Lead-Lithium (PbLi)","A liquid metal that breeds tritium and can cool the blanket.","Liquid lead-lithium eutectic breeds tritium (its lithium) while its lead multiplies neutrons, and it can also carry heat. It underpins liquid-metal blanket concepts, traded against magnetohydrodynamic pumping effects.",["breeding-material","neutron-multiplier","blanket"]),
     ("helium-cooled-blanket","Helium-Cooled Blanket","A blanket cooled by high-pressure helium — chemically inert and tritium-friendly.","Helium coolant is inert and does not activate, easing tritium control, and pairs with ceramic-breeder pebble beds. It is a leading blanket-cooling concept, traded against pumping power.",["ceramic-breeder","primary-coolant","blanket"]),
     ("plasma-volume","Plasma Volume","The volume of confined plasma — it scales the total fusion power.","Total fusion power scales with plasma volume times power density, so volume sets absolute output for a given design. A compact machine trades smaller volume for higher power density via high field and beta.",["specific-power","plasma-pressure","compact-vs-conventional"]),
     ("current-density","Current Density","How much current flows per unit area — high in both plasma and superconductor.","Current density appears twice in fusion: the plasma's, which shapes stability, and the superconductor's, whose high value is what makes compact magnets possible. REBCO's exceptional current density is the enabling property.",["plasma-current","rebco-tape","critical-current"]),
     ("minimum-quench-energy","Minimum Quench Energy","The smallest disturbance that will tip a magnet into a quench.","The minimum quench energy is the heat pulse a conductor can absorb before quenching; higher is safer. It is a stability metric that conductor and cooling design aim to maximise.",["cryogenic-stability","temperature-margin","quench-protection"]),
     ("hot-spot-temperature","Hot-Spot Temperature","The peak temperature reached at a quench site, which must stay bounded.","During a quench the local temperature must be kept below a limit to avoid damage; Kronos's adiabatic analysis reports the magnet as self-protecting within its design basis. Bounding the hot spot is the goal of quench protection.",["quench-protection-detail","quench-detection","design-basis"]),
     ("net-energy-gain","Net Energy Gain","More energy out than in — the milestone the whole field aims at.","Net energy gain means a plant delivers more energy than it consumes over its cycle. Kronos distinguishes plasma-level gain from this plant-level goal and reports both honestly, with the burner's net figures labelled requirement-class.",["engineering-breakeven","net-electric-power","fusion-gain-q"]),
     ("plasma-facing-armor","Plasma-Facing Armour","The sacrificial surface layer that takes erosion and heat.","Armour — usually tungsten — is the front surface of plasma-facing components, taking erosion and heat so the structure behind survives. It is designed to be inspected and replaced as it wears.",["plasma-facing-materials","tungsten-divertor","first-wall-panel-component"]),
     ("tritium-plant","The Tritium Plant","The integrated facility that processes all of the plant's tritium.","The tritium plant receives bred tritium, purifies and stores it, feeds it to the plasma, and accounts for every gram. It is a licensing-critical facility unique to the D–T breeder side of Kronos.",["fuel-cycle","tritium-extraction-unit","tritium-safety"]),
     ("isotope-separation","Isotope Separation","Sorting hydrogen isotopes to recycle fuel and recover products.","The fuel cycle must separate hydrogen isotopes — deuterium, tritium, protium — to recycle fuel and purify products. Isotope separation is a core tritium-plant process.",["tritium-plant","fuel-cycle","helium-3"]),
     ("shielding-blanket","Shielding vs Breeding Trade","Balancing neutron shielding against tritium breeding in the blanket.","Every neutron either breeds tritium, is captured usefully, or is wasted in shielding — and space is limited. Balancing breeding against magnet-protecting shielding is a central blanket-neutronics trade in the compact breeder.",["blanket","shielding","tritium-breeding"]),
     ("plasma-current-ramp","Current Ramp-Up and Ramp-Down","Safely raising and lowering the plasma current at the start and end of a discharge.","Ramping the current up to flat-top and back down must avoid instabilities and manage the flux budget. Ramp design is part of the operating scenario and matters for both stability and solenoid demand.",["tokamak-startup","volt-seconds","plasma-startup-scenario"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
