# -*- coding: utf-8 -*-
"""Glossary depth batch A — a real second paragraph per term (mechanism + Kronos context)."""
def register(cat, page, F, enrich):
    G = {
     "aspect-ratio": f"Aspect ratio is the master geometric lever of a tokamak. Dropping from a conventional A of about 3 to HYPERION's {F['b_A']} sharply raises the achievable plasma pressure per unit field and improves natural shaping, which is what lets a small machine reach reactor-relevant performance. The penalty is paid at the centre: the inboard column has almost no room for the solenoid, toroidal-field conductor and neutron shielding, making it the defining engineering focus of the breeder.",
     "elongation": f"Higher elongation increases the plasma cross-sectional area and the current it can carry at fixed edge safety factor, both of which raise fusion performance. It comes at the cost of vertical instability: a tall plasma drifts up or down and must be held by fast feedback control. HYPERION's &kappa; = {F['b_kappa']} is well within what spherical tokamaks demonstrate, and the control coils and power supplies are sized for it.",
     "triangularity": f"For decades positive triangularity was standard because it supports the H-mode pedestal. Negative triangularity, which HYPERION adopts at &delta; = {F['b_delta']}, has emerged from experiments (notably on DIII-D and TCV) as a way to access good confinement while avoiding the large edge-localised modes that damage divertors — solving an operational problem through configuration rather than added machinery.",
     "safety-factor": f"The safety factor ties directly to stability limits: the external kink is avoided by keeping the edge q above about 2, and rational surfaces where q is a simple fraction are where tearing modes grow. HYPERION's q&#8329;&#8325; = {F['b_q95']} is a deliberately conservative choice that keeps the current profile clear of the most disruptive resonances.",
     "plasma-beta": f"Beta is the economic figure of merit for confinement: a machine that holds more plasma pressure per tesla makes more fusion power for less magnet. Spherical tokamaks excel here because their low aspect ratio raises the beta limit. HYPERION's &beta;<sub>N</sub> = {F['b_bN']} sits comfortably below the no-wall limits observed on machines like NSTX, so it does not rely on wall or feedback stabilisation.",
     "bootstrap-current": f"The bootstrap current is a gift from neoclassical physics: a pressure gradient drives toroidal current for free, reducing the external drive a steady-state machine must supply. Raising the bootstrap fraction is a central efficiency goal, but it is bounded by stability. HYPERION bootstraps {F['b_fbs']} of its {F['b_Ip']}, with the remainder driven by neutral beams and radio-frequency systems.",
     "energy-confinement-time": f"Because turbulence resists first-principles prediction, confinement time is estimated from empirical scaling laws fit to a large multi-machine database. HYPERION assumes only standard H-mode confinement (H<sub>98</sub> = {F['b_H98']}), giving &tau;<sub>E</sub> = {F['b_tauE']} — a deliberately unaggressive choice that Kronos names as a gate rather than treating as demonstrated.",
     "h-mode": f"The H-mode transition is one of fusion's most important empirical discoveries: above a power threshold, an edge transport barrier forms and roughly doubles confinement. Reaching and sustaining it shapes the heating requirement. HYPERION is designed at H<sub>98</sub> = 1 — standard H-mode — rather than betting on an enhanced regime.",
     "edge-localized-modes": f"ELMs are the price of the H-mode pedestal: the stored edge energy is expelled in periodic bursts that erode the divertor and first wall. Large machines invest heavily in ELM control. HYPERION's negative triangularity is chosen partly to suppress them passively, easing one of the toughest lifetime problems in tokamaks.",
     "disruptions": "A disruption chains a sub-millisecond thermal quench with a millisecond current quench, dumping heat on the wall, driving large electromagnetic forces through halo and eddy currents, and potentially generating runaway electrons. Managing disruption risk drives much of a tokamak's structural design — which is why the disruption-free tandem-mirror burner is architecturally attractive.",
     "greenwald-density": "The Greenwald limit is one of the most robust empirical boundaries in tokamak physics, scaling with plasma current over minor-radius area. Operating below it is a firm constraint for the breeder; the burner, being a linear mirror, is not subject to it and instead operates at its design density set by the fuel trajectory.",
     "mhd-stability": "MHD stability sets the hard ceilings on how much pressure and current a machine can safely hold. Ideal modes grow on the microsecond Alfvén timescale and must be avoided by design, while resistive modes like tearing grow more slowly and can be controlled. Kronos's conservative beta, moderate q and negative triangularity place the breeder in a benign region of this space.",
     "current-drive": f"Steady-state operation requires sustaining the plasma current indefinitely, so whatever the bootstrap effect does not supply must be driven externally by beams or waves. Current-drive efficiency directly inflates or deflates the plant's recirculating power. HYPERION's {F['b_Paux']} of auxiliary power both heats the plasma and drives its non-bootstrap current.",
     "divertor": "The divertor is where the plasma's exhaust meets solid matter, and concentrating that heat on a small target can exceed material limits. The modern solution is to radiate most of the exhaust power before it lands and to run the target plasma detached. HYPERION leans on a high radiated fraction — effective, and named as a performance gate rather than assumed.",
     "first-wall": f"The first wall absorbs radiation, neutrons and stray particles, and its heat-flux and neutron-damage tolerance set component lifetimes. HYPERION's is rated for {F['b_wall']}; the burner's is far gentler because its low neutron fraction and linear geometry spread the load. Both are designed as replaceable, inspectable components.",
     "blanket": f"The breeding blanket does three jobs at once: it slows fusion neutrons, breeds tritium from lithium, and recovers the neutrons' energy as heat. Its breeding ratio must exceed one with margin for the plant to fuel itself. HYPERION targets {F['b_TBR']}, producing {F['b_T']} of tritium while co-producing helium-3 for the burner.",
     "tritium-breeding": f"Since tritium is essentially absent in nature and decays with a ~12-year half-life, a D–T plant must breed its own or it cannot run. Lithium-6 is the key breeding isotope, often enriched, with a neutron multiplier added to reach the target ratio. HYPERION's TBR of {F['b_TBR']} is designed to be self-sufficient and to export a surplus.",
     "mirror-ratio": f"The mirror ratio — throat field over central field — determines the fraction of particle velocities that are magnetically reflected rather than lost through the ends. Higher ratios trap more, but simple mirrors still leak through the loss cone. The Kronos burner combines high-field plugs ({F['u_Bm']} throat, {F['u_Bplug']} plug) with an electrostatic potential to close that leak.",
     "ambipolar-potential": f"The ambipolar potential is the mechanism that makes a modern tandem mirror viable: dense end plugs build an electrostatic barrier that confines central-cell ions where magnetism alone cannot. Its depth scales with the plug-to-central density ratio, which is why the Kronos burner's net power depends on reaching a ratio near {F['u_np']}.",
     "direct-energy-conversion": f"Direct conversion is the burner's signature advantage: by decelerating escaping ions against a biased electrode array, it recovers their energy as electricity at about {F['u_dec']}, sidestepping the Carnot-limited steam cycle entirely. It only works because D–&sup3;He keeps most of the fusion energy in charged particles rather than neutrons.",
     "rebco": f"REBCO's ability to carry very high current density in very high field is what collapsed the size and cost of a fusion machine over the last decade. It lets HYPERION reach {F['b_Bpeak']} and the burner plug {F['u_Bplug']} continuously — fields impossible with older low-temperature superconductors. Kronos's REBCO study benchmarks these claims against demonstrated coils.",
     "quench-protection": "A quench must be detected and its stored energy removed before a local hot spot forms, because REBCO's slow quench propagation makes early detection critical. Kronos analyses the peak temperature with an adiabatic method and reports the magnet as self-protecting within its design basis — one of the few results confirmed in-model rather than left open.",
     "plasma": "Because its charges respond collectively to fields, a plasma can be shaped, heated and confined magnetically — the entire basis of the tokamak and the mirror. It also supports a rich zoo of waves and instabilities, which is why so much of fusion engineering is really the engineering of plasma behaviour.",
     "tokamak": "The tokamak's combination of a strong externally-produced toroidal field and a plasma-driven poloidal field gives it the best-studied and highest confinement of any concept, but at the cost of needing to drive and control that plasma current and to manage disruptions. HYPERION is a compact, low-aspect-ratio member of this family.",
     "coulomb-barrier": "Nuclei mostly cross the Coulomb barrier by quantum tunnelling rather than going over it, which is why fusion proceeds at temperatures far below the classical barrier height and why the reaction rate climbs so steeply with temperature. Choosing a fuel is largely choosing how high that barrier is — D–T lowest, D–&sup3;He higher, proton–boron highest.",
     "reactivity": f"Reactivity rises steeply with temperature and then saturates, which sets each fuel's operating point: D–T peaks near {F['b_Ti']}, while D–&sup3;He requires the burner's much hotter {F['u_Ti']}. Kronos does not choose these temperatures arbitrarily — each is dictated by where its fuel's reactivity pays off against the losses.",
     "the-neutron-economy": f"The neutron economy reframes the breeder's {F['b_Pn']} of neutron power from a shielding burden into a product line. Those neutrons breed tritium, co-produce helium-3, and can make medical and industrial isotopes — value that exists whether or not grid-scale net-electric fusion is ever solved, and the foundation of the breeder-first strategy.",
    }
    for slug, para in G.items():
        enrich(slug, add_body=[('p', para)])
