# -*- coding: utf-8 -*-
"""Embed silent hero clips (muted autoplay loops) on Technical Library pages.
Clips are the 506-clip Kronos library, hosted on Cloudflare R2. The page->clip map is
auto-generated by keyword match (see _clip_page_map.json; rebuild with build_clip_map.py)."""
import os, json, re
HERE = os.path.dirname(os.path.abspath(__file__))
CLIPS_BASE = "https://pub-6f4141e515994eaf98b678a16ccbf603.r2.dev/"

def _caption(clip_slug):
    s = re.sub(r"\.mp4$", "", clip_slug)
    s = re.sub(r"^[a-z]+[0-9]*-", "", s)   # drop the group code (g4-, aa2-, breeder-hero-)
    s = s.replace("-", " ").strip()
    return "Kronos motion — " + (s[:1].upper() + s[1:] if s else "in brief") + "."

def register(cat, page, F, enrich):
    mp = {}
    fp = os.path.join(HERE, "_clip_page_map.json")
    if os.path.exists(fp):
        mp = json.load(open(fp, encoding="utf-8"))
    for slug, clip in mp.items():
        cap = _caption(clip)
        block = ('<figure class="clip"><video autoplay muted loop playsinline preload="metadata" '
                 f'aria-label="{cap}"><source src="{CLIPS_BASE}{clip}" type="video/mp4"></video>'
                 f'<figcaption>{cap}</figcaption></figure>')
        enrich(slug, add_body=[('html', block)])
