# -*- coding: utf-8 -*-
"""Glossary batch 13 — diagnostics, transport physics, blanket concepts, assurance."""
def register(cat, page, F):
    T = [
     ("polarimetry","Polarimetry","Measuring internal current from the rotation of light's polarisation.","Polarimetry reads how the plasma rotates the polarisation of a probing beam (Faraday rotation) to infer the internal magnetic field and current density. It complements interferometry for internal profiles.",["interferometry","current-profile","motional-stark-effect"]),
     ("collective-scattering","Collective Thomson Scattering","Scattering microwaves off density fluctuations to probe ions and fast particles.","Collective scattering of high-power microwaves off collective density fluctuations measures ion temperature, flows and fast-ion distributions. It is an advanced diagnostic for the ion population.",["thomson-scattering","fast-ions","plasma-diagnostics"]),
     ("gas-puff-imaging","Gas-Puff Imaging","Visualising edge turbulence by lighting it up with a gas puff.","Gas-puff imaging injects neutral gas and films the light it emits, making edge turbulence and blob filaments directly visible. It is a key tool for studying the plasma edge.",["edge-physics","drift-wave","fast-camera"]),
     ("fast-camera","Fast Visible Cameras","High-speed cameras that image plasma events and instabilities.","Fast visible cameras capture plasma shape, instabilities and transient events at high frame rate, aiding both physics study and machine protection. They are a widely-used, robust diagnostic.",["gas-puff-imaging","plasma-diagnostics","disruption-physics"]),
     ("ir-thermography","Infrared Thermography","Imaging surface temperatures to map heat loads on components.","Infrared cameras map the temperature of plasma-facing surfaces, revealing where heat is deposited on the divertor and first wall. It is essential for protecting components and validating exhaust models.",["heat-flux","divertor","power-exhaust"]),
     ("residual-gas-analyzer","Residual Gas Analysis","Identifying the gases present in the vacuum.","A residual gas analyser (a small mass spectrometer) identifies the species in the vacuum, monitoring purity, leaks and wall conditions. It is a routine vacuum diagnostic.",["vacuum-system","leak-detection","outgassing"]),
     ("momentum-transport","Momentum Transport","How plasma rotation is transported and sustained.","Momentum transport governs how toroidal rotation spreads and decays; since rotation stabilises instabilities, understanding it matters for performance. Turbulence can even drive rotation intrinsically, without external torque.",["plasma-rotation","intrinsic-rotation","turbulent-transport"]),
     ("intrinsic-rotation","Intrinsic Rotation","Plasma rotation that arises without external torque.","Plasmas can spin up on their own, driven by turbulence and edge effects, even without beam torque — intrinsic rotation. It is valuable because rotation stabilises resistive-wall modes at little cost.",["momentum-transport","plasma-rotation","resistive-wall-mode"]),
     ("exb-shear","E&times;B Shear Suppression","Sheared flows tearing apart turbulent eddies to improve confinement.","Sheared E&times;B flows stretch and break up turbulent eddies, suppressing transport and enabling transport barriers. It is a central mechanism behind H-mode and internal barriers.",["zonal-flow","transport-barrier","turbulent-transport"]),
     ("integrated-modeling","Integrated Modelling","Coupling many physics models to simulate a whole discharge.","Integrated modelling links transport, equilibrium, heating, current drive and stability models to simulate a full discharge self-consistently. It is how scenarios are designed and is part of the detailed-analysis path.",["reduced-order-modeling","high-fidelity-analysis","plasma-scenario-development"]),
     ("water-cooled-blanket","Water-Cooled Blanket","A blanket concept using pressurised water as coolant.","A water-cooled lithium-lead blanket uses familiar pressurised-water technology to remove heat while lead-lithium breeds tritium. It leverages mature coolant engineering, traded against tritium-in-water control.",["blanket","lead-lithium","water-detritiation"]),
     ("self-cooled-blanket","Self-Cooled Liquid-Metal Blanket","A blanket where the breeding liquid metal is also the coolant.","In a self-cooled concept, flowing liquid metal (like lead-lithium) both breeds tritium and carries the heat away, simplifying the blanket — though its flow interacts strongly with the magnetic field.",["lead-lithium","blanket","primary-coolant"]),
     ("breeding-zone","Breeding Zone","The region of the blanket where tritium is actually bred.","The breeding zone is where neutrons meet lithium and tritium is produced, arranged behind the first wall and multiplier. Its thickness and composition set the achievable breeding ratio in limited space.",["blanket","tritium-breeding","neutron-multiplier"]),
     ("coolant-manifold","Coolant Manifolds","The piping that distributes coolant through the blanket and first wall.","Manifolds distribute and collect coolant across the many blanket and first-wall channels, balancing flow so every module is adequately cooled. Their design is part of thermal-hydraulic integration.",["primary-coolant","blanket-module-component","heat-exchanger-component"]),
     ("neutron-streaming","Neutron Streaming","Neutrons leaking through gaps and penetrations in the shield.","Neutrons can stream through ports, gaps and penetrations, reaching places direct shielding would protect. Managing streaming with offsets and local shielding is part of neutronics and layout design.",["shielding","port-plug","neutronics"]),
     ("in-service-inspection","In-Service Inspection","Checking component condition during a machine's operating life.","In-service inspection — often remote — monitors the condition of welds, armour and structures over the machine's life to catch degradation before failure. It ties to maintainability and availability.",["condition-monitoring","remote-handling","maintainability"]),
     ("condition-monitoring","Condition Monitoring","Continuously watching component health with embedded sensors.","Condition monitoring uses embedded sensors — strain, temperature, vibration — to track component health in real time, enabling predictive maintenance. Fibre-optic sensing is one enabling technology.",["fiber-bragg-sensing","in-service-inspection","maintainability"]),
     ("digital-thread","The Digital Thread","Linking design, as-built and operating data across a component's life.","A digital thread ties together a component's design intent, as-built record and operating data, so provenance and history are traceable. It supports quality, maintenance and the eventual digital twin.",["metrology-asbuilt","model-shadow-twin","the-3d-model"]),
     ("metrology-asbuilt","As-Built Metrology","Precisely measuring what was actually built versus what was designed.","As-built metrology measures the real machine to high precision, capturing deviations from design for fit-up, control tuning and the digital record. It is where design meets reality during assembly.",["digital-thread","tolerance-stackup","assembly-sequence"]),
     ("dimensional-control","Dimensional Control","Keeping a large, precise machine within tolerance during fabrication and assembly.","Dimensional control — surveying and adjusting as components are made and joined — keeps a large, high-precision machine within tolerance so everything fits and functions. It is essential for magnets and vessel sectors.",["metrology-asbuilt","tolerance-stackup","assembly-sequence"]),
     ("dose-mapping","Dose Mapping","Predicting radiation fields to plan maintenance access.","Dose mapping computes the radiation field around components after shutdown, planning where and when maintenance can be hands-on or must be remote. It follows from activation analysis.",["contact-dose","activation-analysis","remote-handling"]),
     ("thermal-hydraulics","Thermal-Hydraulics","The coupled heat-and-flow analysis that keeps components cool.","Thermal-hydraulics analyses how coolant removes heat from the first wall, blanket and divertor without exceeding limits. Full computational fluid dynamics here is part of the detailed-design path Kronos flags.",["primary-coolant","high-fidelity-analysis","critical-heat-flux"]),
     ("structural-analysis","Structural Analysis (FEA)","Computing stresses to prove components survive their loads.","Finite-element structural analysis computes stresses and deformations under magnetic, thermal and seismic loads to verify components stay within limits. Full FEA — including fatigue — is scheduled detailed-design work.",["hoop-stress","magnet-fatigue","high-fidelity-analysis"]),
     ("electromagnetic-analysis","Electromagnetic Analysis","Computing the fields, forces and induced currents throughout the machine.","Electromagnetic analysis computes the magnetic fields, Lorentz forces and eddy/halo currents — especially during disruptions — that the structure must withstand. It sets key structural loads.",["lorentz-force","halo-current","eddy-current"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
