# -*- coding: utf-8 -*-
"""Glossary batch 3 — foundational nuclear/plasma terms + burner-specific vocabulary."""

def register(cat, page, F):
    T = [
     ("ion-temperature","Ion Temperature","How hot the fuel ions are; the temperature that drives fusion reactions.",
      [f"Fusion rate depends on the ion temperature, since it is the ions that fuse. HYPERION runs at an ion temperature of {F['b_Ti']}; the D–&sup3;He burner far hotter, around {F['u_Ti']}, because its fuel demands it."],
      ["electron-temperature","reactivity","maxwellian-distribution"]),
     ("electron-temperature","Electron Temperature","How hot the plasma electrons are; it governs radiation and current drive.",
      [f"Electron temperature sets radiation losses and current-drive efficiency and need not equal the ion temperature. In the burner the electrons run at {F['u_Te']}, close to the ion temperature of {F['u_Ti']}."],
      ["ion-temperature","bremsstrahlung","thermal-equilibrium"]),
     ("thermal-equilibrium","Thermal Equilibrium","When plasma species share a common temperature via collisions.",
      ["Given enough collisions, a plasma's particles relax toward a common (Maxwellian) temperature. Whether ions and electrons are in equilibrium with each other affects heating strategy and radiation."],
      ["maxwellian-distribution","ion-temperature","electron-temperature"]),
     ("deuterium","Deuterium","A heavy, stable isotope of hydrogen; the base fuel of every Kronos machine.",
      ["Deuterium is a stable hydrogen isotope with one proton and one neutron, abundant in seawater. It is a component of every Kronos fuel — D–T, D–&sup3;He and D–D — and is effectively inexhaustible."],
      ["tritium","helium-3","fusion-fuels-overview"]),
     ("tritium","Tritium","A radioactive hydrogen isotope, bred in the breeder blanket rather than mined.",
      [f"Tritium is a hydrogen isotope with two neutrons, radioactive with a ~12-year half-life and essentially absent in nature. A D–T plant must breed it; HYPERION's blanket targets {F['b_T']} at breeding ratio {F['b_TBR']}."],
      ["tritium-breeding","deuterium","tritium-inventory"]),
     ("helium-3","Helium-3","A rare, light helium isotope; the burner's fuel and a strategic material.",
      [f"Helium-3 is a rare, non-radioactive helium isotope. It fuels the D–&sup3;He burner and is strategically valuable for quantum and medical uses. The breeder co-produces about {F['b_He3']}, giving Kronos an internal supply path."],
      ["d-he3-fuel","helium-3-supply","tritium"]),
     ("proton-boron-11","Proton–Boron-11 (p–&sup1;&sup1;B)","The truly aneutronic reaction — a long-term research endpoint, not the Kronos baseline.",
      ["Proton–boron-11 fusion produces only charged particles, making it the truly aneutronic reaction. It requires extreme temperatures and remains a research destination. Kronos frames it as a far-future endpoint, not its commercial baseline — and never conflates its low-neutron D–&sup3;He burner with it."],
      ["is-kronos-fusion-aneutronic","d-he3-fuel","fusion-fuels-overview"]),
     ("debye-length","Debye Length","The distance over which a plasma screens out electric fields; below it, collective behaviour dominates.",
      ["The Debye length is the scale over which a plasma shields internal electric fields. Structures larger than it behave collectively as a plasma; it is a basic yardstick of plasma physics."],
      ["plasma","plasma-frequency","plasma-density"]),
     ("magnetic-flux-surface","Magnetic Flux Surface","A nested surface traced by field lines, on which pressure is constant.",
      ["Confined field lines wrap nested toroidal surfaces; plasma pressure and temperature are nearly constant on each. Good confinement means well-formed, nested flux surfaces without islands."],
      ["separatrix","magnetic-shear","tearing-mode"]),
     ("rotational-transform","Rotational Transform","How much a field line rotates poloidally per toroidal circuit — the inverse of the safety factor.",
      ["The rotational transform measures the twist of the field lines; it is the reciprocal of the safety factor. The right amount of twist is what makes the nested flux surfaces that confine the plasma."],
      ["safety-factor","magnetic-flux-surface","stellarator"]),
     ("minimum-b-configuration","Minimum-B Configuration","A field geometry with a central magnetic well that stabilises a mirror plasma.",
      ["Shaping a mirror so the field strength increases in every direction from the centre creates a magnetic well that stabilises interchange instabilities. It is a foundational idea behind stable mirror confinement."],
      ["magnetic-well","interchange-instability","tandem-mirror"]),
     ("magnetic-well","Magnetic Well","A field minimum at the plasma centre that provides MHD stability in mirrors.",
      ["A magnetic well — a central minimum in field strength — gives a mirror plasma good-curvature stability, suppressing the interchange modes that plagued early simple mirrors."],
      ["minimum-b-configuration","interchange-instability","tandem-mirror"]),
     ("interchange-instability","Interchange Instability","A pressure-driven flute-like mode in unfavourable curvature, controlled by minimum-B shaping.",
      ["The interchange (flute) instability swaps hot and cold plasma across the field where curvature is bad. Minimum-B, magnetic-well geometries stabilise it — a key reason modern mirrors are viable."],
      ["magnetic-well","minimum-b-configuration","mhd-stability"]),
     ("sloshing-ions","Sloshing Ions","Anisotropic ions injected at an angle to build a mirror's confining potential.",
      ["Injecting energetic ions at an angle makes them 'slosh' between turning points, peaking their density away from the mirror midplane. This shapes the ambipolar potential that plugs the tandem mirror."],
      ["ambipolar-potential","thermal-barrier","tandem-mirror"]),
     ("thermal-barrier","Thermal Barrier","A potential dip that thermally isolates a tandem mirror's plug electrons.",
      ["A thermal barrier is an electrostatic dip that decouples the hot plug electrons from the central cell, letting the plug build a deeper confining potential for less power. It is part of advanced tandem-mirror design."],
      ["ambipolar-potential","sloshing-ions","plug-density-requirement"]),
     ("expander-tank","Expander / End Tank","The region where a mirror's exhaust plasma spreads out before hitting an end wall or converter.",
      ["Beyond the end plug, the field flares into an expander tank so the escaping plasma spreads over a large area, easing the heat load and feeding the direct converter. It is where the burner recovers end-loss energy."],
      ["direct-energy-conversion","tandem-mirror","venetian-blind-collector"]),
     ("venetian-blind-collector","Venetian-Blind Collector","The angled electrode array of a direct energy converter.",
      [f"A venetian-blind collector is a set of angled, biased electrode rings that decelerate and collect the burner's escaping ions, recovering their energy as electricity at about {F['u_dec']} efficiency."],
      ["direct-energy-conversion","expander-tank","the-burner-design-point"]),
     ("drift-wave","Drift-Wave Turbulence","Small-scale waves driven by pressure gradients; the main source of anomalous transport.",
      ["Drift waves, driven by the plasma's own gradients, grow into the micro-turbulence that leaks heat faster than collisions — the dominant confinement limiter. Sheared flows and magnetic shear suppress them."],
      ["turbulent-transport","gyrokinetics","transport-barrier"]),
     ("gyrokinetics","Gyrokinetic Simulation","The reduced kinetic theory used to simulate plasma micro-turbulence.",
      ["Gyrokinetics averages over the fast gyromotion to make turbulence simulation tractable, predicting transport from first principles. Kronos anchors its confinement to the empirical database, with gyrokinetics as a cross-check rather than a sole basis."],
      ["drift-wave","turbulent-transport","confinement-scaling"]),
     ("transport-barrier","Transport Barrier","A region of suppressed turbulence and steep gradients that boosts confinement.",
      ["A transport barrier is a layer where turbulence is quenched — often by sheared flow — allowing steep pressure gradients and improved confinement. The H-mode pedestal is the best-known example."],
      ["pedestal","l-h-transition","drift-wave"]),
     ("pedestal","The Pedestal","The steep-gradient edge region of an H-mode plasma that sets overall performance.",
      ["The H-mode pedestal is a narrow edge region of steep pressure gradient sitting atop the confinement. Its height strongly influences total performance, and its stability is tied to ELMs."],
      ["h-mode","edge-localized-modes","transport-barrier"]),
     ("l-h-transition","L–H Transition","The sudden jump from low- to high-confinement mode above a power threshold.",
      ["Above a heating-power threshold, a plasma spontaneously transitions from L-mode to the roughly-doubled confinement of H-mode. Reaching the threshold is a design consideration for the breeder's heating."],
      ["h-mode","pedestal","heating-systems"]),
     ("greenwald-fraction","Greenwald Fraction","How close a plasma runs to its empirical density limit.",
      ["The Greenwald fraction is the operating density divided by the Greenwald limit. Running well below 1 is conservative; approaching it raises disruption risk. HYPERION is designed within the limit."],
      ["greenwald-density","plasma-density","disruptions"]),
     ("tritium-inventory","Tritium Inventory","The amount of tritium held in a plant at any time — kept low for safety and accountancy.",
      [f"The tritium inventory is the tritium resident in fuel, blanket and processing at any moment. Keeping it low limits both hazard and startup needs; HYPERION's startup inventory is {F['b_startup']}."],
      ["tritium","fuel-cycle","tritium-permeation"]),
     ("tritium-permeation","Tritium Permeation","The tendency of tritium to diffuse through hot metals, requiring barriers.",
      ["Tritium is small and mobile and permeates hot metals, so plants use permeation barriers and monitoring to control losses. It is a central tritium-handling and licensing consideration."],
      ["tritium-inventory","fuel-cycle","tritium"]),
     ("neutron-multiplier","Neutron Multiplier","A blanket material that multiplies neutrons to raise the tritium breeding ratio.",
      [f"Because each fusion reaction yields one neutron but breeding needs margin, blankets include a neutron multiplier (such as beryllium or lead) to boost the neutron count and lift the breeding ratio toward HYPERION's {F['b_TBR']} target."],
      ["tritium-breeding","blanket","beryllium"]),
     ("breeding-material","Breeding Material","The lithium-bearing material in which neutrons breed tritium.",
      ["Tritium is bred when neutrons strike lithium. Blanket designs use solid ceramics or liquid lithium compounds as the breeding material, chosen to balance breeding ratio, heat recovery and handling."],
      ["blanket","flibe","lithium-blanket"]),
     ("flibe","FLiBe","A molten lithium-beryllium fluoride salt used as breeder and coolant.",
      ["FLiBe (Li&#8322;BeF&#8324;) is a molten salt that can both breed tritium and carry heat, combining several blanket functions. It is one candidate breeding medium studied for D–T plants."],
      ["breeding-material","lithium-blanket","blanket"]),
     ("lithium-blanket","Lithium Blanket","A blanket using lithium to breed tritium and recover heat.",
      ["Lithium — solid ceramic or liquid metal — is the breeding element in the blanket, converting neutrons to tritium while its coolant recovers the neutrons' energy as heat for power conversion."],
      ["breeding-material","flibe","blanket"]),
     ("beryllium","Beryllium","A light metal used as a neutron multiplier and, historically, a plasma-facing material.",
      ["Beryllium multiplies neutrons in the breeding blanket and has served as a low-Z plasma-facing material. Its neutron-multiplying role helps a blanket reach breeding self-sufficiency."],
      ["neutron-multiplier","blanket","plasma-facing-materials"]),
     ("tungsten-divertor","Tungsten Divertor","Tungsten armour on the divertor targets, chosen for its heat tolerance.",
      ["Tungsten has the highest melting point of any metal and low erosion, making it the reference armour for divertor targets facing the harshest heat and particle loads."],
      ["divertor","plasma-facing-materials","heat-flux"]),
     ("cucrzr","CuCrZr Alloy","A copper-chromium-zirconium alloy used for actively-cooled heat-sink structures.",
      ["CuCrZr combines copper's excellent heat conduction with enough strength for structural heat sinks under plasma-facing armour. It is a standard divertor and first-wall heat-sink material."],
      ["tungsten-divertor","first-wall","reflector-liner"]),
     ("hastelloy","Hastelloy Substrate","A nickel alloy forming the strong substrate of REBCO superconducting tape.",
      ["REBCO tape is grown on a strong, corrosion-resistant nickel-alloy (Hastelloy-class) substrate that carries the mechanical load while the thin superconducting layer carries the current."],
      ["rebco-tape","magnet-structure","superconducting-magnets"]),
     ("biological-shield","Biological Shield","The thick shielding that protects people from neutron and gamma radiation.",
      ["A biological shield — typically thick concrete and steel — surrounds the machine to attenuate neutrons and gammas to safe levels outside. Its design follows directly from the neutron source strength."],
      ["shielding","neutron-wall-loading","the-neutron-economy"]),
     ("shielding","Neutron Shielding","Material layers that slow and absorb fusion neutrons to protect magnets and people.",
      ["Shielding between the plasma and the magnets (and the outside world) slows and captures neutrons, protecting the superconductors from damage and staff from dose. It is heaviest on the neutron-rich breeder."],
      ["biological-shield","neutron-damage-materials","blanket"]),
     ("steam-cycle","Thermal (Steam) Cycle","The conventional heat-to-electricity cycle the breeder uses and the burner avoids.",
      ["A thermal cycle boils a working fluid to spin a turbine, converting heat to electricity at Carnot-limited efficiency. The breeder recovers its energy this way; the burner skips it with direct conversion."],
      ["power-conversion","direct-energy-conversion","carnot-efficiency"]),
     ("carnot-efficiency","The Carnot Limit","The thermodynamic ceiling on any heat engine — and why direct conversion is attractive.",
      [f"The Carnot limit caps how efficiently any heat engine turns heat into work, based on its temperatures. Because the burner converts charged-particle energy directly at about {F['u_dec']}, it sidesteps the Carnot ceiling that bounds the breeder's thermal cycle."],
      ["steam-cycle","direct-energy-conversion","power-conversion"]),
     ("neutron-moderation","Neutron Moderation","Slowing fast neutrons so they can breed tritium or be captured.",
      ["Fast fusion neutrons are slowed by scattering in the blanket ('moderation') so they are more likely to breed tritium or be safely captured. It is part of blanket neutronics design."],
      ["blanket","neutron-multiplier","shielding"]),
     ("cross-field-transport","Cross-Field Transport","The leakage of heat and particles across magnetic field lines — what confinement fights.",
      ["Ideally particles stay on their flux surface, but collisions and turbulence let heat and particles drift across field lines. Minimising this cross-field transport is the whole point of confinement design."],
      ["turbulent-transport","neoclassical-transport","energy-confinement-time"]),
     ("beta-poloidal","Poloidal Beta","A pressure ratio using only the poloidal field; it correlates with bootstrap current.",
      ["Poloidal beta compares plasma pressure to the poloidal-field pressure. High poloidal beta goes hand in hand with a large bootstrap fraction, making it a useful design indicator for efficient steady-state operation."],
      ["plasma-beta","bootstrap-fraction","spherical-tokamak"]),
    ]
    def make(slug, term, oneliner, paras, rel):
        page(slug, term, "glossary", oneliner, oneliner, [('p', p) for p in paras],
             related=rel, jtype="DefinedTerm", kicker="Glossary")
    for row in T:
        make(row[0], row[1], row[2], row[3], row[4])
