# -*- coding: utf-8 -*-
"""Codes & standards — the engineering codes a fusion plant designs and builds to."""
def register(cat, page, F):
    cat("standards", "Codes & Standards",
        "The engineering codes and standards a fusion plant is designed, built and licensed "
        "against — from pressure vessels and functional safety to materials and quality.", 11.5)
    S = [
     ("codes-overview","Codes & Standards Overview","A fusion plant is engineered to established industrial and nuclear codes, not invented rules.",
      ["A fusion plant, though novel, is built to the same families of established codes as other heavy industry and nuclear facilities: pressure-vessel codes, functional-safety standards, electrical and structural codes, materials specifications and quality-assurance programmes. Kronos maps which codes apply to which system as part of its construction-readiness work.",
       "Naming the applicable codes — and where a nuclear-grade quality programme still has to be established — is part of an honest readiness assessment."],
      [("Approach","Established codes, honestly mapped")],
      ["asme-bpvc","functional-safety-standards","the-path-to-build"]),
     ("asme-bpvc","ASME Boiler & Pressure Vessel Code","The code governing the vacuum vessel and pressure boundaries.",
      ["The ASME Boiler & Pressure Vessel Code governs the design, fabrication and inspection of pressure-retaining components — for a fusion plant, the vacuum vessel and coolant boundaries. Selecting the applicable section and division is an early code decision.",
       "Kronos identifies BPVC applicability for its vessel and pressure systems."],
      [("Governs","Vessels, pressure boundaries")],
      ["vacuum-vessel","non-destructive-examination","codes-overview"]),
     ("nqa-1","ASME NQA-1","The nuclear-grade quality-assurance standard fusion work moves toward.",
      ["ASME NQA-1 defines a nuclear-grade quality-assurance programme. Establishing an NQA-1-class programme is part of maturing from a design study toward a licensable, buildable plant — an item Kronos flags as work to be done rather than assumed complete.",
       "Honest readiness means naming the quality programme as a gap, not glossing it."],
      [("Governs","Nuclear-grade QA")],
      ["quality-management","codes-overview","the-path-to-build"]),
     ("functional-safety-standards","IEC 61508 / 61511 Functional Safety","The standards governing the safety-instrumented system and its integrity level.",
      ["IEC 61508 and 61511 govern functional safety — the design and verification of safety-instrumented systems to a defined safety-integrity level. They apply to the interlocks that protect a fusion machine, and their verification is a scheduled qualification task.",
       "Kronos sets SIL targets for its protective systems and treats verification as gate work."],
      [("Governs","Safety interlocks (SIL)")],
      ["sis-controller","instrumentation-control","redundancy"]),
     ("electrical-standards","IEEE Electrical Standards","The standards for plant power distribution and protection.",
      ["IEEE standards (for distribution, protection and machinery) govern the plant's high-voltage electrical systems, from grid interconnection to magnet and heating power feeds. This is conventional, mature electrical engineering.",
       "It is among the systems Kronos classes as ready for detailed design."],
      [("Governs","Electrical distribution & protection")],
      ["grid-interconnection","power-supply-converter","balance-of-plant"]),
     ("seismic-standards","ASCE Seismic & Structural Standards","The standards for structural and nuclear-seismic design.",
      ["ASCE structural and nuclear-seismic standards (with the building code) govern how the plant and its supports withstand seismic and structural loads. Site-specific seismic qualification is a defined engineering task on the path to build.",
       "Kronos identifies the applicable structural codes; final qualification is site-specific."],
      [("Governs","Structural & seismic")],
      ["gravity-support-component","systems-integration","the-path-to-build"]),
     ("tritium-standards","Radiological & Tritium Standards","The regulations governing radiological protection and tritium handling.",
      ["Radiological-protection regulations and tritium-handling standards govern dose limits, containment and accountancy for the breeder's tritium. Their fusion-class applicability is under review as regulators develop fusion-specific frameworks.",
       "Tritium handling is one of the breeder's named licensing-relevant gates."],
      [("Governs","Radiological & tritium")],
      ["tritium-safety","tritium-plant","iaea-framework"]),
     ("iaea-framework","IAEA Safety Framework","The international safety guidance the fusion field is adapting.",
      ["The IAEA's safety standards provide an overarching framework that the fusion community is adapting to fusion's distinct, lower hazard profile. Kronos monitors the evolving fusion-specific guidance as part of its regulatory approach.",
       "Fusion's inherent safety means its framework is expected to differ from fission's."],
      [("Governs","Overarching safety")],
      ["inherent-safety","tritium-standards","codes-overview"]),
     ("materials-standards","ASTM Materials Standards","The specifications and test methods for qualifying materials.",
      ["ASTM standards specify material compositions and the test methods used to qualify them. Every structural and plasma-facing material in a fusion plant is characterised against such specifications as part of materials qualification.",
       "Kronos frames material qualification against these standards as scheduled work."],
      [("Governs","Material spec & testing")],
      ["materials-qualification","low-activation-steel","codes-overview"]),
     ("quality-management","ISO 9001 / AS9100 Quality Management","The baseline quality-management systems underpinning the programme.",
      ["ISO 9001 and, for aerospace-grade work, AS9100 define quality-management systems that provide the baseline discipline beneath nuclear-grade QA. Establishing a robust QMS is part of maturing toward a buildable plant.",
       "Kronos treats the QMS baseline as planned programme infrastructure."],
      [("Governs","Quality-management baseline")],
      ["nqa-1","codes-overview","the-path-to-build"]),
     ("cryogenic-standards","Cryogenic Codes","The standards governing cryogenic vessels and safety.",
      ["Cryogenic standards (from bodies such as CGA and the relevant European norms) govern the design and safety of cryogenic vessels and systems — the cryostat, cold box and distribution. This is mature big-science cryogenic practice.",
       "Cryogenics is among the systems Kronos classes as ready for detailed design."],
      [("Governs","Cryogenic vessels & safety")],
      ["cryogenic-system","cold-box","codes-overview"]),
     ("fire-protection-standards","NFPA Fire Protection","The standards for fire protection and life safety.",
      ["NFPA fire-protection and life-safety standards apply to the facility as to any industrial plant, covering fire detection, suppression and egress. It is conventional facility engineering.",
       "It is part of the standard code map for the plant."],
      [("Governs","Fire protection & life safety")],
      ["codes-overview","balance-of-plant","general-arrangement"]),
    ]
    for slug,title,desc,paras,facts,rel in S:
        page(slug,title,"standards",desc,desc,[('p',p) for p in paras],facts=facts,related=rel,jtype="TechArticle")
