# -*- coding: utf-8 -*-
"""Glossary batch 12 — superconductivity, power electronics, vacuum technology."""
def register(cat, page, F):
    T = [
     ("cooper-pair","Cooper Pairs","The bound electron pairs that carry superconducting current without resistance.","Superconductivity arises when electrons bind into Cooper pairs that move through the lattice without scattering, carrying current with zero resistance below the critical temperature. It is the microscopic basis of the magnets that make compact fusion possible.",["superconducting-magnets","critical-temperature","meissner-effect"]),
     ("critical-temperature","Critical Temperature","The temperature below which a material superconducts.","Below its critical temperature a superconductor loses all electrical resistance. REBCO's high critical temperature — well above older superconductors — gives operating margin and is part of why it enables high-field fusion magnets.",["cooper-pair","temperature-margin","rebco-tape"]),
     ("meissner-effect","The Meissner Effect","A superconductor expelling magnetic field — the signature of the superconducting state.","A superconductor actively expels magnetic field from its interior (the Meissner effect), distinguishing true superconductivity from mere perfect conductivity. In high-field magnets the practical regime is more complex, governed by flux pinning.",["flux-pinning","cooper-pair","critical-field"]),
     ("flux-pinning","Flux Pinning","Trapping magnetic flux lines so a superconductor can carry current in high field.","In high-field superconductors, magnetic flux penetrates as quantised lines that must be 'pinned' by material defects so current can flow without loss. Engineering strong pinning is key to REBCO's high current density in high field.",["critical-current","meissner-effect","rebco-tape"]),
     ("quench-propagation","Quench Propagation","How a normal zone spreads through a quenching magnet.","When part of a coil goes normal, the resistive zone heats and spreads; how fast it propagates affects whether protection can act before a hot spot forms. REBCO's slow propagation makes detection especially important.",["quench-detection","normal-zone","quench-protection"]),
     ("normal-zone","Normal Zone","The resistive region that appears when a superconductor quenches.","A normal zone is the patch of a coil that has lost superconductivity and become resistive during a quench, generating heat that must be managed. Detecting and responding to it is the essence of quench protection.",["quench-propagation","quench-detection","hot-spot-temperature"]),
     ("stabilizer","Copper Stabiliser","The conductive layer that carries current if the superconductor quenches.","REBCO tape is co-processed with copper that carries the current if the superconductor goes normal, buying time for protection and limiting local heating. The stabiliser is integral to conductor and quench design.",["rebco-tape","winding-pack","quench-protection"]),
     ("twist-pitch","Cable Transposition","Twisting conductor strands to equalise current and cut AC loss.","Transposing or twisting the strands in a cabled conductor equalises the current each carries and reduces AC loss under changing fields. It is part of engineering a stable, low-loss magnet conductor.",["ac-loss","winding-pack","eddy-current"]),
     ("rectifier-inverter","Rectifiers & Inverters","Power electronics that convert between AC and DC for magnets and drives.","Rectifiers convert grid AC to the DC that magnets and some heating systems need; inverters do the reverse for the burner's output. These power-electronic converters are large but conventional.",["power-supply-converter","thyristor","power-quality"]),
     ("thyristor","Thyristor & IGBT Converters","The switching devices at the heart of high-power converters.","Thyristors and insulated-gate bipolar transistors are the semiconductor switches that build high-power converters for magnets, heating and conversion. Their ratings and speed set converter capability.",["rectifier-inverter","power-supply-converter","quench-protection"]),
     ("crowbar-circuit","Crowbar & Protection Circuits","Fast protective circuits that shunt current away from faults.","A crowbar circuit rapidly shunts current to protect equipment during a fault, complementing breakers and dump resistors. Such protection circuits keep the high-power systems safe.",["quench-protection","dump-switch","thyristor"]),
     ("conductance","Vacuum Conductance","How readily gas flows through a vacuum system — it limits pumping.","Conductance measures how easily gas moves through ducts and apertures; even a large pump is throttled by poor conductance. Vacuum-system design maximises conductance to the plasma chamber.",["pumping-speed","vacuum-system","outgassing"]),
     ("outgassing","Outgassing","Gas slowly released from surfaces that vacuum systems must remove.","Materials slowly release adsorbed gas into the vacuum (outgassing), a load the pumps must handle to reach base pressure. Baking surfaces drives it off, which is why vessels are baked before operation.",["bakeout","vacuum-system","base-pressure"]),
     ("bakeout","Vessel Bakeout","Heating the vessel to drive off adsorbed gas and reach high vacuum.","Baking the vacuum vessel to elevated temperature accelerates outgassing so the system can reach ultra-high vacuum. It is a routine conditioning step before plasma operation.",["outgassing","wall-conditioning","vacuum-system"]),
     ("base-pressure","Base Pressure","The lowest pressure a vacuum system reaches before operation.","Base pressure is the residual gas pressure achieved before fuelling — very low, so stray gas does not cool or contaminate the plasma. Reaching it is a cold-commissioning milestone.",["vacuum-system","outgassing","cold-commissioning"]),
     ("leak-detection","Vacuum Leak Detection","Finding and fixing leaks that would spoil the vacuum.","Leak detection, typically with helium tracer gas, locates flaws in the vacuum boundary so they can be repaired. A leak-tight vessel is essential to plasma operation and is verified during commissioning.",["vacuum-vessel","non-destructive-examination","base-pressure"]),
     ("lithium-6","Lithium-6 and Enrichment","The lithium isotope that breeds tritium most effectively.","Lithium-6 breeds tritium far more readily than lithium-7, so blankets often use lithium enriched in lithium-6 to reach the target breeding ratio. Enrichment level is a blanket-design lever.",["tritium-breeding","breeding-material","lithium-blanket"]),
     ("nuclear-data-library","Nuclear Data Libraries","The evaluated cross-sections that neutronics calculations depend on.","Neutronics relies on evaluated nuclear-data libraries (such as ENDF) giving reaction cross-sections versus energy. The quality of these data underpins breeding, activation and shielding predictions.",["neutronics","monte-carlo-neutronics","activation-products"]),
     ("monte-carlo-neutronics","Monte-Carlo Neutronics","Simulating neutron transport by tracking many random histories.","Monte-Carlo codes (such as MCNP) track millions of simulated neutron histories to compute breeding, heating, damage and shielding in complex geometry. It is the high-fidelity neutronics Kronos flags as scheduled detailed-design work.",["neutronics","nuclear-data-library","high-fidelity-analysis"]),
     ("activation-analysis","Activation Analysis","Computing which radioactive isotopes neutrons create, and how they decay.","Activation codes predict the radioactive isotopes formed in materials under neutron irradiation and their decay, feeding waste classification and dose planning. It is how the low-activation strategy is verified.",["activation-products","waste-classification","monte-carlo-neutronics"]),
     ("loss-of-coolant","Loss-of-Coolant Analysis","Checking that losing coolant cannot cause a fusion accident.","A loss-of-coolant analysis confirms that even if cooling fails, a fusion plant cannot run away — the plasma stops and decay heat is small and passively manageable. It is a core part of the inherently favourable fusion safety case.",["decay-heat","inherent-safety","passive-safety"]),
     ("loss-of-vacuum","Loss-of-Vacuum Analysis","Assessing the benign consequences of a vacuum breach.","A loss-of-vacuum event lets air in, which stops the plasma and is bounded by the small energy and tritium inventories involved. Analysing it is part of demonstrating fusion's limited accident potential.",["inherent-safety","tritium-safety","vacuum-vessel"]),
     ("passive-safety","Passive Safety","Safety that relies on physics, not active systems.","Passive safety means the machine stays safe through inherent physics — no chain reaction, tiny fuel inventory, small decay heat — without needing active intervention. It is the foundation of fusion's safety advantage.",["inherent-safety","loss-of-coolant","decay-heat"]),
     ("source-term","Radiological Source Term","The inventory of radioactive material that bounds worst-case releases.","The source term is the amount of mobilisable radioactive material (chiefly tritium and activated dust) that bounds any accidental release. Fusion's small source term is central to its favourable safety case.",["tritium-inventory","radiation-protection","passive-safety"]),
     ("confinement-barriers","Confinement Barriers","The nested barriers that keep radioactive material contained.","Multiple nested barriers — vacuum boundary, building confinement, ventilation with detritiation — contain tritium and activated material. Defence-in-depth confinement is standard practice adapted to fusion's modest source term.",["secondary-containment","source-term","radiation-protection"]),
     ("deuterium-extraction","Deuterium from Water","How the abundant fuel is obtained.","Deuterium makes up a small, fixed fraction of natural hydrogen and is separated from water at industrial scale. It is abundant, cheap and effectively inexhaustible — the reason fuel supply is not a fusion constraint.",["deuterium","heavy-water","fusion-fuels-overview"]),
     ("heavy-water","Heavy Water","Deuterium-rich water, a source of the fuel.","Heavy water (deuterium oxide) is water enriched in deuterium, produced industrially and a practical deuterium source. It illustrates how ordinary and abundant fusion's primary fuel input is.",["deuterium-extraction","deuterium","catalyzed-dd"]),
     ("dc-link","DC Link & Energy Buffering","The DC stage that buffers power between conversion stages.","In power-electronic systems a DC link buffers energy between the rectifier and inverter stages, smoothing delivery. On the burner it sits between direct conversion and the grid interface.",["rectifier-inverter","direct-energy-conversion","power-quality"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
