# -*- coding: utf-8 -*-
"""Glossary batch 17 — plasma-material interaction, current physics, heating figures."""
def register(cat, page, F):
    T = [
     ("physical-sputtering","Physical Sputtering","Wall atoms knocked out by the momentum of impacting ions.","Physical sputtering ejects surface atoms when energetic ions transfer enough momentum, eroding plasma-facing materials and releasing impurities. Choosing high-threshold materials like tungsten limits it.",["sputtering","erosion","tungsten-armor"]),
     ("chemical-sputtering","Chemical Sputtering","Erosion by chemical reactions between plasma and wall.","Chemical sputtering erodes a surface through chemical reactions (notably carbon with hydrogen), forming volatile compounds. It is one reason carbon has largely given way to metallic plasma-facing materials.",["physical-sputtering","erosion","plasma-facing-materials"]),
     ("unipolar-arc","Plasma Arcing","Electrical arcs at the wall that damage surfaces and shed impurities.","Strong sheath potentials can strike arcs between plasma and wall, gouging the surface and injecting impurities. Managing arcing protects plasma-facing components and purity.",["plasma-sheath","erosion","impurity-transport"]),
     ("vapor-shielding","Vapour Shielding","A protective vapour cloud that forms under extreme transient heat.","Under a very intense transient (like a large ELM or disruption), the surface can vaporise into a cloud that radiates and shields the material beneath — vapour shielding. It is a mitigating effect but signals damaging conditions.",["disruption-load","elm-heat-load","erosion"]),
     ("magnetic-helicity","Magnetic Helicity","A conserved measure of magnetic-field twist and linkage.","Magnetic helicity quantifies the twist and linkage of field lines and is nearly conserved even as a plasma relaxes. It underlies self-organisation phenomena in some confinement concepts.",["taylor-relaxation","rotational-transform","spheromak"]),
     ("taylor-relaxation","Taylor Relaxation","A plasma relaxing to a minimum-energy state at fixed helicity.","Taylor's principle says a turbulent plasma relaxes toward a minimum-energy state while conserving magnetic helicity, explaining self-organised configurations like spheromaks and reversed-field pinches.",["magnetic-helicity","spheromak","self-organization"]),
     ("self-organization","Plasma Self-Organisation","Turbulent plasmas settling into ordered magnetic states on their own.","Some plasmas spontaneously organise into ordered magnetic structures through relaxation, needing less external shaping. It is a defining feature of alternative concepts and a contrast to the tokamak's externally-imposed order.",["taylor-relaxation","field-reversed-configuration","spheromak"]),
     ("neoclassical-conductivity","Neoclassical Conductivity","Trapped particles reducing a plasma's effective conductivity.","Trapped particles reduce the plasma's effective electrical conductivity below the simple Spitzer value, a neoclassical effect that also gives rise to the bootstrap current. It matters for current drive and profile evolution.",["spitzer-resistivity","bootstrap-current","trapped-particles"]),
     ("current-relaxation","Current-Profile Relaxation","The resistive evolution of the current toward a relaxed profile.","Left alone, the plasma current diffuses resistively toward a relaxed profile over the resistive time, which can move the safety-factor profile. Heating and current drive are used to hold a favourable profile.",["current-diffusion","current-profile","q-profile"]),
     ("current-drive-efficiency","Current-Drive Efficiency","How much current each watt of external power drives — a key economic lever.","Current-drive efficiency (amperes per watt) sets how much power a steady-state tokamak must spend sustaining its current, directly affecting recirculating power. Raising it, and the bootstrap fraction, improves the energy ledger.",["current-drive","bootstrap-fraction","recirculating-power"]),
     ("single-pass-absorption","Single-Pass Absorption","Whether heating power is absorbed in one pass through the plasma.","Good heating schemes absorb their power in a single pass through the plasma; poor absorption sends power to the walls and lowers efficiency. It is a design criterion for RF and beam systems.",["wave-heating","fast-wave-heating","beam-shinethrough"]),
     ("burn-fraction","Fuel Burn Fraction","The share of injected fuel that actually fuses before being exhausted.","Only a fraction of fuel fuses on each pass before it is exhausted and recycled; the burn fraction, with fuelling efficiency, sets how much fuel throughput a plant needs. It links plasma physics to the fuel cycle.",["fuel-cycle","tritium-burn-efficiency","fueling-efficiency"]),
     ("tritium-burn-efficiency","Tritium Burn Efficiency","How efficiently injected tritium is consumed — it drives inventory needs.","Tritium burn efficiency measures how much injected tritium fuses versus is recycled; low efficiency means large throughput and inventory. Improving it eases the fuel cycle and tritium accountancy.",["burn-fraction","tritium-inventory","fuel-cycle"]),
     ("stray-field","Stray & Fringe Fields","Magnetic fields extending beyond the machine that must be managed.","High-field magnets produce stray fields around the machine that must be shielded or sited for, to protect equipment and people. It is a practical facility-design consideration for compact, high-field machines.",["high-field-magnets","magnetic-shielding","general-arrangement"]),
     ("ramp-rate","Magnet Ramp Rate","How fast a magnet can be charged without losing stability.","The ramp rate limits how quickly a superconducting magnet is energised, bounded by AC losses and stability. It affects start-up time and, for no-insulation coils, is a specific design trade.",["ac-loss","cryogenic-stability","no-insulation-coil"]),
     ("magnetic-shielding","Magnetic Shielding","Ferromagnetic or active shielding that contains stray fields.","Ferromagnetic shields or bucking coils contain a magnet's stray field near sensitive equipment. It is part of integrating high-field magnets into a working facility.",["stray-field","high-field-magnets","systems-integration"]),
     ("functionally-graded-material","Functionally-Graded Materials","Materials that transition gradually to bond dissimilar parts.","Functionally-graded materials transition composition gradually to bond dissimilar materials — such as tungsten armour to copper heat sink — reducing thermal-stress mismatch. They are an enabling joining technology for plasma-facing components.",["hip-bonding","plasma-facing-materials","thermal-fatigue"]),
     ("thermal-barrier-coating","Thermal & Functional Coatings","Thin coatings that protect surfaces or control their properties.","Coatings can protect surfaces from heat or erosion, control tritium permeation, or tailor reflectivity — as on the burner's liner. They are a materials-engineering tool used throughout the machine.",["reflector-liner","tritium-permeation","plasma-facing-materials"]),
     ("alara","ALARA Principle","Keeping radiation exposure As Low As Reasonably Achievable.","ALARA is the guiding radiological-protection principle: reduce doses as far as reasonably practical, not merely below limits. It shapes shielding, remote handling and maintenance design.",["radiation-protection","dose-to-public","remote-handling"]),
     ("critical-materials","Critical & Rare Materials","Scarce inputs like helium-3 and rare earths — and how Kronos manages them.","A few inputs are genuinely scarce: helium-3 (which the breeder makes itself) and the rare earths in REBCO tape (used in small quantities). Kronos's neutron economy turns the scarcest input into an internal product rather than a dependency.",["helium-3-supply","rebco-tape","material-abundance"]),
     ("material-abundance","Material Abundance","How common a technology's key materials are — mostly favourable for fusion.","Fusion's core inputs are abundant: deuterium from water, lithium for breeding, common structural metals. The scarce exceptions are managed deliberately, making material supply a strength rather than a constraint.",["deuterium","lithium-6","critical-materials"]),
     ("recyclability","Material Recyclability","Reusing decommissioned materials once they clear activity limits.","Because fusion's activated materials mostly decay to clearance within decades, much of a decommissioned plant can eventually be recycled rather than disposed of. It strengthens the lifecycle and resource case.",["clearance-level","waste-processing","lifecycle-assessment"]),
     ("thermal-storage","Thermal Storage & Load Following","Storing heat to help a plant follow demand.","A thermal plant can store heat to decouple generation from demand, aiding load-following. Combined with a driven machine's inherent dispatchability, it adds flexibility to firm fusion output.",["dispatchable-power","steam-cycle","load-following"]),
     ("load-following","Load-Following Capability","Adjusting output to match changing demand.","Load-following is the ability to raise and lower output as demand changes. A driven fusion machine, steered by its heating, can follow load — an advantage over baseload-only or intermittent sources.",["dispatchable-power","burn-control","thermal-storage"]),
    ]
    for slug,term,one,para,rel in T:
        page(slug,term,"glossary",one,one,[('p',para)],related=rel,jtype="DefinedTerm",kicker="Glossary")
