# -*- coding: utf-8 -*-
"""FAQ batch 2 — more real questions serious readers ask."""

def register(cat, page, F):
    Q = [
     ("when-will-fusion-be-ready","When will fusion be ready?",
      "Kronos gives gate-based milestones, not a fixed date — and stages a saleable product ahead of net electricity.",
      ["Kronos does not promise a calendar date. It advances through evidence-based gates (G1–G4), and, crucially, stages a saleable product — tritium, neutrons, isotopes — ahead of the hardest net-electric milestone. That decouples early value from the longest-pole physics.",
       "Anyone quoting a precise fusion date should be treated with caution; Kronos quotes gates and what closes each."],
      ["gate-reviews","the-path-to-build","the-breeder-first-strategy"]),
     ("how-is-kronos-different","What makes Kronos different from other fusion startups?",
      "A breeder-first, two-machine strategy with a product before net electricity — and a verifiably honest, open record.",
      ["Two things. First, the architecture: rather than racing one D–T tokamak to net electricity, Kronos builds a breeder that sells fuel, neutrons and isotopes first, and a low-neutron burner for clean direct-conversion electricity. Second, the posture: every number is open and reproducible, and every caveat is stated on the same page as the claim.",
       "The bet is that a saleable product plus verifiable honesty is a stronger position than a single hero number."],
      ["the-breeder-first-strategy","how-is-kronos-honest","kronos-vs-dt-tokamak"]),
     ("how-is-kronos-honest","How does Kronos stay honest about its claims?",
      "By publishing reproducible engines, labelling requirement-class results, and naming its gates — as policy.",
      ["Honesty is operationalised: the engines behind every number are deposited openly and reproduce; requirement-class results (like burner net power) are labelled as such; low-neutron is never called aneutronic; and the binding gates are named on the pages that discuss them.",
       "The point is that serious diligence finds caveats anyway — so Kronos states them first, turning honesty into credibility."],
      ["honesty-framework","reproducibility-overview","what-are-the-open-questions"]),
     ("is-the-3d-model-real","Is the interactive 3D model a real machine?",
      "It is a physics-grounded design instrument, not a mirror of operating hardware — and it says so.",
      [f"The model is a schematic, physics-grounded design tool: a rotatable reactor, an in-browser solver, and the full frozen design point (breeder Q = {F['b_Q']}, burner Q<sub>E</sub> = {F['u_QE']}). It is stage one of a model &rarr; shadow &rarr; digital-twin progression — a design instrument, not a live twin of a machine that does not yet exist (construction of the HYPERION breeder is scheduled to begin in Q2 2027).",
       "Kronos labels it as schematic rather than letting its polish imply as-built hardware."],
      ["the-3d-model","model-shadow-twin","has-kronos-built-a-reactor"]),
     ("why-a-breeder-if-it-loses-money","Why build the breeder if electricity is not its product?",
      "Because its products — tritium, neutrons, isotopes, helium-3 — have value independent of net-electric fusion.",
      ["The breeder is not trying to sell electricity. Its outputs — scarce tritium, a high neutron flux, medical isotopes and strategic helium-3 — are valuable in themselves, giving Kronos a business that does not wait on the field's hardest milestone.",
       "Building the neutron-and-fuel machine first is what de-risks the whole programme."],
      ["the-breeder-first-strategy","the-neutron-economy","tritium-supply"]),
     ("can-fusion-follow-demand","Can a fusion plant follow demand, or only run flat-out?",
      "A driven machine is steerable by its heating, so it can in principle follow load, not just run baseload.",
      ["Because Kronos machines are driven — continuously heated rather than self-igniting — turning the heating up or down steers the output. That makes them dispatchable in principle, able to follow load like a gas plant, as well as provide steady baseload.",
       "Dispatchability is an operational advantage over intermittent renewables."],
      ["dispatchable-power","ignition-vs-driven","baseload-power"]),
     ("what-happens-if-something-fails","What happens if something fails mid-operation?",
      "The plasma simply cools and stops within seconds — there is no stored energy to run away.",
      ["A fusion plasma needs precisely maintained conditions and holds only seconds of fuel. Any fault, leak or power loss makes it lose confinement and extinguish almost immediately. Unlike fission, there is no chain reaction and no decay-heat-driven runaway to worry about.",
       "The burner, as a linear mirror, additionally avoids the tokamak disruption failure mode."],
      ["inherent-safety","can-a-fusion-plant-melt-down","disruptions"]),
     ("does-fusion-produce-waste","Does fusion produce radioactive waste?",
      "No long-lived high-level waste — only activated structure, kept short-lived by material choice.",
      ["Fusion makes no spent fuel and no long-lived high-level waste. Its only waste is structural metal made mildly radioactive by neutrons; low-activation materials keep that short-lived, decaying to hands-on levels in decades. The neutron-rich breeder carries most of it; the burner very little.",
       "Kronos screens waste volumes and activation per component rather than assuming the issue away."],
      ["fusion-waste","low-activation-steel","activation-products"]),
     ("what-is-the-plug-density-ratio","What is the plug-density ratio and why does it matter?",
      "It is the burner's binding requirement — the plug must reach ~"+F["u_np"]+"&times; the central density to confine the plasma.",
      [f"In the tandem-mirror burner, the end plugs must reach a density about {F['u_np']}&times; that of the central cell to build a deep enough electrostatic potential to confine the central ions. The burner's net-positive operation depends on it, which is why Kronos labels that net power requirement-class.",
       "It is the single most important honest caveat on the burner, and Kronos states it openly."],
      ["plug-density-requirement","ambipolar-potential","whats-the-catch-with-the-burner"]),
     ("can-i-see-the-data","Can I see the data behind Kronos?",
      "Yes — five open Zenodo deposits contain the engines, inputs and expected outputs, free to download and re-run.",
      ["Yes. The reduced-order engines, input decks and expected outputs are deposited openly on Zenodo under CC BY 4.0 — breeder, burner, REBCO magnets, direct energy conversion, and the AI/quantum record. You can download them and reproduce the published numbers yourself.",
       "This is the core of the Kronos model: check us, don't trust us."],
      ["the-open-deposits","how-to-reproduce","reproducibility-overview"]),
     ("is-kronos-peer-reviewed","Is the Kronos work peer-reviewed?",
      "The deposits are openly reproducible now; conventional peer review through arXiv and journals is in preparation.",
      ["The open, reproducible deposits let anyone check the work today. In parallel, Kronos is pursuing the conventional peer-review path — preprints and journal or IAEA submissions — so the work is scrutinised through both mechanisms. Reproducibility and peer review are complementary, not substitutes.",
       "Status updates on the peer-review track are published as they progress."],
      ["peer-review-track","reproducibility-overview","the-open-deposits"]),
     ("why-two-fuels","Why does Kronos use two different fuels?",
      "Because fuel should follow purpose: D–T to breed and make neutrons, D–&sup3;He to make clean electricity.",
      ["The breeder uses neutron-rich D–T because its job is to make tritium and neutrons. The burner uses low-neutron D–&sup3;He because its job is to make electricity cleanly and by direct conversion. Optimising each machine for a different fuel is the whole idea — 'fuel follows purpose, not platform.'"],
      ["fusion-fuels-overview","the-breeder-first-strategy","d-he3-fuel"]),
    ]
    for slug,q,oneliner,ans,rel in Q:
        page(slug,q,"faq",oneliner,oneliner,[('qa',[(q," ".join(f"<p>{a}</p>" for a in ans))])],
             related=rel,jtype="FAQPage",kicker="Question")
