# -*- coding: utf-8 -*-
"""Glossary depth batch D — waves, drifts, MHD modes, edge/exhaust physics."""
def register(cat, page, F, enrich):
    G = {
     "debye-length": "The Debye length is the scale below which a plasma's charges screen out electric fields; structures larger than it behave collectively as a plasma. It is tiny in a fusion plasma, which is why the plasma stays quasineutral almost everywhere and why the sheath at a wall is so thin.",
     "plasma-frequency": "The plasma frequency, set by density, decides which electromagnetic waves a plasma reflects and which pass through, governing both heating schemes and diagnostics like interferometry and reflectometry. A wave below the local cutoff is reflected, which is why launch frequency and geometry are chosen so heating power reaches its resonant layer.",
     "gyrofrequency": "The gyrofrequency, proportional to field strength, is the rate a particle spirals around a field line, and tuning radio waves to it heats the plasma resonantly — the basis of ion- and electron-cyclotron heating. Because it maps to field and hence position, the plasma's own cyclotron emission also provides a temperature-profile diagnostic.",
     "toroidal-field": f"The toroidal field is the dominant confining field, running the long way around the torus, and its strength sets how tightly the plasma is held. HYPERION's is {F['b_B0']} on axis, rising to {F['b_Bpeak']} at the REBCO conductor — the high-field frontier that lets a compact machine perform.",
     "poloidal-field": "The poloidal field, produced mainly by the plasma current with shaping coils for control, wraps the short way around and combines with the toroidal field to make the helical field lines that confine the plasma. Poloidal-field coils are the actuators the shape- and position-control system drives in real time.",
     "magnetic-shear": "Sheared field lines tear apart small instabilities and turbulent eddies, so magnetic shear is a stabilising design knob. Its distribution, set by the current profile, decides where modes can grow and enables advanced regimes like reversed-shear operation with internal transport barriers.",
     "trapped-particles": "In a torus the field is weaker on the outboard side, so some particles are mirror-reflected and bounce rather than circulate, tracing banana orbits. Trapped particles drive both the neoclassical transport that sets the confinement floor and the bootstrap current that reduces external drive — two effects that come together in a well-designed plasma.",
     "current-drive-x": "",
     "exb-drift": "The E&times;B drift moves all particles at the same velocity regardless of charge, so it does not separate charge but does set bulk rotation and edge flows. Sheared E&times;B flow is one of the main mechanisms that suppresses turbulence, underlying both the H-mode edge barrier and internal transport barriers.",
     "curvature-drift": "Curvature and gradient drifts push ions and electrons in opposite directions, which in a straight field would separate charge and destroy confinement — the very problem the tokamak's twisted field and the mirror's shaping exist to cancel. Understanding them is understanding why closed, rotationally-transformed field lines are necessary.",
     "sawtooth-oscillation": "Sawteeth are repetitive core temperature collapses driven by an internal kink and magnetic reconnection when the central safety factor drops below one. Usually tolerable on their own, they can seed the larger neoclassical tearing modes that limit performance, so they are actively managed with heating and current drive.",
     "tearing-mode": "Tearing modes let magnetic surfaces reconnect into islands that short-circuit confinement across them, and the neoclassical variety is a leading performance limiter. The standard cure is surgical: drive replacement current at the island with steerable electron-cyclotron waves, restoring the surface.",
     "neoclassical-tearing-mode": "An NTM is a magnetic island sustained by the loss of bootstrap current inside it, and it can clamp the achievable beta well below the ideal limit. Because it grows from a seed (often a sawtooth), avoiding large sawteeth and driving replacement current with ECRH are the two levers used to keep it in check.",
     "kink-instability": "The kink is a current-driven mode that bends the plasma column when the current is too high for the field, and the external kink is the most dangerous ideal instability. Keeping the edge safety factor above about two, as HYPERION does, avoids it and effectively caps the plasma current for a given field.",
     "disruption-mitigation": "When a disruption cannot be avoided, mitigation systems flood the plasma with impurity gas or a shattered pellet so its energy radiates uniformly rather than striking one spot, limiting heat loads, forces and runaway electrons. The linear tandem-mirror burner avoids this failure mode entirely, which is one of its architectural safety advantages.",
     "runaway-electrons": "During a disruption's current quench, electric fields can accelerate a beam of electrons to tens of MeV that, uncontrolled, would gouge the wall. Preventing or dissipating this beam is a core part of disruption mitigation on any tokamak — and a problem the disruption-free burner does not have.",
     "pedestal": "The H-mode pedestal is a narrow edge region of steep pressure gradient whose height, through profile stiffness, strongly sets the whole plasma's performance. Its stability is tied to peeling-ballooning modes and ELMs, which is why edge configuration choices like negative triangularity matter so much.",
     "l-h-transition": "Above a heating-power threshold the plasma spontaneously jumps to the roughly-doubled confinement of H-mode, so a machine's heating must comfortably exceed that threshold to operate in the high-confinement regime. The transition is one of fusion's most consequential empirical discoveries and underlies the confinement Kronos assumes.",
     "drift-wave": "Drift waves, driven by the plasma's own gradients, grow into the micro-turbulence that leaks heat faster than collisions and dominates transport. Sheared flows and magnetic shear suppress them, which is why the physics of turbulence suppression is really the physics of confinement.",
     "transport-barrier": "A transport barrier is a layer where turbulence is quenched — usually by sheared flow — allowing steep gradients and improved confinement. The H-mode pedestal is the edge example; a reversed-shear core can host an internal one, and together they define the high-performance regimes a power plant aims for.",
     "gyrokinetics": "Gyrokinetics averages over the fast gyration to make turbulence simulation tractable, predicting transport from first principles. Kronos treats it as a cross-check rather than a foundation: its confinement targets are anchored to the empirical database, so the design does not stand or fall on turbulence modelling.",
     "detachment": "In detachment, the divertor plasma is cooled by radiation and neutrals until it lifts off the target, dramatically cutting the peak heat flux. It is the key technique for protecting the divertor and is tied directly to HYPERION's high-radiated-fraction strategy and its named performance gate.",
     "neutral-recycling": "Ions reaching the wall neutralise and return as gas to be re-ionised, and this recycling flux governs edge density and strongly shapes the divertor. High recycling makes density control harder but also feeds the cold, dense divertor conditions that enable detachment.",
     "greenwald-fraction": "The Greenwald fraction — operating density over the empirical limit — is a compact measure of how aggressively a tokamak is running. Well below one is conservative; approaching one raises disruption risk. HYPERION is designed within the limit, while the burner is free of it entirely.",
     "quasineutrality": "Beyond the tiny Debye length a plasma keeps its positive and negative charge densities nearly equal, because any imbalance sets up strong restoring fields. Quasineutrality is exactly the constraint that produces the ambipolar physics the tandem-mirror burner exploits to plug its ends.",
     "current-profile": "The radial distribution of plasma current sets the safety-factor profile and therefore stability, so tailoring it — with heating and current drive — is a primary tool for avoiding tearing modes and reaching advanced scenarios. Its slow resistive relaxation is why current-profile control must be applied over the whole discharge.",
     "safety-factor-x": "",
     "bootstrap-fraction": f"A higher bootstrap fraction means less external current drive and therefore lower recirculating power, so it is a direct efficiency lever bounded by stability. HYPERION's {F['b_fbs']} bootstrap fraction reduces but does not eliminate the drive it needs, which is why it also relies on efficient beam and RF current drive for steady state.",
     "power-exhaust": "Getting the fusion power out without destroying the components it flows through is one of fusion's hardest problems, because concentrating it on a small divertor can exceed material limits. Radiating most of the exhaust before it lands is the primary tool — the basis of HYPERION's high-radiated-fraction divertor and a genuine performance gate.",
     "plasma-shaping": f"Shaping — the combination of elongation ({F['b_kappa']}) and triangularity ({F['b_delta']}) — controls how much current and pressure a plasma holds and how stable it is. HYPERION's tall, negative-triangularity cross-section is a deliberate performance-and-stability choice, and one of the spherical tokamak's natural strengths.",
    }
    for k in ("current-drive-x","safety-factor-x"): G.pop(k, None)
    for slug, para in G.items():
        if para: enrich(slug, add_body=[('p', para)])
